# -*- coding: utf-8 -*-
"""GitHub 從零到協作：模組 A～D（第 1～28 課）。"""
from gh_common import *

_AREAS = ghw({"t": "areas", "q": u"三個區域模擬器：編輯、add、commit，看檔案在哪裡。"})

_GRAPH = ghw({"t": "graph", "q": u"分支模擬器：按按鈕或自己輸入指令，看 commit 圖怎麼變。"})

_SNAP = svg(
    title(u"每個 commit 都是整個專案的快照，並指向上一個 commit"),
    box(30, 60, 150, 80, u"commit 582091b", [u"初始提交", u"README.md"], BLUE),
    box(245, 60, 150, 80, u"commit edad20f", [u"加入 app.py", u"README.md、app.py"], BLUE),
    box(460, 60, 150, 80, u"commit 880269e", [u"app.py 多印一行", u"README.md、app.py'"], GREEN),
    A(245, 100, 180, 100, MUTED), A(460, 100, 395, 100, MUTED),
    T(320, 170, u"箭頭方向：新的 commit 記得「我的上一個是誰」（parent）；舊的不知道未來", 10.5, MUTED),
)

_THREE = svg(
    title(u"Git 的三個區域與搬運指令"),
    box(20, 60, 170, 90, u"工作目錄", [u"你看得到、正在改的檔案"], ORANGE),
    box(235, 60, 170, 90, u"暫存區（index）", [u"「下一個 commit」的草稿"], PURPLE),
    box(450, 60, 170, 90, u"儲存庫（.git）", [u"所有 commit 的歷史"], BLUE),
    A(190, 90, 235, 90, GREEN), T(212, 82, u"git add", 10, GREEN),
    A(405, 90, 450, 90, GREEN), T(427, 82, u"git commit", 10, GREEN),
    A(235, 125, 190, 125, RED), T(212, 142, u"git restore", 10, RED),
    A(450, 125, 405, 125, RED), T(427, 142, u"restore --staged", 9, RED),
)

_DIST = svg(
    title(u"分散式：每個人的電腦都有完整的歷史"),
    box(240, 40, 160, 70, u"GitHub 上的倉庫", [u"origin（遠端）"], GREEN),
    box(30, 160, 160, 70, u"你的筆電", [u"完整的 .git"], BLUE), box(240, 160, 160, 70, u"同事的電腦", [u"完整的 .git"], BLUE), box(450, 160, 160, 70, u"CI 伺服器", [u"完整的 .git"], BLUE),
    A(110, 160, 260, 110, MUTED), A(320, 160, 320, 110, MUTED), A(530, 160, 380, 110, MUTED),
    T(320, 255, u"push 把 commit 送上去，fetch／pull 把別人的 commit 拿下來", 10.5, MUTED),
)

MODULE_A = (u"模組 A｜觀念入門", [

lesson(u"Git 和 GitHub 不一樣",
  u"工具與平台",
  [u"分清楚 Git 與 GitHub", u"知道 GitHub 提供了哪些 Git 沒有的東西", u"認識其他類似平台"],
  [("p", u"很多人把 Git 和 GitHub 混為一談，其實它們是兩樣東西："),
   ("t", [u"", u"Git", u"GitHub"],
    [[u"是什麼", u"一個<strong>版本控制工具</strong>（軟體）", u"一個<strong>網站</strong>（雲端服務）"], [u"在哪裡跑", u"你的電腦上", u"GitHub 的伺服器上"],
     [u"誰做的", u"Linus Torvalds 在 2005 年為了管理 Linux 原始碼而寫", u"2008 年成立的公司，2018 年被微軟收購"],
     [u"沒網路能用嗎", u"可以，完全離線也能工作", u"不行"], [u"提供什麼", u"記錄歷史、分支、合併", u"存放倉庫、Pull Request、Issue、Actions、網頁、權限管理⋯⋯"]]),
   ("p", u"比喻：Git 像是「文書處理軟體裡的追蹤修訂」，GitHub 像是「讓大家一起編輯文件的雲端硬碟＋討論區」。你可以只用 Git 不用 GitHub；但 GitHub 上的一切，都建立在 Git 之上。"),
   ("p", u"類似 GitHub 的平台還有 <strong>GitLab</strong>、<strong>Bitbucket</strong>、<strong>Gitea</strong> 等。它們底層都是 Git，所以本課程的 Git 部分在這些平台上通用；只有網站操作（Pull Request 在 GitLab 叫 Merge Request）略有不同。"),
  ],
  u"Git 是 Linus Torvalds 在 2005 年寫的版本控制工具，在你的電腦上運作、可完全離線；GitHub 是 2008 年成立、2018 年被微軟收購的雲端平台，在 Git 之上提供存放倉庫、Pull Request、Issue、Actions 等協作功能。GitLab、Bitbucket 等平台底層也是 Git。",
  [u"Git 和 GitHub 哪一個需要網路？", u"Git 是誰、為了什麼寫的？", u"GitHub 提供了哪些 Git 本身沒有的功能？"]),

lesson(u"為什麼需要版本控制",
  u"從「報告_最終版_真的最終版」說起",
  [u"說出不用版本控制的痛點", u"知道版本控制解決的四件事", u"理解為什麼不只工程師需要它"],
  [("p", u"你一定看過這種資料夾："),
   ("code", u"報告.docx\n報告_v2.docx\n報告_v2_老師改過.docx\n報告_最終版.docx\n報告_最終版_真的最終版.docx\n報告_最終版_真的最終版(1).docx"),
   ("p", u"問題是：哪個才是最新的？v2 和最終版差在哪？三天前刪掉的那段，還找得回來嗎？兩個人同時改，誰的版本算數？"),
   ("p", u"版本控制系統（Version Control System）就是為了解決這些問題："),
   ("ul", [u"<strong>完整歷史</strong>：每次存檔（commit）都記錄「誰、什麼時候、改了什麼、為什麼」，可以隨時回到任何一個版本。",
           u"<strong>比較差異</strong>：精確看出兩個版本之間哪幾行變了。",
           u"<strong>平行開發</strong>：用「分支」同時嘗試好幾個方向，互不干擾，最後再合併。",
           u"<strong>多人協作</strong>：大家各自修改，系統幫你合併；真的衝突時會明確告訴你。"]),
   ("p", u"Git 最擅長處理<strong>純文字</strong>檔案：程式碼、Markdown、設定檔、LaTeX 論文、網頁。Word、Excel、圖片這類二進位檔也能放，但 Git 看不懂它們的內容，只能整個檔案存一份。"),
  ],
  u"不用版本控制時，檔案會變成一堆「最終版」副本，搞不清楚差異、找不回刪掉的內容、多人修改互相覆蓋。版本控制提供完整歷史、比較差異、用分支平行開發與多人協作。Git 最擅長純文字檔，二進位檔只能整份存。",
  [u"版本控制解決了哪四件事？", u"為什麼 Git 比較適合純文字檔？", u"除了程式碼，還有哪些東西適合用 Git 管理？"]),

lesson(u"三個區域",
  u"工作目錄、暫存區、儲存庫",
  [u"說出 Git 的三個區域", u"理解暫存區存在的理由", u"知道檔案在區域之間怎麼移動"],
  [("p", u"理解 Git 最重要的一張圖：你的檔案會存在於<strong>三個區域</strong>。"),
   ("fig", _THREE, "0 0 640 170", u"三個區域與搬運指令。"),
   ("ul", [u"<strong>工作目錄</strong>（working directory）：就是資料夾裡你看得到的檔案，用編輯器打開修改的就是它。",
           u"<strong>暫存區</strong>（staging area，又叫 index）：「下一次 commit 要包含什麼」的清單。用 <code>git add</code> 把修改放進來。",
           u"<strong>儲存庫</strong>（repository）：藏在 <code>.git</code> 資料夾裡的完整歷史。<code>git commit</code> 把暫存區的內容永久存成一個版本。"]),
   ("p", u"為什麼要多一個暫存區？因為你常常一次改了好幾件事，但希望分成幾個有意義的 commit。例如同時修了一個 bug 又改了排版——先只 add 修 bug 的檔案、commit「修正登入錯誤」，再 add 排版的檔案、commit「調整排版」。暫存區讓你<strong>挑選</strong>要存的東西。"),
   _AREAS,
  ],
  u"Git 的檔案存在三個區域：工作目錄（你正在編輯的檔案）、暫存區／index（下一次 commit 的草稿，用 git add 放入）、儲存庫（.git 中的完整歷史，用 git commit 存入）。暫存區讓你從一堆修改中挑出要放進同一個 commit 的部分。",
  [u"三個區域各是什麼？", u"git add 和 git commit 分別把檔案從哪裡搬到哪裡？", u"為什麼需要暫存區？"]),

lesson(u"commit 是什麼",
  u"快照、雜湊值與父節點",
  [u"理解 commit 是快照不是差異", u"認識 commit 的雜湊值", u"理解 commit 之間的父子關係"],
  [("p", u"一個 <strong>commit</strong> 是專案在某個時間點的<strong>完整快照</strong>，加上一些說明資料："),
   ("ul", [u"作者與時間", u"commit 訊息（你寫的說明）", u"<strong>父 commit</strong>（parent）：上一個版本是誰", u"一個 40 位十六進位的<strong>雜湊值</strong>（hash），例如 <code>edad20f121e019738a20f1cf7b2026fc83cbc709</code>，平常只寫前 7 位 <code>edad20f</code>"]),
   ("fig", _SNAP, "0 0 640 185", u"commit 串成一條鏈，每個都指向自己的父 commit。"),
   ("p", u"雜湊值是從 commit 的<strong>全部內容</strong>（包括檔案、訊息、作者、時間、父 commit）算出來的。只要任何一點不同，雜湊就完全不同。這帶來兩個重要性質："),
   ("ul", [u"<strong>無法偷改歷史</strong>：改了一個舊 commit，它的雜湊會變，所有後代的雜湊也都跟著變，大家一看就知道。",
           u"<strong>全世界唯一</strong>：同一個雜湊，在你的電腦和 GitHub 上一定指同一個 commit。"]),
   ("p", u"說「快照」而不說「差異」，是因為 Git 概念上每次都存整個專案的樣子；沒變的檔案不會重複存，而是直接指向舊的那份（第 46 課會打開 .git 看）。"),
  ],
  u"commit 是專案在某時間點的完整快照，附帶作者、時間、訊息、父 commit，以及從全部內容算出的 40 位雜湊值（常只寫前 7 位）。雜湊讓歷史無法被偷偷修改、且全世界唯一。沒變的檔案不會重複存，而是指向舊的那份。",
  [u"一個 commit 包含哪些資訊？", u"為什麼改了舊 commit，後面所有 commit 的雜湊都會變？", u"為什麼說 commit 是「快照」？"]),

lesson(u"分散式版本控制",
  u"每個人都有完整的歷史",
  [u"理解集中式與分散式的差別", u"認識遠端倉庫（remote）", u"知道 push 與 pull 的方向"],
  [("p", u"早期的版本控制（例如 SVN）是<strong>集中式</strong>的：歷史只存在一台伺服器上，每次查歷史、存檔都要連線。伺服器壞了，大家都不能工作。"),
   ("p", u"Git 是<strong>分散式</strong>的：每個人 <code>clone</code> 下來的，都是<strong>完整的歷史</strong>。你在飛機上也能 commit、查 log、開分支；GitHub 只是大家約定好的「中央集合點」。"),
   ("fig", _DIST, "0 0 640 270", u"GitHub 是大家同步的地方，但每一份都是完整的。"),
   ("t", [u"動作", u"方向", u"說明"],
    [[u"<code>git clone</code>", u"GitHub → 你", u"第一次把整個倉庫複製下來"], [u"<code>git push</code>", u"你 → GitHub", u"把你的新 commit 送上去"],
     [u"<code>git fetch</code>", u"GitHub → 你", u"把別人的新 commit 拿下來，但不動你的檔案"], [u"<code>git pull</code>", u"GitHub → 你", u"fetch ＋ 合併到你目前的分支"]]),
   ("p", u"記住：<strong>commit 只存在你的電腦上，直到你 push</strong>。很多新手以為 commit 就「上傳」了，其實沒有。"),
  ],
  u"集中式版本控制的歷史只在一台伺服器上；Git 是分散式的，每個 clone 都有完整歷史，可離線 commit 與查詢，GitHub 只是大家同步的集合點。clone 第一次複製、push 送出、fetch 取回不合併、pull 取回並合併。commit 在 push 之前只存在本機。",
  [u"集中式與分散式版本控制有什麼差別？", u"fetch 和 pull 有什麼不同？", u"commit 之後，GitHub 上就有了嗎？"]),
])

MODULE_B = (u"模組 B｜開始使用", [

lesson(u"註冊 GitHub、安裝 Git",
  u"準備工具",
  [u"註冊 GitHub 帳號", u"在 Windows 與 macOS 安裝 Git", u"確認安裝成功"],
  [("h", u"註冊 GitHub"),
   ("p", u"到 github.com 按 Sign up，填 Email、密碼、使用者名稱。<strong>使用者名稱會出現在你所有倉庫的網址裡</strong>（github.com/你的名稱/專案），建議取一個正式、好記的。註冊後建議立刻開啟<strong>兩步驟驗證</strong>（2FA）——GitHub 已要求所有會貢獻程式碼的帳號啟用。"),
   ("h", u"安裝 Git"),
   ("t", [u"系統", u"方法"],
    [[u"Windows", u"到 git-scm.com 下載 Git for Windows 安裝程式，一路按「下一步」即可（預設選項就很好）。它會附帶 <strong>Git Bash</strong>，一個可以打本課程所有指令的終端機。"],
     [u"macOS", u"打開「終端機」輸入 <code>git --version</code>，若沒有安裝，系統會跳出視窗請你安裝 Xcode 命令列工具；或用 Homebrew：<code>brew install git</code>。"],
     [u"Linux", u"用套件管理員，例如 <code>sudo apt install git</code>（Ubuntu／Debian）。"]]),
   ("p", u"安裝完成後，在終端機確認："),
   cmd(u"git --version"),
   ("p", u"看到類似 <code>git version 2.4x.x</code> 就成功了。本課程的範例使用 Git 2.43；2.23 之後的版本才有 <code>git switch</code> 與 <code>git restore</code>，如果你的版本太舊，請更新。"),
   ("p", u"本課程的指令都在終端機輸入：Windows 用 Git Bash，macOS 用「終端機」。開頭的 <code>$</code> 是提示符號，<strong>不用打</strong>。"),
  ],
  u"到 github.com 註冊，使用者名稱會出現在倉庫網址中，並應開啟兩步驟驗證。Windows 安裝 Git for Windows（附 Git Bash），macOS 用 Xcode 命令列工具或 Homebrew，Linux 用套件管理員。用 git --version 確認；git switch／restore 需 2.23 以上。指令前的 $ 不用打。",
  [u"GitHub 使用者名稱會出現在哪裡？", u"Windows 上要在哪裡輸入 Git 指令？", u"git switch 需要哪個版本以上？"]),

lesson(u"第一次設定",
  u"告訴 Git 你是誰",
  [u"設定使用者名稱與 Email", u"設定預設分支名稱", u"了解設定的三個層級"],
  [("p", u"每個 commit 都會記錄作者。安裝後第一件事，就是告訴 Git 你是誰："),
   ] + gex("config") + [
   ("ul", [u"<code>user.name</code>：顯示在 commit 上的名字，可以用真名或暱稱。",
           u"<code>user.email</code>：GitHub 用它把 commit 連結到你的帳號。如果不想公開 Email，可以在 GitHub 設定中取得一個 <code>…@users.noreply.github.com</code> 的隱私信箱來用。",
           u"<code>init.defaultBranch main</code>：新倉庫的預設分支叫 <code>main</code>（舊版 Git 預設叫 <code>master</code>，GitHub 自 2020 年起預設為 main）。"]),
   ("t", [u"層級", u"參數", u"存在哪裡", u"影響範圍"],
    [[u"系統", u"<code>--system</code>", u"Git 安裝目錄", u"這台電腦的所有使用者"], [u"全域", u"<code>--global</code>", u"<code>~/.gitconfig</code>", u"你的所有倉庫"],
     [u"倉庫", u"（不加）", u"<code>.git/config</code>", u"只有這個倉庫"]]),
   ("p", u"範圍越小優先權越高。例如公司專案想用公司信箱：在那個倉庫裡執行 <code>git config user.email \"me@company.com\"</code>（不加 --global）就好。"),
   ("p", u"另外建議設定編輯器（commit 時若沒寫 -m 會打開它）：<code>git config --global core.editor \"code --wait\"</code>（VS Code）或 <code>nano</code>。"),
  ],
  u"第一次使用要設定 user.name 與 user.email（GitHub 用 Email 連結帳號，可用 noreply 隱私信箱），以及 init.defaultBranch main。設定有系統、全域（~/.gitconfig）、倉庫（.git/config）三層，範圍越小優先權越高。也可設定 core.editor。",
  [u"user.email 為什麼重要？", u"三個設定層級各存在哪裡？", u"想讓某個專案用不同 Email 該怎麼設？"]),

lesson(u"登入驗證：HTTPS 與 SSH",
  u"讓電腦證明「我是我」",
  [u"知道 GitHub 不接受密碼推送", u"設定 Personal Access Token 或 Git Credential Manager", u"建立並登記 SSH 金鑰"],
  [("p", u"push 到 GitHub 時，GitHub 要確認你有權限。自 2021 年 8 月起，GitHub <strong>不再接受用帳號密碼</strong>做 Git 操作，你需要以下其中一種方式："),
   ("t", [u"方式", u"網址長相", u"適合"],
    [[u"HTTPS ＋ 憑證管理員", u"<code>https://github.com/ming/demo.git</code>", u"新手；Windows 的 Git 已內建 Git Credential Manager，第一次 push 會跳出瀏覽器登入"],
     [u"HTTPS ＋ Personal Access Token", u"同上", u"沒有憑證管理員時；把 token 當密碼貼上"], [u"SSH 金鑰", u"<code>git@github.com:ming/demo.git</code>", u"常用終端機的人；設定一次就不用再輸入"]]),
   ("h", u"方法一：Personal Access Token"),
   ("p", u"GitHub 右上角頭像 → Settings → Developer settings → Personal access tokens。建議用 <strong>Fine-grained token</strong>：可以限定只能存取某幾個倉庫、只給需要的權限（例如 Contents 讀寫），並設定到期日。token 只顯示一次，要像密碼一樣保管。"),
   ("h", u"方法二：SSH 金鑰"),
   cmd(u"ssh-keygen -t ed25519 -C \"ming@example.com\"\n# 一路按 Enter（可以設定密語保護私鑰）\ncat ~/.ssh/id_ed25519.pub\n# 複製輸出的整行，貼到 GitHub → Settings → SSH and GPG keys → New SSH key\nssh -T git@github.com"),
   ("p", u"最後一行成功時會看到 <code>Hi ming! You've successfully authenticated</code>。<code>.pub</code> 是<strong>公鑰</strong>，可以給別人；沒有 .pub 的 <code>id_ed25519</code> 是<strong>私鑰</strong>，絕對不能外流。"),
   ("p", u"另一個簡單的選擇是 GitHub 官方的命令列工具 <code>gh</code>：執行 <code>gh auth login</code>，它會引導你用瀏覽器登入並設定好 Git 的驗證（第 45 課）。"),
  ],
  u"GitHub 自 2021 年 8 月起不接受密碼做 Git 操作。可用 HTTPS 搭配憑證管理員（Windows 內建，第一次會跳瀏覽器登入）或 Personal Access Token（建議 Fine-grained、限定倉庫與期限），或用 ssh-keygen 建立 ed25519 金鑰並把公鑰貼到 GitHub。私鑰絕不外流；gh auth login 也能一次設定好。",
  [u"為什麼不能用 GitHub 密碼 push？", u"Fine-grained token 有什麼優點？", u"SSH 的公鑰和私鑰哪個可以給 GitHub？"]),

lesson(u"建立第一個倉庫",
  u"git init 與 GitHub 上的 New repository",
  [u"用 git init 在本機建立倉庫", u"在 GitHub 網站建立倉庫", u"認識 README、.gitignore、LICENSE"],
  [("p", u"倉庫（repository，常簡稱 repo）就是一個被 Git 管理的資料夾。在本機建立："),
   ] + gex("init") + [
   ("p", u"<code>git init</code> 在資料夾裡建立了一個隱藏的 <code>.git</code> 資料夾——<strong>整個歷史都住在這裡</strong>。刪掉 .git，這個資料夾就變回普通資料夾。"),
   ("h", u"在 GitHub 上建立"),
   ("p", u"右上角「＋」→ New repository。要填的欄位："),
   ("t", [u"欄位", u"說明"],
    [[u"Repository name", u"倉庫名稱，會成為網址的一部分；習慣用小寫與連字號，如 <code>my-first-repo</code>"], [u"Public／Private", u"公開（全世界看得到）或私有（只有你和你邀請的人）"],
     [u"Add a README", u"專案的說明首頁，用 Markdown 寫（第 44 課）"], [u"Add .gitignore", u"選一個語言範本，自動忽略該語言常見的暫存檔（第 14 課）"],
     [u"Choose a license", u"開源授權條款；不選代表「保留所有權利」（第 51 課）"]]),
   ("p", u"兩種起點都可以：如果你在 GitHub 上建立並勾選了 README，就用 <code>git clone</code> 下載（第 10 課）；如果本機已經有專案，就在 GitHub 建立<strong>空的</strong>倉庫（不要勾 README），再把本機的推上去（第 12 課）。"),
  ],
  u"git init 會在資料夾中建立隱藏的 .git，整個歷史都存在那裡。在 GitHub 用 New repository 建立時要填名稱、選擇公開或私有，並可加入 README、.gitignore 範本與授權條款。GitHub 上先建立就用 clone；本機已有專案則在 GitHub 建立空倉庫再推上去。",
  [u"git init 做了什麼？", u"刪掉 .git 會怎樣？", u"本機已有專案時，GitHub 上的倉庫該不該勾 README？"]),

lesson(u"clone：把倉庫複製下來",
  u"從 GitHub 到你的電腦",
  [u"用 git clone 下載倉庫", u"認識 origin", u"理解 clone 拿到了什麼"],
  [("p", u"在 GitHub 倉庫頁面按綠色的 <strong>Code</strong> 按鈕，複製網址（HTTPS 或 SSH），然後："),
   cmd(u"git clone https://github.com/ming/demo.git\ncd demo"),
   ("p", u"下面是實際執行的結果（範例中用本機路徑模擬 GitHub 網址）："),
   ] + gex("remote", 0, 3) + [
   ("p", u"clone 做了三件事："),
   ("ol", [u"建立一個同名資料夾，下載<strong>完整的歷史</strong>（不只最新版）。", u"自動把來源記成一個叫 <code>origin</code> 的遠端（remote）——之後 push、pull 預設就是對它。", u"把預設分支（main）的檔案放到工作目錄。"]),
   ("p", u"<code>origin</code> 只是一個慣用的名字，代表「我是從這裡 clone 的」。一個倉庫可以有好幾個遠端，例如 fork 時常會再加一個 <code>upstream</code>（第 33 課）。"),
   ("p", u"想下載別人的公開專案來研究，也是用 clone——不需要任何權限。但要 push 回去，就需要寫入權限（或用 fork）。"),
  ],
  u"git clone 網址 會建立同名資料夾、下載完整歷史、自動把來源命名為遠端 origin，並把預設分支的檔案放到工作目錄。origin 只是慣用名稱，倉庫可以有多個遠端。clone 公開專案不需權限，但 push 需要寫入權限。",
  [u"clone 會下載最新版還是完整歷史？", u"origin 是什麼？", u"沒有權限可以 clone 別人的公開倉庫嗎？"]),

lesson(u"add 與 commit",
  u"存下第一個版本",
  [u"用 git status 觀察狀態", u"用 add 與 commit 建立版本", u"寫出好的 commit 訊息"],
  [("p", u"建立一個檔案，看看 Git 怎麼看待它："),
   ] + gex("first") + [
   ("p", u"逐行解讀："),
   ("ul", [u"<code>Untracked files</code>：Git 看到了新檔案，但還沒在管理它。", u"<code>git add</code> 之後變成 <code>Changes to be committed</code>：已經放進暫存區。",
           u"<code>git commit -m \"訊息\"</code>：建立 commit。<code>(root-commit)</code> 表示這是第一個 commit，<code>0f345f7</code> 是它的雜湊。", u"<code>git log</code> 列出歷史。"]),
   ("h", u"好的 commit 訊息"),
   ("t", [u"✗ 不好", u"✓ 好"],
    [[u"update", u"修正登入時密碼含空白會失敗的問題"], [u"改東西", u"首頁加上聯絡表單"], [u"asdf", u"將圖片壓縮，首頁載入時間從 3 秒降到 1 秒"]]),
   ("ul", [u"第一行是<strong>摘要</strong>，簡短（約 50 字元內）說明「這個 commit 做了什麼」。", u"需要的話空一行，再寫詳細說明：<strong>為什麼</strong>要這樣改。",
           u"一個 commit 只做一件事。半年後的你（或同事）會感謝你。", u"很多團隊採用 <strong>Conventional Commits</strong> 格式：<code>feat: 加入登入</code>、<code>fix: 修正…</code>、<code>docs: 更新 README</code>。"]),
   ("p", u"小技巧：<code>git add .</code> 會加入目前資料夾下所有變更；<code>git commit -am \"訊息\"</code> 可以一次把<strong>已追蹤</strong>檔案的修改 add 加 commit（新檔案仍要先 add）。"),
  ],
  u"新檔案先是 Untracked；git add 後進入暫存區（Changes to be committed）；git commit -m 建立 commit，第一個標示 root-commit；git log 查看歷史。好的 commit 訊息第一行簡述做了什麼、內文說明為什麼，一個 commit 只做一件事，可採用 Conventional Commits。git add . 加入全部，commit -am 只適用已追蹤檔。",
  [u"Untracked 是什麼意思？", u"好的 commit 訊息應該包含什麼？", u"git commit -am 能加入新檔案嗎？"]),

lesson(u"push 與 pull",
  u"和 GitHub 同步",
  [u"把 commit 推上 GitHub", u"把別人的修改拉下來", u"把本機現有專案推上新的 GitHub 倉庫"],
  [("p", u"在 clone 下來的倉庫裡做一個 commit，然後 push："),
   ] + gex("remote", 3) + [
   ("p", u"注意 <code>git status</code> 的變化：commit 之後是 <code>ahead of 'origin/main' by 1 commit</code>（你比 GitHub 多一個），push 之後變成 <code>up to date</code>。<code>origin/main</code> 是 Git 記住的「上次看到 GitHub 上的 main 在哪」。"),
   ("h", u"把別人的修改拉下來"),
   ("p", u"假設你在桌機 push 了一個 commit，現在回到筆電："),
   ] + gex("pull") + [
   ("p", u"<code>git fetch</code> 只更新 <code>origin/main</code>，不碰你的檔案；<code>git pull</code> 則是 fetch 之後再合併。養成習慣：<strong>開始工作前先 pull</strong>。"),
   ("h", u"本機已有專案，推到新的 GitHub 倉庫"),
   cmd(u"# 先在 GitHub 建立一個「空的」倉庫（不要勾 README）\ngit remote add origin https://github.com/ming/demo.git\ngit push -u origin main"),
   ("p", u"<code>-u</code>（--set-upstream）讓本機的 main 記住「對應 origin 的 main」，之後只要打 <code>git push</code>、<code>git pull</code> 就好。"),
  ],
  u"commit 後 git status 顯示 ahead of origin/main，push 後變成 up to date；origin/main 是 Git 記住的遠端分支位置。git fetch 只更新 origin/main，git pull 是 fetch 加合併，開始工作前應先 pull。本機專案推到新倉庫：git remote add origin 網址，再 git push -u origin main。",
  [u"ahead of 'origin/main' by 1 commit 是什麼意思？", u"fetch 和 pull 的差別？", u"push 時的 -u 有什麼作用？"]),
])

_RESTORE_TREE = ghw({"t": "tree", "q": u"「我要復原」決策樹：回答問題，找到該用的指令。", "nodes": {
  "start": {"q": u"你想復原的東西，現在在哪裡？", "o": [[u"只是改了檔案，還沒 add", "wd"], [u"已經 add 了，還沒 commit", "idx"], [u"已經 commit 了", "cm"]]},
  "wd": {"a": u"<code>git restore 檔名</code>：把檔案改回暫存區（也就是上次 add 或 commit）的樣子。<br>⚠️ 這些修改從來沒被 Git 存過，丟掉就<strong>真的救不回來</strong>。"},
  "idx": {"a": u"<code>git restore --staged 檔名</code>：把檔案從暫存區拿出來，修改仍保留在工作目錄。想連修改一起丟掉，再接著 <code>git restore 檔名</code>。"},
  "cm": {"q": u"這個 commit 已經 push 到 GitHub 了嗎？", "o": [[u"還沒，只在我的電腦上", "local"], [u"已經 push 了（別人可能已經拿到）", "pushed"]]},
  "local": {"q": u"你想怎麼處理？", "o": [[u"只是 commit 訊息打錯，或漏了一個檔案", "amend"], [u"取消這個 commit，但保留修改", "soft"], [u"整個不要了，連修改一起丟掉", "hard"]]},
  "amend": {"a": u"<code>git commit --amend -m \"新訊息\"</code>（漏的檔案先 add 再 amend）。會產生一個新雜湊的 commit 取代舊的（第 16 課）。"},
  "soft": {"a": u"<code>git reset --soft HEAD~1</code>：commit 取消，修改還在暫存區；或 <code>git reset HEAD~1</code>（mixed）：修改留在工作目錄、尚未 add（第 15 課）。"},
  "hard": {"a": u"<code>git reset --hard HEAD~1</code>：commit 與修改都丟掉。萬一後悔，用 <code>git reflog</code> 找回（第 28 課）。"},
  "pushed": {"a": u"<code>git revert 雜湊</code>：新增一個「反向」的 commit 抵消它，<strong>不改寫歷史</strong>，然後正常 push。<br>不要對已 push 的 commit 用 reset 再強制推送——會打亂其他人的歷史。"}}})

MODULE_C = (u"模組 C｜日常操作", [

lesson(u"status、diff、log",
  u"看懂現在的狀態",
  [u"用 git status 與 status --short", u"用 git diff 看修改內容", u"用 git log 查歷史"],
  [("p", u"日常最常打的三個指令：<strong>status</strong>（現在怎樣）、<strong>diff</strong>（改了什麼）、<strong>log</strong>（之前發生過什麼）。"),
   ] + gex("diff") + [
   ("p", u"讀懂 diff：<code>---</code> 是舊版、<code>+++</code> 是新版；<code>@@ -1 +1,2 @@</code> 表示舊版從第 1 行起 1 行、新版從第 1 行起 2 行；<code>+</code> 開頭是新增的行，<code>-</code> 是刪除的行。"),
   ("p", u"注意：<code>git add</code> 之後再打 <code>git diff</code> 是空的！因為 <code>git diff</code> 比較的是<strong>工作目錄 vs. 暫存區</strong>；要看已 add 的內容，要用 <code>git diff --staged</code>（暫存區 vs. 最新 commit）。"),
   ("t", [u"<code>status --short</code> 代碼", u"意思"],
    [[u"<code>??</code>", u"未追蹤的新檔案"], [u"<code> M</code>（M 在右）", u"已修改，尚未 add"], [u"<code>M </code>（M 在左）", u"已修改，已 add"], [u"<code>A </code>", u"新檔案，已 add"], [u"<code> D</code>", u"已刪除"]]),
   ] + gex("log", label=u"查歷史") + [
   ("p", u"<code>git log --oneline</code> 一行一個 commit；<code>--stat</code> 列出改了哪些檔案；<code>git show</code> 看單一 commit 的完整內容；在最後加 <code>-- 檔名</code> 只看跟這個檔案有關的 commit。圖形版：<code>git log --oneline --graph --all</code>。"),
  ],
  u"git status 看目前狀態，--short 用兩欄代碼（左欄暫存區、右欄工作目錄，?? 是未追蹤）；git diff 比較工作目錄與暫存區，--staged 比較暫存區與最新 commit；diff 中 + 是新增、- 是刪除。git log --oneline、--stat、--graph --all、git show、-- 檔名 用來查歷史。",
  [u"為什麼 add 之後 git diff 沒有輸出？", u"status --short 的 M 在左邊和右邊有什麼不同？", u"怎麼只看某個檔案的歷史？"]),

lesson(u".gitignore",
  u"哪些檔案不該進版本控制",
  [u"知道哪些檔案應該忽略", u"撰寫 .gitignore 規則", u"用測試器驗證規則"],
  [("p", u"不是所有檔案都該 commit："),
   ("ul", [u"<strong>機密</strong>：<code>.env</code>、API 金鑰、密碼檔——上傳到公開倉庫幾分鐘內就可能被機器人掃到。", u"<strong>自動產生的檔案</strong>：編譯結果 <code>build/</code>、<code>dist/</code>，可以從原始碼重新產生。",
           u"<strong>套件</strong>：<code>node_modules/</code>、<code>venv/</code>，用 package.json、requirements.txt 就能重新安裝。", u"<strong>個人或系統檔</strong>：<code>.DS_Store</code>（macOS）、<code>Thumbs.db</code>（Windows）、編輯器設定、log 檔。"]),
   ] + gex("ignore") + [
   ("p", u"加入 .gitignore 之後，<code>build/</code>、<code>logs/</code>、<code>.env</code> 都從 status 消失了。<code>git check-ignore -v</code> 會告訴你某個檔案是被哪一行規則忽略的。<strong>.gitignore 本身要 commit</strong>，這樣團隊每個人都套用同樣規則。"),
   ("t", [u"規則", u"意思"],
    [[u"<code>*.log</code>", u"任何層級、任何名稱以 .log 結尾的檔案"], [u"<code>build/</code>", u"名叫 build 的資料夾（結尾的 / 表示只比對資料夾）"], [u"<code>/config.local</code>", u"只有根目錄的 config.local（開頭的 / 表示從根目錄算）"],
     [u"<code>!important.log</code>", u"例外：不要忽略它"], [u"<code>**/tmp/</code>", u"任何層級的 tmp 資料夾"], [u"<code>docs/*.pdf</code>", u"docs 底下一層的 pdf（不含更深的子資料夾）"]]),
   ghw({"t": "ignore", "q": u".gitignore 測試器：修改左邊的規則或右邊的路徑，看哪些檔案被忽略（比對結果已用 git check-ignore 驗證）。"}),
   ("p", u"重要：.gitignore 只對<strong>還沒被追蹤</strong>的檔案有效。已經 commit 過的檔案，要先用 <code>git rm --cached 檔名</code> 停止追蹤（第 49 課）。GitHub 維護了一套各語言的範本：github.com/github/gitignore。"),
  ],
  u"機密（.env、金鑰）、可重新產生的編譯結果、可重新安裝的套件、個人或系統檔都不該 commit。.gitignore 規則：*.log 任意層級、結尾 / 只比對資料夾、開頭 / 從根目錄算、! 表示例外、** 跨層級；最後符合的規則決定結果，上層資料夾被忽略則內容無法例外。.gitignore 要 commit，且只對未追蹤檔案有效。",
  [u"為什麼 node_modules 不該 commit？", u"build/ 和 /build 有什麼不同？", u"已經 commit 的檔案加進 .gitignore 會怎樣？"]),

lesson(u"復原：restore、reset、revert",
  u"三種「後悔藥」",
  [u"用 restore 復原檔案", u"理解 reset 的三種模式", u"知道何時該用 revert"],
  [("p", u"Git 的「復原」有好幾種，關鍵在於：<strong>你要復原的東西在哪個區域？有沒有 push 過？</strong>"),
   ("h", u"restore：復原檔案"),
   ] + gex("restore") + [
   ("h", u"revert 與 reset：復原 commit"),
   ] + gex("reset", label=u"revert 新增反向 commit；reset 移動分支") + [
   ("ul", [u"<code>git revert</code>：新增一個「相反」的 commit 抵消舊的。歷史只增不減，<strong>對已經 push 的 commit 是安全的做法</strong>。",
           u"<code>git reset</code>：把分支指標往回移，後面的 commit 從歷史上「消失」。只適合<strong>還沒 push</strong> 的 commit。"]),
   ("p", u"reset 有三種模式，差別在「被退掉的 commit 的修改要放哪」："),
   ghw({"t": "reset", "q": u"git reset 的三種模式（假設歷史是 A → B → C，main 指向 C）："}),
   ] + gex("reset3", label=u"三種模式實測") + [
   _RESTORE_TREE,
  ],
  u"git restore 檔名 把工作目錄改回暫存區的版本，restore --staged 把檔案移出暫存區。git revert 新增反向 commit，不改寫歷史，適合已 push 的 commit；git reset 移動分支指標，只適合未 push 的 commit。reset --soft 修改留在暫存區、--mixed（預設）留在工作目錄、--hard 全部丟掉。",
  [u"已經 push 的 commit 該用 revert 還是 reset？", u"reset 三種模式差在哪？", u"git restore 丟掉的修改救得回來嗎？"]),

lesson(u"amend：修改上一個 commit",
  u"訊息打錯、漏了檔案",
  [u"用 --amend 修改 commit 訊息", u"用 --amend 補上漏掉的檔案", u"理解 amend 會改變雜湊"],
  [("p", u"剛 commit 完發現訊息打錯字："),
   ] + gex("amend") + [
   ("p", u"注意雜湊從 <code>541711b</code> 變成了 <code>098731a</code>：amend 並不是「修改」舊 commit，而是<strong>做一個新的 commit 取代它</strong>（舊的仍在 reflog 裡，第 28 課）。"),
   ("p", u"漏了檔案也一樣：先 <code>git add 漏掉的檔案</code>，再 <code>git commit --amend --no-edit</code>（<code>--no-edit</code> 表示沿用原本的訊息）。"),
   ("p", u"⚠️ 跟 reset 一樣，<strong>只對還沒 push 的 commit 使用</strong>。如果已經 push，amend 之後本機和 GitHub 的歷史就分岔了，必須強制推送（<code>git push --force-with-lease</code>）——在自己一個人的分支上可以，在共用分支上會給別人帶來麻煩。"),
   ("p", u"想修改更早之前的 commit，可以用互動式 rebase：<code>git rebase -i HEAD~3</code>，在打開的清單中把 <code>pick</code> 改成 <code>reword</code>（改訊息）、<code>squash</code>（合併到前一個）、<code>drop</code>（刪除）等。"),
  ],
  u"git commit --amend -m 可修改上一個 commit 的訊息；漏了檔案先 add 再 commit --amend --no-edit。amend 是做新 commit 取代舊的，雜湊會改變，只應用在未 push 的 commit；已 push 則需強制推送（--force-with-lease），共用分支應避免。更早的 commit 可用 git rebase -i 改寫。",
  [u"amend 之後雜湊為什麼會變？", u"--no-edit 是什麼意思？", u"想修改三個 commit 以前的訊息該怎麼做？"]),

lesson(u"stash：暫時收起來",
  u"寫到一半要切去做別的事",
  [u"用 stash 暫存修改", u"查看與取回 stash", u"知道 stash 的使用時機"],
  [("p", u"你正在寫新功能，寫到一半，老闆說「線上有 bug，馬上修！」。現在的修改還不能 commit，但切換分支又會帶著這些修改走。這時用 <strong>stash</strong>："),
   ] + gex("stash") + [
   ("t", [u"指令", u"作用"],
    [[u"<code>git stash push -m \"說明\"</code>", u"把未 commit 的修改收起來，工作目錄回到乾淨狀態（舊寫法 <code>git stash</code>）"], [u"<code>git stash list</code>", u"列出所有收起來的東西"],
     [u"<code>git stash pop</code>", u"取回最新的一個，並從清單移除"], [u"<code>git stash apply</code>", u"取回但保留在清單中"], [u"<code>git stash drop</code>", u"丟掉一個"], [u"<code>git stash -u</code>", u"連未追蹤的新檔案也一起收"]]),
   ("p", u"stash 就像一個「抽屜」：先把桌上的東西掃進去，處理完急事再拿出來。但抽屜放久了會忘記裡面有什麼——如果一件工作要擱置很久，不如開一個分支 commit 起來。"),
  ],
  u"git stash push -m 把未 commit 的修改收起來讓工作目錄變乾淨，stash list 列出、pop 取回並移除、apply 取回但保留、drop 丟掉、-u 連未追蹤檔一起收。適合臨時切去處理急事；要擱置很久的工作則應開分支 commit。",
  [u"什麼情況適合用 stash？", u"pop 和 apply 有什麼不同？", u"新建立的檔案預設會被 stash 收起來嗎？"]),

lesson(u"tag 與版本號",
  u"替重要的 commit 取名字",
  [u"建立附註標籤", u"理解語意化版本 SemVer", u"推送標籤到 GitHub"],
  [("p", u"commit 的雜湊不好記。發布正式版時，可以給那個 commit 貼一個<strong>標籤</strong>（tag）："),
   ] + gex("tag") + [
   ("p", u"<code>-a</code> 建立<strong>附註標籤</strong>（annotated tag），會記錄建立者、時間和說明，正式發布建議用它；不加 -a 是輕量標籤，只是一個名字。<code>git describe</code> 的 <code>v1.0.0-1-g6b6b9eb</code> 表示「v1.0.0 之後又多了 1 個 commit，目前在 6b6b9eb」。"),
   ("h", u"語意化版本（SemVer）"),
   ("p", u"版本號 <code>主版號.次版號.修訂號</code>，例如 <code>2.4.1</code>："),
   ("t", [u"哪個數字加 1", u"時機", u"例子"],
    [[u"主版號 MAJOR", u"不相容的改變（舊的用法會壞）", u"1.9.3 → 2.0.0"], [u"次版號 MINOR", u"新增功能，向下相容", u"1.9.3 → 1.10.0"], [u"修訂號 PATCH", u"修 bug，向下相容", u"1.9.3 → 1.9.4"]]),
   ("p", u"標籤預設<strong>不會</strong>隨 <code>git push</code> 上傳，要另外推送："),
   cmd(u"git push origin v1.0.0\n# 或一次推送所有標籤\ngit push --tags"),
   ("p", u"在 GitHub 上，標籤可以進一步做成 <strong>Release</strong>，附上更新說明與下載檔（第 42 課）。"),
  ],
  u"git tag -a v1.0.0 -m 建立附註標籤（記錄建立者、時間、說明），適合正式發布；git describe 顯示距離最近標籤多少 commit。語意化版本 MAJOR.MINOR.PATCH：不相容改變加主版號、新功能加次版號、修 bug 加修訂號。標籤需 git push origin 標籤 或 --tags 另外推送，在 GitHub 可做成 Release。",
  [u"附註標籤和輕量標籤的差別？", u"修了一個 bug，版本號 1.4.2 應該變成什麼？", u"git push 會自動推送標籤嗎？"]),

lesson(u"在 GitHub 網頁上操作",
  u"不用終端機也能做的事",
  [u"在網頁上編輯與上傳檔案", u"瀏覽歷史與差異", u"認識 github.dev 與鍵盤快捷鍵"],
  [("p", u"很多小事可以直接在 GitHub 網站完成："),
   ("t", [u"想做的事", u"怎麼做"],
    [[u"編輯一個檔案", u"打開檔案 → 右上角鉛筆圖示 → 修改 → <strong>Commit changes</strong>，可選擇直接 commit 到 main 或開新分支並建立 Pull Request"],
     [u"上傳檔案", u"倉庫首頁 <strong>Add file → Upload files</strong>，拖曳檔案進去（單檔有大小限制）"], [u"新增檔案", u"<strong>Add file → Create new file</strong>，檔名中打 <code>/</code> 會自動建立資料夾"],
     [u"看歷史", u"檔案頁面的 <strong>History</strong>，或倉庫首頁的 commits 數字"], [u"看是誰改的", u"檔案頁面的 <strong>Blame</strong>：每一行最後由哪個 commit 修改"], [u"比較兩個版本", u"網址 <code>/compare/v1.0.0...main</code>"]]),
   ("p", u"在倉庫頁面按鍵盤上的 <code>.</code>（句點），或把網址的 github.com 改成 <code>github.dev</code>，會在瀏覽器中打開一個網頁版的 VS Code，可以同時編輯多個檔案再一次 commit。按 <code>t</code> 可以快速搜尋檔案、<code>?</code> 列出所有快捷鍵。"),
   ("p", u"Blame 對應的指令是 <code>git blame</code>："),
   ] + gex("blame") + [
   ("p", u"網頁操作很方便，但它沒有本機的完整歷史與工具，也不能執行程式測試。小修改（改錯字、更新 README）用網頁，真正的開發還是在本機。"),
  ],
  u"GitHub 網頁可以直接編輯（鉛筆圖示後 Commit changes，可選 commit 到 main 或開分支 PR）、上傳與新增檔案、看 History 與 Blame、用 /compare 比較版本。按 . 或改用 github.dev 可開啟網頁版 VS Code，t 搜尋檔案、? 列出快捷鍵。git blame 對應 Blame 功能。真正開發仍在本機。",
  [u"在 GitHub 網頁上編輯檔案後有哪兩種 commit 方式？", u"Blame 能告訴你什麼？", u"怎麼在瀏覽器裡開啟 VS Code？"]),

lesson(u"圖形介面工具",
  u"GitHub Desktop 與 VS Code",
  [u"認識常見的 Git 圖形介面", u"把圖形介面的按鈕對應到指令", u"判斷何時用哪一種"],
  [("p", u"不想打指令也可以用圖形介面。它們背後執行的就是同樣的 Git 指令："),
   ("t", [u"工具", u"特色"],
    [[u"GitHub Desktop", u"GitHub 官方、免費，Windows／macOS；介面最簡單，適合入門"], [u"VS Code 原始碼控制", u"編輯器內建（左側分支圖示），可以逐行挑選要 stage 的部分"],
     [u"JetBrains IDE（IntelliJ、PyCharm）", u"整合度高，合併衝突工具很好用"], [u"Sourcetree、GitKraken、Fork", u"以分支圖為中心的專用工具"]]),
   ("t", [u"圖形介面上的按鈕", u"對應的指令"],
    [[u"勾選檔案／Stage", u"<code>git add</code>"], [u"Commit to main", u"<code>git commit</code>"], [u"Push origin／Sync", u"<code>git push</code>（Sync 通常是 pull 加 push）"],
     [u"Fetch origin", u"<code>git fetch</code>"], [u"Current branch → New branch", u"<code>git switch -c</code>"], [u"Discard changes", u"<code>git restore</code>"], [u"Stash changes", u"<code>git stash</code>"]]),
   ("p", u"建議：<strong>先學指令，再用圖形介面</strong>。圖形介面讓日常操作更快、看 diff 更舒服；但出了問題（衝突、復原、救援）時，網路上的解法幾乎都是指令，看得懂指令才知道按鈕做了什麼。"),
  ],
  u"常見圖形介面有 GitHub Desktop（官方、最簡單）、VS Code 原始碼控制、JetBrains IDE、Sourcetree／GitKraken／Fork。按鈕背後就是 git add、commit、push、fetch、switch -c、restore、stash 等指令。建議先學指令再用圖形介面，出問題時才看得懂解法。",
  [u"GitHub Desktop 的 Sync 大約等於哪些指令？", u"VS Code 的原始碼控制有什麼方便的地方？", u"為什麼建議先學指令？"]),
])

_BR = svg(
    title(u"分支只是一個指向 commit 的標籤；HEAD 指向目前的分支"),
    C(80, 120, 18, BLUE, BLUE), C(200, 120, 18, BLUE, BLUE), C(320, 120, 18, BLUE, BLUE), C(440, 70, 18, GREEN, GREEN),
    A(98, 120, 182, 120, MUTED), A(218, 120, 302, 120, MUTED), A(338, 112, 422, 76, MUTED),
    T(80, 125, u"A", 12, "#fff"), T(200, 125, u"B", 12, "#fff"), T(320, 125, u"C", 12, "#fff"), T(440, 75, u"D", 12, "#fff"),
    R(290, 160, 60, 22, BLUE, BLUE, 5), T(320, 175, u"main", 11, "#fff"),
    R(395, 20, 100, 22, GREEN, GREEN, 5), T(445, 35, u"feature-login", 10, "#fff"),
    R(510, 20, 60, 22, ORANGE, ORANGE, 5), T(540, 35, u"HEAD", 11, "#fff"), A(510, 31, 497, 31, ORANGE),
    T(320, 215, u"在 feature-login 上 commit，只有 feature-login 往前走；main 留在 C", 10.5, MUTED),
)

MODULE_D = (u"模組 D｜分支", [

lesson(u"分支是什麼",
  u"一個會移動的標籤",
  [u"理解分支的本質", u"認識 HEAD", u"知道為什麼要用分支"],
  [("p", u"在很多舊系統中，開分支等於複製整個專案，又慢又占空間。在 Git 裡，<strong>分支只是一個指向某個 commit 的標籤</strong>——一個存著 40 個字元雜湊的小檔案。所以開分支幾乎不花時間。"),
   ("fig", _BR, "0 0 640 230", u"分支是標籤；HEAD 告訴 Git「你現在在哪個分支」。"),
   ("ul", [u"每次 commit，<strong>目前所在的分支</strong>會自動往前移到新 commit。", u"<strong>HEAD</strong> 是一個特殊的指標，指向「你現在所在的分支」。切換分支，就是移動 HEAD。",
           u"<code>main</code> 也只是一個普通分支，只是大家約定它是「正式、穩定」的那條線。"]),
   ("p", u"為什麼要用分支？因為你可以<strong>放心實驗</strong>：開一個分支做新功能，main 保持穩定；做壞了就丟掉分支，做好了再合併回 main。團隊中每個人、每個功能各一個分支，互不干擾。"),
   _GRAPH,
  ],
  u"Git 的分支只是一個指向 commit 的標籤（存著雜湊的小檔案），所以開分支幾乎不花時間。每次 commit，目前所在的分支會往前移；HEAD 指向目前所在的分支，切換分支就是移動 HEAD。main 只是約定為穩定版的普通分支。分支讓人放心實驗、並行開發。",
  [u"Git 的分支本質上是什麼？", u"HEAD 是什麼？", u"在 feature 分支 commit 時，main 會動嗎？"]),

lesson(u"建立與切換分支",
  u"switch 與 checkout",
  [u"建立新分支", u"在分支之間切換", u"理解切換分支時檔案的變化"],
  [] + gex("branch") + [
   ("p", u"重點觀察：在 feature-login 上 commit 了 login.py，<strong>切回 main 之後 login.py 就不見了</strong>——因為 main 的快照裡沒有它。檔案沒有消失，它安全地存在 feature-login 分支裡，切回去就會出現。"),
   ("t", [u"指令", u"作用"],
    [[u"<code>git branch</code>", u"列出分支，<code>*</code> 是目前所在"], [u"<code>git branch 名稱</code>", u"建立分支（但不切換）"], [u"<code>git switch 名稱</code>", u"切換到分支"],
     [u"<code>git switch -c 名稱</code>", u"建立並切換（最常用）"], [u"<code>git branch -v</code>", u"列出分支與各自最新的 commit"], [u"<code>git branch -d 名稱</code>", u"刪除已合併的分支（未合併要用 -D）"]]),
   ("p", u"舊教學常用 <code>git checkout 名稱</code> 和 <code>git checkout -b 名稱</code>，效果一樣。checkout 一個指令做太多事（切分支、還原檔案⋯⋯），所以 Git 2.23 拆成了 <code>switch</code>（切分支）和 <code>restore</code>（還原檔案）。"),
   ("p", u"切換分支前，如果有<strong>尚未 commit</strong> 的修改會跟目標分支衝突，Git 會拒絕切換以保護你的修改。這時先 commit 或 stash（第 17 課）。"),
   ("p", u"分支命名慣例：<code>feature/login</code>、<code>fix/typo-in-readme</code>、<code>docs/api</code>——用類別前綴加簡短描述，不要用空白。"),
  ],
  u"git switch -c 名稱 建立並切換分支，git branch 列出、branch -v 顯示最新 commit、branch -d 刪除已合併分支（未合併用 -D）。切換分支時工作目錄會變成該分支的快照，在其他分支建立的檔案會暫時不見。舊寫法 checkout／checkout -b 效果相同，2.23 拆成 switch 與 restore。有衝突的未提交修改會阻止切換。",
  [u"切回 main 後 login.py 為什麼不見了？", u"git switch -c 和 git branch 有什麼不同？", u"有未 commit 的修改時切換分支會發生什麼事？"]),

lesson(u"merge：合併分支",
  u"快轉與三方合併",
  [u"理解快轉合併", u"理解三方合併與合併 commit", u"合併後刪除分支"],
  [("p", u"功能做完了，要把 feature 分支合併回 main：先切到 main，再 <code>git merge feature</code>。合併有兩種情況。"),
   ("h", u"情況一：快轉（fast-forward）"),
   ("p", u"如果 main 在你開分支之後<strong>沒有新的 commit</strong>，Git 只要把 main 的標籤往前移就好，不需要新的 commit："),
   ] + gex("ffmerge") + [
   ("h", u"情況二：三方合併（three-way merge）"),
   ("p", u"如果 main 在這段期間<strong>也有了新 commit</strong>，兩條線分岔了。Git 會比較三個版本——兩個分支的最新 commit，加上它們的<strong>共同祖先</strong>——自動合併，並產生一個有<strong>兩個父 commit</strong> 的「合併 commit」："),
   ] + gex("merge3") + [
   ("p", u"<code>'ort'</code> 是 Git 目前預設的合併策略名稱。只要兩邊改的是<strong>不同的地方</strong>（這裡一邊改 README、一邊加 login.py），Git 都能自動合併。兩邊改到<strong>同一行</strong>，就會發生衝突（下一課）。"),
   ("p", u"合併完成的分支可以用 <code>git branch -d</code> 刪除——刪的只是標籤，commit 都還在 main 的歷史裡。"),
  ],
  u"合併時先切到目標分支再 git merge 來源分支。若目標分支沒有新 commit，Git 只把標籤往前移（快轉，Fast-forward）；若兩邊都有新 commit，Git 以兩個分支與共同祖先進行三方合併，產生有兩個父 commit 的合併 commit（預設策略 ort）。改到不同地方可自動合併，改同一行則會衝突。合併後可刪除分支。",
  [u"什麼時候會發生快轉合併？", u"三方合併的「三方」是哪三個版本？", u"合併 commit 有幾個父 commit？"]),

lesson(u"合併衝突",
  u"兩邊改了同一行",
  [u"理解衝突發生的原因", u"讀懂衝突標記", u"解決衝突並完成合併"],
  [("p", u"main 把問候改成 <code>Hello!</code>，feature-greet 把同一行改成 <code>你好</code>。Git 不知道該聽誰的，只好停下來問你："),
   ] + gex("conflict") + [
   ("p", u"解決衝突的步驟："),
   ("ol", [u"<code>git status</code> 找出 <code>both modified</code> 的檔案。", u"打開檔案，找到 <code>&lt;&lt;&lt;&lt;&lt;&lt;&lt;</code>、<code>=======</code>、<code>&gt;&gt;&gt;&gt;&gt;&gt;&gt;</code> 標記。",
           u"決定要留哪一邊、兩邊都留、或寫一個全新的版本（上例寫成了 <code>你好！</code>），<strong>刪掉所有標記</strong>。", u"<code>git add 檔名</code> 標記為已解決。", u"<code>git commit</code> 完成合併。"]),
   ("p", u"後悔了想放棄這次合併：<code>git merge --abort</code>，一切回到合併之前。"),
   ghw({"t": "conflict", "q": u"動手解衝突：", "file": "config.py", "br": "feature-dark",
        "pre": "APP_NAME = \"記帳本\"\n", "ours": "THEME = \"light\"\nFONT_SIZE = 16", "theirs": "THEME = \"dark\"\nFONT_SIZE = 14", "post": "DEBUG = False\n"}),
   ("p", u"VS Code 等編輯器會在衝突處顯示「Accept Current Change／Accept Incoming Change／Accept Both」按鈕，就是上面那幾個按鈕。減少衝突的方法：分支不要拖太久、常常把 main 合併進來、一個 commit 只改一件事、團隊溝通誰在改哪個檔案。"),
  ],
  u"兩個分支改了同一處，合併時 Git 會停下並標示 CONFLICT。檔案中 <<<<<<< HEAD 到 ======= 是目前分支的版本，======= 到 >>>>>>> 是合併進來的版本。解決步驟：找出 both modified 檔案、編輯並刪除所有標記、git add、git commit；git merge --abort 可放棄合併。分支不拖太久、常合併 main 可減少衝突。",
  [u"衝突標記中，HEAD 那一段是哪個分支的內容？", u"解決衝突後要執行哪兩個指令？", u"怎麼放棄這次合併？"]),

lesson(u"rebase：讓歷史變成一直線",
  u"把你的 commit 搬到最新的基礎上",
  [u"理解 rebase 的運作", u"比較 rebase 與 merge 的歷史", u"知道 rebase 會改變雜湊"],
  [("p", u"你在 feature-login 做了兩個 commit，這段期間 main 也前進了。除了 merge，還可以 <strong>rebase</strong>：把你的 commit「重新播放」在 main 的最新 commit 之後。"),
   ] + gex("rebase") + [
   ("p", u"比較前後兩張圖：原本分岔的歷史變成了<strong>一直線</strong>，好像你是在 main 最新版上才開始寫的。但仔細看雜湊：<code>ea55c3c</code> 變成 <code>5ab4cd7</code>、<code>9411b1a</code> 變成 <code>3b05a39</code>——rebase 不是搬移，而是<strong>複製出新的 commit</strong>（因為父 commit 變了，雜湊一定會變）。"),
   ("t", [u"", u"merge", u"rebase"],
    [[u"歷史形狀", u"保留真實的分岔與合併", u"一直線，乾淨"], [u"改寫歷史？", u"否，只新增合併 commit", u"是，你的 commit 被換成新的"], [u"衝突", u"一次解決", u"可能每個 commit 各解一次"],
     [u"安全性", u"任何時候都安全", u"只能對還沒分享出去的 commit 做"]]),
   ("p", u"rebase 途中遇到衝突：解決後 <code>git add</code>，再 <code>git rebase --continue</code>；想放棄就 <code>git rebase --abort</code>。"),
   _GRAPH,
   ("p", u"在模擬器裡試試：<code>git switch -c feature</code>、commit 兩次、<code>git switch main</code>、commit 一次、<code>git switch feature</code>、<code>git rebase main</code>，看 feature 的 commit 被複製到右邊，舊的變成虛線。"),
  ],
  u"git rebase main 把目前分支的 commit 重新播放在 main 的最新 commit 之後，讓歷史變成一直線；因為父 commit 改變，這些 commit 會被複製成新雜湊的 commit。merge 保留真實分岔、不改寫歷史、任何時候安全；rebase 歷史乾淨但改寫歷史，只能對未分享的 commit 使用。衝突時解決後 add 再 rebase --continue，或 --abort 放棄。",
  [u"rebase 後 commit 的雜湊為什麼會變？", u"merge 和 rebase 的歷史形狀有什麼不同？", u"rebase 衝突解決後要執行什麼？"]),

lesson(u"merge 還是 rebase？",
  u"rebase 的黃金守則",
  [u"記住 rebase 的黃金守則", u"知道兩者常見的使用時機", u"認識 pull 的兩種模式"],
  [("p", u"<strong>黃金守則：不要 rebase 已經 push、別人可能已經拿到的 commit。</strong>"),
   ("p", u"原因：rebase 會產生新 commit、丟掉舊的。如果同事的分支是建立在你的舊 commit 上，你 rebase 後強制推送，他的歷史就和 GitHub 對不上，會出現重複的 commit 和一堆莫名的衝突。"),
   ("t", [u"情境", u"建議"],
    [[u"自己的功能分支，還沒 push 或只有你在用", u"可以 rebase main，讓 PR 歷史乾淨"], [u"把功能合併回 main", u"在 GitHub 上用 Pull Request 合併（第 31 課的三種方式）"],
     [u"main、develop 等共用分支", u"永遠不要 rebase、不要強制推送"], [u"pull 時本機和 GitHub 都有新 commit", u"可以設定 pull 用 rebase，避免多出無意義的合併 commit"]]),
   ("p", u"最後一種情況很常見：你和同事都 push 了 main，你的 push 被拒絕："),
   ] + gex("pushrej") + [
   ("p", u"範例中設定了 <code>git config pull.rebase true</code>，所以 <code>git pull</code> 用 rebase 把你的 commit 接在同事的之後，歷史保持一直線。若不設定，新版 Git 在兩邊分岔時會要求你選擇：<code>git pull --rebase</code> 或 <code>git pull --no-rebase</code>（merge）。"),
   ("p", u"真的需要覆蓋遠端時（例如 rebase 了自己的 PR 分支），用 <code>git push --force-with-lease</code> 而不是 <code>--force</code>：前者會先確認遠端沒有你不知道的新 commit，避免覆蓋掉別人的工作。"),
  ],
  u"rebase 的黃金守則：不要 rebase 已經 push、別人可能拿到的 commit，否則他人的歷史會對不上。自己未分享的功能分支可以 rebase main；共用分支永不 rebase 或強制推送。push 被拒時 pull 可設定 pull.rebase true 讓歷史保持直線。需要覆蓋遠端時用 --force-with-lease 而非 --force。",
  [u"rebase 的黃金守則是什麼？", u"push 被拒絕（rejected）通常是什麼原因？", u"--force-with-lease 比 --force 安全在哪裡？"]),

lesson(u"分支策略",
  u"GitHub Flow、Git Flow、主幹開發",
  [u"認識三種常見的分支策略", u"比較它們的適用情境", u"為自己的專案選擇策略"],
  [("p", u"團隊要約定「什麼時候開分支、合併到哪裡」。三種常見做法："),
   ("t", [u"策略", u"規則", u"適合"],
    [[u"<strong>GitHub Flow</strong>", u"main 永遠可以部署；每件工作開一個短命分支 → Pull Request → 審查 → 合併回 main → 部署", u"網站、持續部署的服務，大多數團隊"],
     [u"<strong>Git Flow</strong>", u"main（正式版）＋ develop（開發中）＋ feature／release／hotfix 分支，各有合併規則", u"有明確版本發布週期的軟體（例如 App、桌面軟體）"],
     [u"<strong>主幹開發</strong>（Trunk-based）", u"大家頻繁地（每天）把小改動合併進 main，未完成的功能用「功能開關」藏起來", u"高度自動化測試的大團隊（Google 等）"]]),
   ("fig", svg(title(u"GitHub Flow：一件事一個分支"),
               P("M30 120 L610 120", BLUE, sw=3), T(620, 124, u"main", 11, BLUE, "start"),
               P("M100 120 C130 120 130 70 160 70 L260 70 C290 70 290 120 320 120", GREEN, sw=2.5), T(200, 62, u"feature/login", 10, GREEN),
               P("M360 120 C390 120 390 170 420 170 L500 170 C530 170 530 120 560 120", ORANGE, sw=2.5), T(460, 190, u"fix/typo", 10, ORANGE),
               C(320, 120, 8, BLUE, BLUE), C(560, 120, 8, BLUE, BLUE), T(320, 100, u"PR 合併", 9.5, MUTED), T(560, 100, u"PR 合併", 9.5, MUTED)), "0 0 660 210", u"GitHub Flow。"),
   ("p", u"給初學者與小團隊的建議：<strong>用 GitHub Flow</strong>。規則只有一條——不要直接在 main 上 commit，任何修改都開分支、發 PR。它簡單、跟 GitHub 的功能完美搭配，本課程後面的協作流程都以它為準。"),
  ],
  u"GitHub Flow：main 永遠可部署，每件工作開短命分支、發 PR 審查後合併；Git Flow：main 加 develop 加 feature、release、hotfix 分支，適合有版本週期的軟體；主幹開發：每天把小改動併入 main、用功能開關隱藏未完成功能，適合高度自動化的大團隊。初學者與小團隊建議用 GitHub Flow。",
  [u"GitHub Flow 的核心規則是什麼？", u"Git Flow 的 develop 分支用途？", u"主幹開發如何處理還沒完成的功能？"]),

lesson(u"cherry-pick 與 reflog",
  u"挑一個 commit、救回消失的 commit",
  [u"用 cherry-pick 複製單一 commit", u"用 reflog 找回被 reset 掉的 commit", u"理解 reflog 的期限"],
  [("h", u"cherry-pick：只拿我要的那一個"),
   ("p", u"experiment 分支有兩個 commit，你只想要其中「加入 util.py 小工具」那一個，不要實驗性修改："),
   ] + gex("cherry") + [
   ("p", u"cherry-pick 把那個 commit 的修改<strong>複製</strong>一份到目前分支，產生新雜湊（aec5ad2 → 21aeb91）。常見用途：把 main 上的 bug 修正搬到舊版本的維護分支。"),
   ("h", u"reflog：Git 的「黑盒子」"),
   ("p", u"不小心 <code>reset --hard</code> 掉了重要的 commit？別慌："),
   ] + gex("reflog") + [
   ("p", u"<code>git reflog</code> 記錄了 HEAD 在<strong>你這台電腦上</strong>走過的每一步，即使 commit 已經沒有任何分支指著它。找到它（HEAD@{1}），reset 回去或開一個新分支指向它（<code>git branch rescue 830b714</code>）就救回來了。"),
   ("p", u"限制：reflog 只存在本機、不會 push；沒有分支指向的 commit 大約 30 天到 90 天後會被清理（依設定）。另外，<strong>從來沒有 commit 過</strong>的修改（例如被 <code>git restore</code> 丟掉的）不在 reflog 裡，救不回來——所以多 commit 永遠是好習慣。"),
  ],
  u"git cherry-pick 雜湊 把指定 commit 的修改複製到目前分支（產生新雜湊），常用於把 bug 修正搬到維護分支。git reflog 記錄 HEAD 在本機走過的每一步，可找回被 reset 掉的 commit 並 reset 回去或開新分支指向它。reflog 只在本機、無人指向的 commit 約 30～90 天後清理；從未 commit 的修改救不回來。",
  [u"cherry-pick 是搬移還是複製？", u"reflog 存在哪裡？會被 push 嗎？", u"被 git restore 丟掉的修改能用 reflog 救回嗎？"]),
])

MODULES = [MODULE_A, MODULE_B, MODULE_C, MODULE_D]
