# -*- coding: utf-8 -*-
"""GitHub 從零到協作：模組 E～H（第 29～53 課）。"""
from gh_common import *

_PRFLOW = ghw({"t": "steps", "q": u"Pull Request 的一生（按步驟或「下一步」）：", "steps": [
  [u"開分支", u"<code>git switch -c fix/login-error</code>。永遠不要直接在 main 上改。", u"本機"],
  [u"寫程式、commit", u"一個 commit 做一件事，訊息寫清楚。", u"本機"],
  [u"push 分支", u"<code>git push -u origin fix/login-error</code>。push 後終端機會印出建立 PR 的網址。", u"本機 → GitHub"],
  [u"開 Pull Request", u"在 GitHub 上按 <b>Compare &amp; pull request</b>：選擇 base（要合併進去的，通常是 main）與 compare（你的分支），寫標題與說明。還沒完成可以先開成 <b>Draft</b>。", u"GitHub"],
  [u"自動檢查（CI）", u"GitHub Actions 自動跑測試、lint，結果顯示在 PR 下方：綠色勾勾或紅色叉叉。", u"GitHub"],
  [u"Code Review", u"指定 Reviewer。審查者逐行留言、提出建議，最後選 Approve 或 Request changes。", u"GitHub"],
  [u"修改、再 push", u"在同一個分支繼續 commit、push，PR 會自動更新，不用重開。", u"本機 → GitHub"],
  [u"合併", u"檢查都過、審查通過後按 <b>Merge</b>（merge commit／squash／rebase 三選一）。", u"GitHub"],
  [u"清理", u"刪除遠端分支（GitHub 上有按鈕），本機 <code>git switch main</code>、<code>git pull</code>、<code>git branch -d fix/login-error</code>。", u"本機"]]})

MODULE_E = (u"模組 E｜GitHub 協作", [

lesson(u"Pull Request",
  u"請大家看看我的修改",
  [u"理解 Pull Request 是什麼", u"走過一次完整的 PR 流程", u"寫出好的 PR 說明"],
  [("p", u"<strong>Pull Request</strong>（PR，拉取請求）的意思是：「我在這個分支做了一些修改，請把它<strong>拉</strong>進 main。」它不是 Git 的功能，而是 GitHub 在 Git 之上提供的<strong>討論與審查</strong>機制。"),
   ("p", u"先把分支推上 GitHub："),
   ] + gex("newbranch_push") + [
   ("p", u"推送到真正的 GitHub 時，終端機會多印一行網址，例如 <code>remote: Create a pull request for 'fix-typo' on GitHub by visiting: https://github.com/ming/demo/pull/new/fix-typo</code>，點它就能開 PR。到倉庫頁面時，GitHub 也會顯示黃色提示條與 <strong>Compare &amp; pull request</strong> 按鈕。"),
   _PRFLOW,
   ("h", u"好的 PR 說明"),
   ("ul", [u"<strong>做了什麼、為什麼</strong>：解決哪個問題？附上 Issue 編號，寫 <code>Fixes #42</code>，PR 合併時 Issue 會自動關閉。", u"<strong>怎麼測試的</strong>：讓審查者知道該檢查什麼。",
           u"<strong>畫面截圖</strong>：介面修改時，前後對照最清楚。", u"<strong>保持小</strong>：幾百行以內的 PR 比較容易被仔細審查、快速合併。"]),
  ],
  u"Pull Request 是 GitHub 提供的討論與審查機制：請求把某分支的修改拉進 main。流程：開分支、commit、push、在 GitHub 按 Compare & pull request（可先開 Draft）、CI 自動檢查、Code Review、在同一分支繼續 push 更新、合併、清理分支。好的 PR 說明寫明做了什麼與為什麼、用 Fixes #編號 連結 Issue、說明測試方式、附截圖，並保持小。",
  [u"Pull Request 是 Git 的功能嗎？", u"審查者要求修改時，需要重開一個 PR 嗎？", u"Fixes #42 有什麼作用？"]),

lesson(u"Code Review",
  u"審查與被審查",
  [u"在 PR 上留言與建議修改", u"理解 Approve 與 Request changes", u"學會給與接受回饋"],
  [("p", u"PR 頁面有四個分頁：<strong>Conversation</strong>（討論）、<strong>Commits</strong>、<strong>Checks</strong>（自動檢查）、<strong>Files changed</strong>（差異）。審查主要在 Files changed 進行："),
   ("ul", [u"點某一行左邊的 <strong>＋</strong> 號留言；拖曳可以選多行。", u"留言時按 <strong>Suggest changes</strong> 圖示，可以直接寫出建議的程式碼，作者按一下 <strong>Commit suggestion</strong> 就會套用。",
           u"所有留言寫完後按 <strong>Review changes</strong>，選一個結論："]),
   ("t", [u"結論", u"意思"],
    [[u"Comment", u"只是留言，沒有表態"], [u"Approve", u"核准，可以合併"], [u"Request changes", u"需要修改後才能合併（如果有設定保護規則，會擋住合併）"]]),
   ("p", u"作者修改後回覆留言並按 <strong>Resolve conversation</strong>，然後按 Reviewer 旁的🔄重新請求審查。"),
   ("h", u"審查的禮儀"),
   ("t", [u"審查者", u"作者"],
    [[u"對事不對人：「這裡可能會漏掉空字串」而不是「你寫錯了」", u"不要把審查當成攻擊；它是在幫你抓 bug"], [u"區分必要與建議：用「nit:」標示小地方（不改也行）", u"不同意就說明理由，討論是正常的"],
     [u"說明理由，附上文件或範例", u"每則留言都回覆或處理，不要默默忽略"], [u"也稱讚寫得好的地方", u"感謝審查者花的時間"]]),
   ("p", u"Code Review 不只是抓錯：它讓團隊中至少有兩個人懂每一段程式碼，也是新人學習的好機會。"),
  ],
  u"PR 有 Conversation、Commits、Checks、Files changed 分頁；在 Files changed 點行號旁＋留言、用 Suggest changes 寫出建議程式碼讓作者一鍵套用，最後以 Comment、Approve 或 Request changes 結論。作者修改後 Resolve 並重新請求審查。審查應對事不對人、區分必要與 nit、說明理由；作者應把審查當幫助並回應每則留言。",
  [u"Approve 和 Request changes 有什麼差別？", u"Suggest changes 的好處是什麼？", u"nit: 是什麼意思？"]),

lesson(u"三種合併方式",
  u"merge commit、squash、rebase",
  [u"比較 GitHub 的三種合併按鈕", u"看出各自產生的歷史", u"為團隊選擇合併方式"],
  [("p", u"GitHub 的合併按鈕旁有一個下拉選單，提供三種方式："),
   ("t", [u"方式", u"結果", u"優點", u"缺點"],
    [[u"<strong>Create a merge commit</strong>", u"保留分支所有 commit，再加一個合併 commit", u"完整保留真實歷史", u"main 的歷史有很多分岔與「修錯字」之類的小 commit"],
     [u"<strong>Squash and merge</strong>", u"把 PR 所有 commit 壓成<strong>一個</strong> commit 放到 main", u"main 上一個 PR 一個 commit，非常乾淨", u"分支內的細節歷史消失"],
     [u"<strong>Rebase and merge</strong>", u"把 PR 的每個 commit 複製到 main 最後面，不產生合併 commit", u"一直線，保留每個 commit", u"commit 雜湊改變；每個 commit 都要有意義"]]),
   ("p", u"Squash 是很多團隊的預設選擇。它在本機的等價指令是 <code>git merge --squash</code>："),
   ] + gex("squash") + [
   ("p", u"分支上的三個 commit（包括「修錯字」）在 main 上變成了一個「登入與登出功能 (#12)」。GitHub 預設會在 squash 的訊息後面附上 PR 編號，方便日後追查。"),
   ("p", u"倉庫管理者可以在 Settings → General → Pull Requests 中只開放其中幾種方式。另外，Squash 或 Rebase 合併後，本機的功能分支在 Git 看來「沒有被合併」（因為 main 上的是新 commit），所以要用 <code>git branch -D</code> 刪除。"),
  ],
  u"GitHub 有三種合併方式：Create a merge commit 保留所有 commit 加合併 commit（真實但雜亂）；Squash and merge 把 PR 壓成一個 commit（乾淨但失去細節，常見預設）；Rebase and merge 把每個 commit 複製到 main 後面（直線但雜湊改變）。squash 對應 git merge --squash。管理者可在設定中限制方式；squash／rebase 後本機分支要用 -D 刪除。",
  [u"Squash and merge 會在 main 產生幾個 commit？", u"哪種方式會保留分支上的每一個 commit 且不產生合併 commit？", u"squash 合併後為什麼本機分支要用 -D 刪除？"]),

lesson(u"Fork：參與別人的專案",
  u"沒有寫入權限也能貢獻",
  [u"理解 fork 是什麼", u"走過 fork 貢獻流程", u"區分 fork 與 clone"],
  [("p", u"你想修正某個開源專案的錯字，但你沒有它的寫入權限。做法是 <strong>fork</strong>：在 GitHub 上把整個倉庫<strong>複製一份到你的帳號底下</strong>，你對這份有完整權限。"),
   ("fig", svg(title(u"Fork 貢獻流程"),
               box(30, 40, 180, 60, u"原專案", [u"torvalds/tool"], BLUE), box(430, 40, 180, 60, u"你的 fork", [u"ming/tool"], GREEN),
               box(430, 170, 180, 60, u"你的電腦", [u"clone 下來的"], ORANGE),
               A(210, 60, 430, 60, MUTED), T(320, 52, u"① Fork（GitHub 上）", 10, MUTED), A(520, 100, 520, 170, MUTED), T(530, 140, u"② clone", 10, MUTED, "start"),
               A(500, 170, 500, 100, GREEN), T(490, 140, u"③ push", 10, GREEN, "end"), A(430, 85, 210, 85, RED), T(320, 100, u"④ Pull Request", 10, RED)), "0 0 640 250", u"fork、clone、push、PR。"),
   ("ol", [u"在原專案頁面右上角按 <strong>Fork</strong>。", u"<code>git clone</code> <strong>你的 fork</strong>（不是原專案）。", u"開分支、修改、commit，push 到你的 fork。",
           u"到 GitHub 上按 <strong>Contribute → Open pull request</strong>，PR 的方向是「你的 fork 的分支 → 原專案的 main」。", u"原專案的維護者審查、合併。"]),
   ("t", [u"", u"clone", u"fork"],
    [[u"在哪裡發生", u"GitHub → 你的電腦", u"GitHub 上，一個帳號 → 另一個帳號"], [u"是 Git 指令嗎", u"是", u"不是，是 GitHub 的功能"], [u"目的", u"在本機工作", u"取得一份你有權限的副本"]]),
   ("p", u"有寫入權限的團隊成員通常不用 fork，直接在原倉庫開分支就好；fork 主要用在開源專案的外部貢獻者。"),
  ],
  u"Fork 是 GitHub 功能：把別人的倉庫複製到你的帳號下，讓沒有寫入權限的人也能貢獻。流程：按 Fork、clone 你的 fork、開分支修改並 push 到 fork、在 GitHub 從 fork 的分支向原專案發 PR、由維護者審查合併。clone 是 Git 指令、從 GitHub 到電腦；fork 是在 GitHub 帳號之間複製。團隊成員通常直接開分支。",
  [u"fork 和 clone 的差別？", u"fork 流程的 PR 方向是什麼？", u"有寫入權限時還需要 fork 嗎？"]),

lesson(u"讓 fork 跟上原專案",
  u"upstream 同步",
  [u"加入 upstream 遠端", u"把原專案的新 commit 同步到 fork", u"使用 GitHub 的 Sync fork 按鈕"],
  [("p", u"fork 之後，原專案持續有人更新，你的 fork 卻停在 fork 那一刻。要同步，先把原專案加成第二個遠端，慣例叫 <code>upstream</code>："),
   ] + gex("upstream") + [
   ("ul", [u"<code>origin</code>：你的 fork（你可以 push）。", u"<code>upstream</code>：原專案（只讀取）。", u"<code>git fetch upstream</code> 把原專案的新 commit 拿下來，成為 <code>upstream/main</code>。",
           u"<code>git merge upstream/main</code> 合併到你本機的 main，再 <code>git push origin main</code> 更新你的 fork。"]),
   ("p", u"更簡單的方法：在 GitHub 上你的 fork 頁面，按 <strong>Sync fork → Update branch</strong>，GitHub 直接幫你同步，之後本機 <code>git pull</code> 即可。"),
   ("p", u"開新 PR 前先同步，能大幅減少衝突。如果你的 PR 分支已經落後很多，可以 <code>git rebase upstream/main</code> 再 <code>git push --force-with-lease</code>（這是你自己的分支，可以這樣做）。"),
  ],
  u"fork 不會自動跟上原專案。git remote add upstream 原專案網址 加入第二個遠端；git fetch upstream 取得原專案更新成為 upstream/main；git merge upstream/main 合併後 git push origin main 更新 fork。也可在 GitHub 按 Sync fork。開 PR 前先同步可減少衝突，落後的 PR 分支可 rebase upstream/main 後 --force-with-lease。",
  [u"origin 和 upstream 各指向誰？", u"同步 fork 的三個指令是什麼？", u"GitHub 網頁上有哪個按鈕可以同步 fork？"]),

lesson(u"Issue",
  u"回報問題與追蹤工作",
  [u"建立與管理 Issue", u"使用標籤、指派、里程碑", u"在 commit 與 PR 中連結 Issue"],
  [("p", u"<strong>Issue</strong> 是 GitHub 的「待辦事項＋討論串」：回報 bug、提議新功能、提問、記錄任務。每個 Issue 有一個編號（與 PR 共用編號序列），例如 <code>#42</code>。"),
   ("t", [u"功能", u"用途"],
    [[u"Labels 標籤", u"分類：<code>bug</code>、<code>enhancement</code>、<code>good first issue</code>（適合新手）、<code>help wanted</code>"], [u"Assignees 指派", u"誰負責處理"],
     [u"Milestone 里程碑", u"歸到某個版本或期限，如「v2.0」，可看完成百分比"], [u"Issue 範本", u"在 <code>.github/ISSUE_TEMPLATE/</code> 放範本，要求回報者填寫重現步驟、環境等"],
     [u"Sub-issues", u"把大任務拆成子任務"]]),
   ("h", u"好的 bug 回報"),
   ("code", u"## 發生了什麼\n按下「匯出 PDF」後頁面一片空白。\n\n## 重現步驟\n1. 登入後進入「報表」\n2. 選擇 2025 年\n3. 按「匯出 PDF」\n\n## 預期結果\n下載 PDF 檔。\n\n## 環境\nWindows 11、Chrome 130、版本 v2.3.1"),
   ("h", u"自動連結"),
   ("ul", [u"在任何留言、commit 訊息中寫 <code>#42</code>，會自動變成連到 Issue 42 的連結。", u"在 PR 說明或 commit 訊息中寫 <code>Fixes #42</code>、<code>Closes #42</code>、<code>Resolves #42</code>，合併到預設分支時自動關閉 Issue。",
           u"寫 <code>@使用者名稱</code> 會通知那個人。"]),
   ("p", u"另外還有 <strong>Discussions</strong>：適合開放式的問答與交流，不像 Issue 那樣代表「一件要完成的事」。"),
  ],
  u"Issue 是 GitHub 的待辦與討論串，編號與 PR 共用。可用 Labels 分類（bug、enhancement、good first issue）、Assignees 指派、Milestone 歸到版本、Issue 範本規範回報內容、Sub-issues 拆分任務。好的 bug 回報包含現象、重現步驟、預期結果、環境。寫 #42 自動連結、Fixes #42 合併時自動關閉、@名稱 通知人。開放式問答可用 Discussions。",
  [u"good first issue 標籤的用途？", u"好的 bug 回報應包含哪些部分？", u"怎麼讓 PR 合併時自動關閉 Issue？"]),

lesson(u"Projects 看板",
  u"用 GitHub 管理工作",
  [u"建立 Projects 看板", u"使用自訂欄位與檢視", u"設定自動化"],
  [("p", u"<strong>GitHub Projects</strong> 是一個可以放 Issue 與 PR 的看板／表格，像 Trello 或 Jira 的簡化版。它屬於使用者或組織，可以跨好幾個倉庫。"),
   ("t", [u"檢視方式", u"適合"],
    [[u"Board（看板）", u"把卡片在「Todo → In Progress → Done」欄之間拖曳"], [u"Table（表格）", u"像試算表一樣一次編輯很多項目的欄位"], [u"Roadmap（時間軸）", u"依日期排列，看專案進度"]]),
   ("ul", [u"<strong>自訂欄位</strong>：Status、優先度、預估時間、迭代（Iteration，例如兩週一個 Sprint）。", u"<strong>篩選與分組</strong>：例如「只看指派給我的」「依優先度分組」，可以存成不同的檢視。",
           u"<strong>內建自動化</strong>：Issue 關閉時自動移到 Done、PR 合併時自動更新狀態、新 Issue 自動加入看板。", u"<strong>草稿項目</strong>：還沒成形的想法可以先寫成草稿，之後再轉成正式 Issue。"]),
   ("p", u"一個實用的小團隊做法：每週開會時打開 Board 檢視，從左到右看一遍；每個人只從 Todo 拿最上面的卡片，PR 合併後卡片自動到 Done。"),
  ],
  u"GitHub Projects 是可放入 Issue 與 PR 的看板／表格，屬於使用者或組織、可跨倉庫。有 Board、Table、Roadmap 三種檢視；可加自訂欄位（狀態、優先度、迭代）、篩選分組並存成檢視；內建自動化可在 Issue 關閉或 PR 合併時更新狀態；也可先建草稿項目。",
  [u"Projects 有哪三種檢視？", u"Projects 能跨多個倉庫嗎？", u"舉一個 Projects 內建自動化的例子。"]),

lesson(u"保護 main 分支",
  u"規則集與必要檢查",
  [u"理解為什麼要保護分支", u"設定常見的保護規則", u"認識 CODEOWNERS 與合併佇列"],
  [("p", u"團隊大了，總會有人不小心直接 push 到 main、或合併了測試沒過的 PR。GitHub 可以替分支加上規則（Settings → Rules → <strong>Rulesets</strong>，舊介面為 Branches → Branch protection rules）："),
   ("t", [u"規則", u"效果"],
    [[u"Require a pull request before merging", u"不能直接 push，一定要透過 PR"], [u"Required approvals", u"至少要幾個人 Approve"], [u"Require status checks to pass", u"指定的 CI 檢查（例如測試）要綠燈才能合併"],
     [u"Require branches to be up to date", u"PR 分支必須包含 main 的最新 commit"], [u"Block force pushes", u"禁止強制推送"], [u"Restrict deletions", u"禁止刪除這個分支"],
     [u"Require signed commits", u"commit 必須有簽章"], [u"Require linear history", u"禁止合併 commit（只能 squash 或 rebase）"]]),
   ("h", u"CODEOWNERS"),
   ("p", u"在 <code>.github/CODEOWNERS</code> 檔案中指定誰負責哪些檔案，有人修改時會自動請他審查："),
   ("code", u"# 預設：前端組審查所有檔案\n*            @ming-org/frontend\n# 資料庫相關要 DBA 審查\n/db/         @hua\n*.sql        @hua\n# 文件\n/docs/       @ming"),
   ("p", u"搭配「Require review from Code Owners」規則，就能確保重要的檔案一定經過負責人看過。"),
   ("p", u"大型專案還可以開啟 <strong>Merge queue</strong>（合併佇列）：多個 PR 排隊，GitHub 依序把它們與最新的 main 組合起來再測一次，避免「兩個各自都通過的 PR 合在一起卻壞掉」。"),
  ],
  u"分支規則（Rulesets 或 Branch protection rules）可要求透過 PR 合併、需幾人核准、CI 檢查通過、分支須最新，並可禁止強制推送與刪除、要求簽章或線性歷史。.github/CODEOWNERS 指定檔案負責人並自動請其審查，可搭配要求 Code Owner 審查。Merge queue 讓多個 PR 依序與最新 main 一起測試再合併。",
  [u"怎麼禁止任何人直接 push 到 main？", u"CODEOWNERS 檔案的作用是什麼？", u"Merge queue 解決了什麼問題？"]),

lesson(u"團隊與權限",
  u"Organization、協作者與角色",
  [u"認識個人帳號與組織", u"了解倉庫的權限等級", u"安全地管理成員"],
  [("p", u"倉庫可以屬於<strong>個人帳號</strong>或<strong>組織</strong>（Organization）。個人倉庫可以邀請 <strong>Collaborator</strong>（協作者）；公司或社群專案則建議建立組織，把成員分成 <strong>Teams</strong>，再把團隊指派到倉庫。"),
   ("t", [u"角色", u"能做什麼"],
    [[u"Read", u"看程式碼、開 Issue 和留言、clone"], [u"Triage", u"Read ＋ 管理 Issue 與 PR（標籤、指派、關閉），不能 push"], [u"Write", u"Triage ＋ push、合併 PR"],
     [u"Maintain", u"Write ＋ 管理部分倉庫設定（不含敏感與破壞性操作）"], [u"Admin", u"完全控制，包括刪除倉庫、變更可見性、管理權限"]]),
   ("ul", [u"<strong>最小權限原則</strong>：只給完成工作所需的權限。大部分開發者 Write 就夠了，Admin 留給少數人。", u"組織可以<strong>要求所有成員啟用兩步驟驗證</strong>。",
           u"成員離職時從組織移除，他就失去所有倉庫的權限——這是用組織而不是個人帳號管理公司專案的主要理由。", u"<strong>Outside collaborator</strong>：不是組織成員、但被允許存取特定倉庫的外部人員（例如外包）。"]),
   ("p", u"公開倉庫的可見性設定（Settings → General → Danger Zone）可以把私有轉公開或反之；轉公開前務必確認歷史中沒有密碼與金鑰（第 49 課）。"),
  ],
  u"倉庫可屬於個人（邀請 Collaborator）或組織（以 Teams 管理成員）。權限由低到高：Read、Triage（管理 Issue／PR）、Write（push、合併）、Maintain、Admin（刪除、可見性、權限）。應遵循最小權限原則、要求 2FA；組織讓離職者一次失去所有權限；Outside collaborator 是外部協作者。私有轉公開前要確認歷史中沒有機密。",
  [u"Triage 和 Write 差在哪？", u"為什麼公司專案建議用組織而不是個人帳號？", u"什麼是最小權限原則？"]),
])

_YML = u"""name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: pytest"""

MODULE_F = (u"模組 F｜自動化與進階功能", [

lesson(u"GitHub Actions 入門",
  u"workflow、job、step",
  [u"理解 GitHub Actions 的用途", u"讀懂 workflow 檔的結構", u"認識觸發事件與 runner"],
  [("p", u"<strong>GitHub Actions</strong> 讓你在發生某些事情時（push、開 PR、排程、手動按按鈕）自動執行工作：跑測試、檢查格式、建置、部署、發布⋯⋯。設定寫在倉庫的 <code>.github/workflows/*.yml</code>，用 YAML 格式。"),
   ("code", _YML),
   ("t", [u"名詞", u"意思", u"上例"],
    [[u"workflow", u"一個 yml 檔就是一個工作流程", u"CI"], [u"on（event）", u"什麼時候觸發", u"push 到 main，或任何 PR"], [u"job", u"一組步驟，在一台機器上執行；多個 job 預設平行執行", u"test"],
     [u"runs-on（runner）", u"在哪種機器上跑", u"GitHub 提供的 Ubuntu 虛擬機"], [u"step", u"一個步驟：<code>uses</code> 使用別人寫好的 action，<code>run</code> 執行指令", u"checkout、安裝 Python、裝套件、跑 pytest"]]),
   ("ul", [u"<code>actions/checkout</code> 把你的倉庫程式碼抓到 runner 上——幾乎每個 workflow 第一步都是它。", u"<code>@v4</code> 是 action 的版本；為了安全，重要專案常改成固定到完整的 commit 雜湊。",
           u"YAML 用<strong>縮排</strong>表示層級，只能用空白不能用 Tab，縮排錯誤是最常見的錯。"]),
   ("p", u"執行結果在倉庫的 <strong>Actions</strong> 分頁，點進去可以看每個 step 的輸出。公開倉庫使用 GitHub 提供的 runner 免費；私有倉庫每月有免費額度，超過要付費。"),
  ],
  u"GitHub Actions 在 push、PR、排程或手動觸發時自動執行工作，設定寫在 .github/workflows/*.yml。workflow 是一個檔、on 是觸發事件、job 是在一台 runner 上執行的步驟組（預設平行）、runs-on 指定機器、step 用 uses 引用 action 或用 run 執行指令。checkout 幾乎是第一步；YAML 以空白縮排。公開倉庫免費、私有倉庫有每月額度。",
  [u"workflow 檔要放在哪個資料夾？", u"uses 和 run 有什麼不同？", u"為什麼幾乎每個 workflow 第一步都是 actions/checkout？"]),

lesson(u"CI：每次 push 自動測試",
  u"持續整合",
  [u"理解 CI 的意義", u"在 PR 上看懂檢查結果", u"用矩陣在多個版本上測試"],
  [("p", u"<strong>CI（持續整合）</strong>的想法是：每次有人 push 或開 PR，就自動跑一次完整的測試。問題在剛出現時就被發現，而不是上線後才爆炸。"),
   ("p", u"上一課的 workflow 就是 CI。PR 頁面下方會顯示檢查結果：🟡 執行中、✅ 通過、❌ 失敗。點 <strong>Details</strong> 看失敗的 log；搭配分支保護的「Require status checks」（第 36 課），測試沒過就無法合併。"),
   ("h", u"矩陣：一次測好幾種環境"),
   ("code", u"jobs:\n  test:\n    strategy:\n      matrix:\n        os: [ubuntu-latest, windows-latest, macos-latest]\n        python: [\"3.11\", \"3.12\", \"3.13\"]\n    runs-on: ${{ matrix.os }}\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: ${{ matrix.python }}\n      - run: pip install -r requirements.txt\n      - run: pytest"),
   ("p", u"這會產生 3 × 3 = 9 個 job 平行執行，確保你的程式在三種作業系統、三個 Python 版本上都能跑。<code>${{ }}</code> 是 Actions 的運算式語法。"),
   ("ul", [u"<strong>快取</strong>：<code>actions/setup-python</code>、<code>actions/setup-node</code> 都有 <code>cache</code> 選項，可以快取下載的套件，加快每次執行。",
           u"<strong>Lint</strong>：除了測試，CI 也常跑格式檢查（如 ruff、eslint、prettier），讓程式風格一致。", u"<strong>徽章</strong>：在 README 放上 workflow 的狀態徽章，大家一眼就知道 main 是不是綠燈。"]),
  ],
  u"CI 持續整合在每次 push 或開 PR 時自動跑完整測試，讓問題及早發現。PR 下方顯示執行中、通過或失敗，Details 看 log，搭配分支保護可讓測試失敗時無法合併。strategy.matrix 可一次在多種作業系統與版本上測試（3×3 產生 9 個 job），${{ }} 是運算式語法；還可加入快取、lint 與狀態徽章。",
  [u"CI 的核心想法是什麼？", u"matrix 有 3 種 OS 和 3 種版本，會產生幾個 job？", u"怎麼讓測試沒過的 PR 無法合併？"]),

lesson(u"GitHub Pages：免費架網站",
  u"從倉庫直接發布網頁",
  [u"用 GitHub Pages 發布靜態網站", u"了解兩種發布來源", u"知道 Pages 的限制"],
  [("p", u"<strong>GitHub Pages</strong> 可以把倉庫裡的 HTML、CSS、JavaScript 直接變成一個公開的網站，網址是 <code>https://使用者名稱.github.io/倉庫名稱/</code>。個人作品集、專案文件、部落格都很適合。"),
   ("t", [u"發布來源", u"設定", u"適合"],
    [[u"Deploy from a branch", u"Settings → Pages → 選分支（如 main）與資料夾（/ 或 /docs）", u"純 HTML 網站，什麼都不用建置"],
     [u"GitHub Actions", u"Settings → Pages → Source 選 GitHub Actions，用 workflow 建置後發布", u"需要建置的網站（React、Vue、Hugo、Astro 等）"]]),
   ("p", u"最簡單的做法：建立倉庫 <code>ming.github.io</code>（倉庫名稱等於「使用者名稱.github.io」），放一個 <code>index.html</code>，幾分鐘後打開 <code>https://ming.github.io</code> 就看得到了。"),
   ("code", u"# 用 Actions 部署的 workflow 核心\npermissions:\n  pages: write\n  id-token: write\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    environment: github-pages\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci && npm run build\n      - uses: actions/upload-pages-artifact@v3\n        with:\n          path: dist\n      - uses: actions/deploy-pages@v4"),
   ("ul", [u"只能放<strong>靜態</strong>網站：沒有伺服器端程式、沒有資料庫。", u"可以設定<strong>自訂網域</strong>，並免費啟用 HTTPS。",
           u"免費方案下，公開倉庫才能使用 Pages。<strong>不要</strong>拿來架商業網店或放機密資料。", u"網站有容量與流量的使用限制，詳見官方文件。"]),
  ],
  u"GitHub Pages 把倉庫中的靜態檔案發布成網站（使用者名稱.github.io/倉庫名稱）。發布來源可選分支（純 HTML，設定分支與 / 或 /docs）或 GitHub Actions（先建置再用 upload-pages-artifact 與 deploy-pages 發布）。名為「使用者名稱.github.io」的倉庫會成為根網址。只支援靜態網站，可設自訂網域與免費 HTTPS，免費方案需公開倉庫，有容量流量限制。",
  [u"GitHub Pages 能跑資料庫嗎？", u"React 網站應該選哪種發布來源？", u"倉庫取什麼名稱可以得到 https://ming.github.io？"]),

lesson(u"Secrets 與環境變數",
  u"不要把金鑰寫在程式碼裡",
  [u"在 Actions 中使用 Secrets", u"區分 secrets 與 variables", u"理解 GITHUB_TOKEN 與權限"],
  [("p", u"部署時常需要密碼、API 金鑰。它們<strong>絕對不能</strong>寫在 workflow 檔或程式碼中（任何能看倉庫的人都看得到）。正確做法是存成 <strong>Secret</strong>：Settings → Secrets and variables → Actions → New repository secret。"),
   ("code", u"steps:\n  - run: ./deploy.sh\n    env:\n      API_KEY: ${{ secrets.API_KEY }}\n      REGION: ${{ vars.REGION }}"),
   ("t", [u"", u"Secrets", u"Variables"],
    [[u"用途", u"密碼、金鑰、token", u"不機密的設定，如區域、網址"], [u"寫入後看得到嗎", u"不行，只能覆蓋", u"可以"], [u"出現在 log 中", u"自動遮成 <code>***</code>", u"照常顯示"], [u"語法", u"<code>${{ secrets.名稱 }}</code>", u"<code>${{ vars.名稱 }}</code>"]]),
   ("ul", [u"<strong>層級</strong>：可以設在倉庫、組織（多個倉庫共用）、或 <strong>Environment</strong>（例如 production 環境，可以要求有人核准才部署）。",
           u"<strong>GITHUB_TOKEN</strong>：每次執行自動產生的臨時 token，用來操作本倉庫（例如留言、發布）。用 <code>permissions:</code> 把它的權限縮到最小。",
           u"<strong>fork 來的 PR 拿不到 secrets</strong>：這是安全設計，避免陌生人開 PR 把你的金鑰印出來。", u"能連到雲端服務時，優先用 <strong>OIDC</strong>（無需長期金鑰的短期憑證）取代存放雲端金鑰。"]),
   ("p", u"本機開發時，機密放在 <code>.env</code> 檔並加入 .gitignore（第 14 課），在 README 裡附一個沒有真實值的 <code>.env.example</code> 告訴別人需要哪些變數。"),
  ],
  u"金鑰不能寫在程式碼或 workflow 中，應存為 Secret，用 ${{ secrets.名稱 }} 取用；Secrets 寫入後不可讀、log 中自動遮蔽，不機密的設定用 Variables（${{ vars.名稱 }}）。可設在倉庫、組織或 Environment（可要求核准）。GITHUB_TOKEN 是自動產生的臨時 token，用 permissions 縮小權限；fork 的 PR 拿不到 secrets；雲端可用 OIDC。本機用 .env 加 .gitignore 與 .env.example。",
  [u"Secrets 和 Variables 有什麼不同？", u"為什麼 fork 來的 PR 拿不到 secrets？", u".env.example 的用途是什麼？"]),

lesson(u"Releases 與套件發布",
  u"把版本交到使用者手上",
  [u"在 GitHub 建立 Release", u"自動產生更新說明", u"用 Actions 在打 tag 時自動發布"],
  [("p", u"<strong>Release</strong> 是建立在 tag（第 18 課）之上的「發布頁面」：版本號、更新說明、可下載的檔案（例如編譯好的安裝程式）。在倉庫右側 Releases → Draft a new release："),
   ("ol", [u"選擇或建立一個 tag（如 <code>v1.2.0</code>）。", u"按 <strong>Generate release notes</strong>：GitHub 會自動列出上次發布以來合併的所有 PR 與貢獻者。", u"拖曳上傳附件（binaries）。", u"勾選 <strong>Set as a pre-release</strong> 表示測試版，或直接發布。"]),
   ("p", u"使用者可以按倉庫的 Watch → Custom → Releases，只在有新版本時收到通知。"),
   ("h", u"打 tag 自動發布"),
   ("code", u"on:\n  push:\n    tags: [\"v*\"]\npermissions:\n  contents: write\njobs:\n  release:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: make build\n      - run: gh release create \"$GITHUB_REF_NAME\" dist/* --generate-notes\n        env:\n          GH_TOKEN: ${{ github.token }}"),
   ("p", u"這樣只要 <code>git tag -a v1.2.0 -m ... && git push origin v1.2.0</code>，Actions 就會自動建置並建立 Release。"),
   ("p", u"<strong>GitHub Packages</strong> 則可以存放 npm、Maven、NuGet 套件與 Docker 映像檔（ghcr.io）。不過 Python 與 JavaScript 的公開套件通常還是發布到 PyPI、npmjs.com，也能用 Actions 自動完成。"),
  ],
  u"Release 建立在 tag 之上，包含版本號、更新說明與可下載附件；Generate release notes 自動列出合併的 PR 與貢獻者，可標為 pre-release。使用者可 Watch 只訂閱 Releases。用 on: push: tags: v* 的 workflow 搭配 gh release create 可在推送 tag 時自動發布。GitHub Packages 存放 npm、Maven、Docker（ghcr.io）等套件。",
  [u"Release 和 tag 的關係是什麼？", u"Generate release notes 會產生什麼？", u"怎麼讓 push tag 時自動發布？"]),

lesson(u"安全性功能",
  u"Dependabot、Secret scanning、Code scanning",
  [u"認識 GitHub 的安全工具", u"處理 Dependabot 的警告與 PR", u"了解 push protection"],
  [("p", u"倉庫的 <strong>Security</strong> 分頁集中了幾個自動化安全工具（公開倉庫大多免費）："),
   ("t", [u"工具", u"做什麼"],
    [[u"Dependabot alerts", u"你用的套件出現已知漏洞時發出警告"], [u"Dependabot security updates", u"自動開 PR 把有漏洞的套件升級到修補版本"],
     [u"Dependabot version updates", u"定期開 PR 把套件升到最新版（用 <code>.github/dependabot.yml</code> 設定頻率）"], [u"Secret scanning", u"掃描倉庫中是否有外洩的 token、金鑰"],
     [u"Push protection", u"<strong>在你 push 時</strong>就擋下含有已知格式金鑰的 commit"], [u"Code scanning（CodeQL）", u"靜態分析程式碼中的安全漏洞，例如 SQL 注入"]]),
   ("code", u"# .github/dependabot.yml\nversion: 2\nupdates:\n  - package-ecosystem: \"pip\"\n    directory: \"/\"\n    schedule:\n      interval: \"weekly\"\n  - package-ecosystem: \"github-actions\"\n    directory: \"/\"\n    schedule:\n      interval: \"monthly\""),
   ("p", u"收到 Dependabot 的 PR 時：看 CI 是否通過、讀一下套件的更新說明（尤其是主版號升級），沒問題就合併。不要讓這些 PR 堆積——越晚升級，一次要跨的版本越多。"),
   ("p", u"如果 push protection 擋下了你的 push，<strong>不要選擇略過</strong>：把金鑰從 commit 中移除（amend 或 reset），改用 Secret 或 .env。萬一金鑰真的上去了，要<strong>立刻到服務商那裡撤銷並換一把新的</strong>——刪掉 commit 不夠，它可能已經被複製走了（第 49 課）。"),
   ("p", u"另外可以在倉庫放一個 <code>SECURITY.md</code>，告訴別人發現漏洞時該私下怎麼聯絡你，而不是公開開 Issue。"),
  ],
  u"Security 分頁有 Dependabot（漏洞警告、自動開修補 PR、用 dependabot.yml 定期升級）、Secret scanning 與 Push protection（push 時就擋下含金鑰的 commit）、Code scanning（CodeQL 靜態分析）。Dependabot PR 要看 CI 與更新說明後盡快合併。金鑰外洩時要立刻撤銷並更換，刪 commit 不夠。SECURITY.md 說明漏洞的私下回報方式。",
  [u"Dependabot 能幫你做哪些事？", u"push protection 擋下金鑰時該怎麼處理？", u"金鑰已經推上 GitHub，只刪掉 commit 夠嗎？"]),

lesson(u"Markdown 與 README",
  u"專案的門面",
  [u"掌握 GitHub Flavored Markdown 語法", u"寫出好的 README", u"認識其他標準檔案"],
  [("p", u"GitHub 上的 README、Issue、PR、留言都用 <strong>Markdown</strong> 撰寫——用簡單的符號表示格式。GitHub 版本叫 GFM（GitHub Flavored Markdown）："),
   ("t", [u"寫法", u"效果"],
    [[u"<code># 標題</code>、<code>## 小標題</code>", u"標題（# 越多層級越小）"], [u"<code>**粗體**</code>、<code>*斜體*</code>、<code>~~刪除~~</code>", u"文字樣式"],
     [u"<code>- 項目</code>、<code>1. 項目</code>", u"清單"], [u"<code>- [ ] 待辦</code>、<code>- [x] 完成</code>", u"勾選清單（在 Issue 中可以直接點）"],
     [u"<code>[文字](網址)</code>、<code>![說明](圖片網址)</code>", u"連結與圖片"], [u"<code>`code`</code>", u"行內程式碼"], [u"三個反引號加語言名稱", u"有語法上色的程式碼區塊"],
     [u"<code>| A | B |</code> 加 <code>|---|---|</code>", u"表格"], [u"<code>&gt; [!NOTE]</code>", u"提示框（NOTE、TIP、IMPORTANT、WARNING、CAUTION）"]]),
   ("p", u"GitHub 還支援 <code>```mermaid</code> 畫流程圖、<code>$...$</code> 寫數學公式、<code>:smile:</code> 表情符號。"),
   ("h", u"好的 README 包含"),
   ("ol", [u"<strong>這是什麼</strong>：一兩句話說明專案用途，附截圖。", u"<strong>安裝</strong>：照著貼上就能跑的指令。", u"<strong>使用方式</strong>：最常見的用法範例。",
           u"<strong>如何貢獻</strong>：或連到 CONTRIBUTING.md。", u"<strong>授權</strong>：用什麼授權條款。"]),
   ("t", [u"檔案", u"用途"],
    [[u"<code>LICENSE</code>", u"授權條款（第 51 課）"], [u"<code>CONTRIBUTING.md</code>", u"貢獻指南"], [u"<code>CODE_OF_CONDUCT.md</code>", u"行為準則"], [u"<code>SECURITY.md</code>", u"漏洞回報方式"],
     [u"<code>.github/pull_request_template.md</code>", u"PR 說明範本"]]),
   ("p", u"小彩蛋：建立一個與使用者名稱同名的倉庫（如 <code>ming/ming</code>），它的 README 會顯示在你的個人頁面最上方，可以當作自我介紹。"),
  ],
  u"GitHub 用 GFM Markdown：# 標題、**粗體**、- 清單、- [ ] 勾選清單、[文字](網址)、反引號程式碼、| 表格、> [!NOTE] 提示框，並支援 mermaid、數學與表情符號。好的 README 說明是什麼、安裝、使用、如何貢獻、授權。其他標準檔案：LICENSE、CONTRIBUTING.md、CODE_OF_CONDUCT.md、SECURITY.md、PR 範本。與使用者名稱同名的倉庫 README 會顯示在個人頁面。",
  [u"怎麼在 Markdown 中做出可以打勾的清單？", u"好的 README 應該包含哪些段落？", u"怎麼在個人頁面顯示自我介紹？"]),

lesson(u"gh、Codespaces 與 Copilot",
  u"更多 GitHub 工具",
  [u"用 gh 命令列操作 GitHub", u"認識 Codespaces 雲端開發環境", u"了解 Copilot 的用途與注意事項"],
  [("h", u"gh：GitHub 官方命令列工具"),
   ("p", u"<code>git</code> 管理本機的版本歷史；<code>gh</code> 則讓你在終端機操作 GitHub 網站上的功能（PR、Issue、Release、Actions），不用切到瀏覽器。安裝：cli.github.com，或 <code>brew install gh</code>、<code>winget install GitHub.cli</code>。"),
   cmd(u"gh auth login                 # 登入並設定 Git 驗證\ngh repo create my-app --public --clone\ngh pr create --fill            # 用 commit 訊息自動填寫 PR\ngh pr list\ngh pr checkout 42             # 把別人的 PR 抓下來測試\ngh pr merge 42 --squash --delete-branch\ngh issue create --title \"匯出失敗\" --body \"重現步驟⋯⋯\"\ngh run watch                   # 即時看 Actions 執行\ngh release create v1.2.0 --generate-notes"),
   ("h", u"Codespaces"),
   ("p", u"在倉庫按 <strong>Code → Codespaces → Create codespace</strong>，GitHub 會在雲端開一台已經 clone 好專案的開發機器，用瀏覽器或本機 VS Code 連上去。用 <code>.devcontainer/devcontainer.json</code> 設定好語言與工具，新成員打開就能開始寫，不用花一天裝環境。個人帳號每月有免費額度，用完記得關閉以免計費。"),
   ("h", u"GitHub Copilot"),
   ("p", u"Copilot 是 GitHub 的 AI 程式助手：在編輯器裡自動補全程式碼、用對話解釋與修改程式，也可以幫忙審查 PR、撰寫 PR 摘要，甚至接受 Issue 指派後自己開 PR。注意："),
   ("ul", [u"AI 產生的程式碼<strong>一定要自己讀過、測過</strong>，它可能有錯誤或安全問題。", u"把它當成「很快但需要監督的新同事」，責任仍然在你。", u"公司使用前先確認政策（程式碼是否能送到外部服務）。"]),
  ],
  u"gh 是 GitHub 官方命令列工具，可在終端機登入（gh auth login）、建立倉庫、開與合併 PR、抓 PR 測試、建 Issue、看 Actions、發布 Release。Codespaces 在雲端建立已 clone 專案的開發機，用 devcontainer.json 設定環境，有免費額度、用完要關閉。Copilot 是 AI 程式助手，可補全、對話、協助審查，但產生的程式碼必須自己檢查並確認公司政策。",
  [u"git 和 gh 的分工是什麼？", u"devcontainer.json 的用途？", u"使用 Copilot 產生的程式碼要注意什麼？"]),
])

MODULE_G = (u"模組 G｜Git 的內部", [

lesson(u"物件：blob、tree、commit",
  u"打開 .git 看看",
  [u"認識 Git 的三種主要物件", u"用 cat-file 查看物件", u"理解物件 ID 是內容的雜湊"],
  [("p", u"Git 的核心其實是一個簡單的<strong>以內容定址的資料庫</strong>：每樣東西都存成一個「物件」，物件的名字就是它內容的 SHA-1 雜湊。主要有三種物件："),
   ("t", [u"物件", u"存什麼", u"比喻"],
    [[u"<strong>blob</strong>", u"一個檔案的內容（不含檔名）", u"一張紙"], [u"<strong>tree</strong>", u"一個資料夾：檔名 → blob 或子 tree 的對照表", u"資料夾"],
     [u"<strong>commit</strong>", u"指向一個根 tree，加上父 commit、作者、訊息", u"貼在資料夾上的便條"]]),
   ] + gex("objects") + [
   ("p", u"逐行看：HEAD 是一個 commit；commit 裡記著它的根 <code>tree</code> 和 <code>parent</code>；tree 列出兩個 blob 和它們的檔名；用 <code>git hash-object</code> 自己算 README 內容的雜湊，得到的 <code>3ab1ad6…</code> 和 tree 裡記錄的一模一樣。"),
   ("fig", svg(title(u"一個 commit 的物件結構"),
               box(30, 70, 150, 60, u"commit edad20f", [u"加入 app.py"], BLUE), box(250, 70, 150, 60, u"tree 39f5e05", [u"根目錄"], GREEN),
               box(470, 30, 150, 50, u"blob 3ab1ad6", [u"README.md 的內容"], ORANGE), box(470, 120, 150, 50, u"blob 11b15b1", [u"app.py 的內容"], ORANGE),
               box(30, 170, 150, 50, u"commit 582091b", [u"父 commit"], BLUE),
               A(180, 100, 250, 100, MUTED), A(400, 90, 470, 60, MUTED), A(400, 110, 470, 140, MUTED), A(105, 130, 105, 170, MUTED), T(115, 155, u"parent", 9, MUTED, "start")), "0 0 640 235", u"commit → tree → blob。"),
   ("p", u"這解釋了很多事：內容相同的檔案（不管叫什麼名字、在哪個 commit）只會存<strong>一份</strong> blob；沒改的檔案在新 commit 的 tree 裡直接指向舊的 blob——所以 commit 是「快照」卻不浪費空間。"),
   ghw({"t": "hash", "q": u"自己算算看：輸入檔案內容，計算 Git 的 blob 物件 ID（演算法與 git hash-object 相同，已實際比對驗證）："}),
  ],
  u"Git 是以內容定址的資料庫，物件名稱是內容的 SHA-1。三種主要物件：blob 存檔案內容（不含檔名）、tree 存資料夾的檔名對照、commit 指向根 tree 並記錄父 commit、作者與訊息。git cat-file -t／-p 可查看物件，git hash-object 可自己算出相同雜湊。內容相同只存一份 blob，沒變的檔案直接指向舊 blob，所以快照不浪費空間。",
  [u"blob 裡有存檔名嗎？", u"commit 物件裡記錄了哪些東西？", u"為什麼內容相同的檔案只會存一份？"]),

lesson(u"參照：HEAD 與分支的真面目",
  u"refs 資料夾",
  [u"認識 .git 資料夾的結構", u"看見分支只是檔案", u"理解 HEAD 的兩種狀態"],
  [] + gex("refs") + [
   ("p", u"真相大白："),
   ("ul", [u"分支 <code>main</code> 就是 <code>.git/refs/heads/main</code> 這個檔案，內容只有一行 40 字元的 commit 雜湊。這就是為什麼開分支幾乎不花時間。",
           u"<code>.git/HEAD</code> 的內容是 <code>ref: refs/heads/main</code>——「我現在在 main 上」。切到 dev，它就變成 <code>ref: refs/heads/dev</code>。",
           u"遠端分支在 <code>.git/refs/remotes/origin/</code>，標籤在 <code>.git/refs/tags/</code>。（分支很多時，Git 會把它們打包進 <code>.git/packed-refs</code> 一個檔案裡。）"]),
   ("t", [u".git 中的項目", u"用途"],
    [[u"<code>objects/</code>", u"所有物件（blob、tree、commit、tag）"], [u"<code>refs/</code>", u"分支、標籤、遠端分支"], [u"<code>HEAD</code>", u"目前所在的分支"], [u"<code>index</code>", u"暫存區（一個二進位檔）"],
     [u"<code>config</code>", u"這個倉庫的設定（遠端網址等）"], [u"<code>logs/</code>", u"reflog 的紀錄"], [u"<code>hooks/</code>", u"在 commit、push 等時機自動執行的腳本範例"]]),
   ("h", u"分離的 HEAD（detached HEAD）"),
   ("p", u"如果你 <code>git switch --detach 雜湊</code>（或 <code>git checkout 雜湊</code>）切到某個 commit 而不是分支，HEAD 的內容會直接是一個雜湊，稱為 <strong>detached HEAD</strong>。這時可以看、可以實驗，但新 commit 不屬於任何分支，切走就會「迷路」（只能靠 reflog 找）。想保留的話：<code>git switch -c 新分支名稱</code>。"),
  ],
  u"分支 main 就是 .git/refs/heads/main 檔案，內容是一行 commit 雜湊；.git/HEAD 寫著 ref: refs/heads/main 表示目前所在分支。遠端分支在 refs/remotes、標籤在 refs/tags，也可能打包進 packed-refs。.git 中還有 objects、index（暫存區）、config、logs（reflog）、hooks。直接切到某個 commit 會成為 detached HEAD，新 commit 不屬於任何分支，要用 switch -c 保存。",
  [u"分支在 .git 裡是什麼樣子？", u"HEAD 檔案的內容通常是什麼？", u"detached HEAD 時做的 commit 要怎麼保存？"]),

lesson(u"打包與垃圾回收",
  u"Git 怎麼省空間",
  [u"理解鬆散物件與 packfile", u"認識 git gc", u"了解 Git 用 SHA-1 的安全議題"],
  [("p", u"每個新物件一開始都是 <code>.git/objects/</code> 下的一個壓縮檔（<strong>鬆散物件</strong>，loose object）。修改一個大檔案的一行，就會多一個幾乎一樣的 blob——看起來很浪費。所以 Git 會定期<strong>打包</strong>："),
   ] + gex("pack") + [
   ("p", u"<code>git gc</code>（garbage collection）把 30 個鬆散物件打包成一個 <strong>packfile</strong>（<code>.pack</code> 存資料，<code>.idx</code> 是索引）。在 pack 裡，相似的物件會存成「基底＋差異（delta）」，所以 10 個版本的大檔案只占一點點空間。同時，沒有任何分支或 reflog 指向的過期物件會被刪除。"),
   ("ul", [u"Git 會在適當時機<strong>自動</strong>執行 gc，平常不用手動。", u"<code>git clone</code> 與 <code>git push</code> 時，傳輸的也是 packfile，所以速度很快。",
           u"這套機制對文字檔效果極好；對已經壓縮過的二進位檔（影片、zip、jpg）幾乎無效——這是大型二進位檔該用 Git LFS 的原因（第 50 課）。"]),
   ("h", u"SHA-1 安全嗎？"),
   ("p", u"2017 年研究者首次做出兩個不同但 SHA-1 相同的 PDF。Git 之後改用能偵測這類攻擊的強化版 SHA-1，並已支援以 <strong>SHA-256</strong> 建立倉庫（<code>git init --object-format=sha256</code>）。不過 SHA-256 倉庫與 GitHub 等平台的相容性仍在推進中，目前絕大多數倉庫仍使用 SHA-1。"),
  ],
  u"新物件先是 .git/objects 下的鬆散物件；git gc 把它們打包成 packfile（.pack 與 .idx），相似物件以基底加差異儲存，並刪除無人指向的過期物件。gc 會自動執行，clone 與 push 也傳輸 packfile。差異壓縮對文字檔有效、對已壓縮的二進位檔幾乎無效，所以大型二進位檔應用 Git LFS。SHA-1 在 2017 年被證實可碰撞，Git 採用偵測碰撞的強化版並支援 SHA-256 倉庫。",
  [u"鬆散物件和 packfile 有什麼不同？", u"為什麼 Git 對影片檔很沒效率？", u"Git 如何因應 SHA-1 的碰撞問題？"]),
])

_RESCUE = ghw({"t": "tree", "q": u"災難救援決策樹：", "nodes": {
  "start": {"q": u"發生了什麼事？", "o": [[u"把密碼、金鑰 commit 進去了", "sec"], [u"在錯的分支上 commit 了", "wb"], [u"reset 之後 commit 不見了", "lost"], [u"push 被拒絕（rejected）", "rej"], [u"不知道哪個 commit 讓程式壞掉", "bis"], [u"合併或 rebase 到一半，一團亂", "mid"]]},
  "sec": {"q": u"已經 push 了嗎？", "o": [[u"還沒", "sec1"], [u"已經 push 了", "sec2"]]},
  "sec1": {"a": u"還來得及：<code>git rm --cached .env</code>（或 reset 掉那個 commit）、把它加進 .gitignore，再 <code>git commit --amend</code> 讓它從最新 commit 消失。若它在更早的 commit 裡，用互動式 rebase 把那個 commit 改掉。確認 <code>git log --all -- .env</code> 沒有結果再 push。"},
  "sec2": {"a": u"<strong>第一步：立刻到服務商撤銷那把金鑰並換新的</strong>——這比清歷史更重要，機器人可能已經抓走了。接著停止追蹤檔案（<code>git rm --cached</code>）並加入 .gitignore；若一定要從歷史中抹除，用 <code>git filter-repo</code> 重寫歷史並強制推送，所有協作者都要重新 clone。"},
  "wb": {"a": u"在當前分支建立新分支保存 commit：<code>git branch 正確的分支</code>，再把目前分支退回：<code>git reset --hard HEAD~1</code>，然後 <code>git switch 正確的分支</code>。若正確的分支已經存在，改用 <code>git switch 正確的分支</code> 加 <code>git cherry-pick 雜湊</code>。"},
  "lost": {"a": u"<code>git reflog</code> 找到那個 commit 的雜湊或 <code>HEAD@{n}</code>，再 <code>git reset --hard 它</code> 或 <code>git branch rescue 它</code>。"},
  "rej": {"a": u"遠端有你沒有的新 commit。<code>git pull</code>（或 <code>git pull --rebase</code>）把它們拿下來、解決可能的衝突，再 <code>git push</code>。<strong>不要</strong>直接 <code>--force</code>，那會把別人的 commit 蓋掉。"},
  "bis": {"a": u"用 <code>git bisect</code> 二分搜尋：標記一個壞的和一個好的 commit，Git 會一半一半地幫你找到第一個壞掉的 commit；有自動測試時可以用 <code>git bisect run 指令</code> 全自動完成。"},
  "mid": {"a": u"放棄回到開始前：<code>git merge --abort</code>、<code>git rebase --abort</code>、<code>git cherry-pick --abort</code>。<code>git status</code> 會告訴你現在處於哪一種狀態。"}}})

_CARDS = ghw({"t": "cards", "q": u"Git 指令速查（可搜尋、可分類）：",
  "groups": [["s", u"開始", "#3a6ea5"], ["d", u"日常", "#2e8b57"], ["b", u"分支", "#8e5bb5"], ["r", u"遠端", "#d08a2a"], ["u", u"復原與救援", "#d0564f"], ["i", u"檢視", "#2a9d9d"]],
  "cards": [["git config --global user.name \"名字\"", "s", u"設定作者名稱（user.email 同理）"], ["git init", "s", u"把目前資料夾變成 Git 倉庫"], ["git clone 網址", "s", u"下載整個倉庫與歷史"],
            ["git status", "d", u"目前狀態；加 -s 簡短顯示"], ["git add 檔案", "d", u"放進暫存區；git add . 加入全部"], ["git commit -m \"訊息\"", "d", u"建立 commit；-am 一次加入已追蹤檔"],
            ["git stash push -m \"說明\"", "d", u"暫時收起未 commit 的修改；git stash pop 取回"], ["git tag -a v1.0.0 -m \"說明\"", "d", u"建立附註標籤"],
            ["git switch -c 名稱", "b", u"建立並切換分支"], ["git switch 名稱", "b", u"切換分支"], ["git branch -d 名稱", "b", u"刪除已合併的分支（-D 強制）"], ["git merge 名稱", "b", u"把分支合併進目前分支"],
            ["git rebase main", "b", u"把目前分支的 commit 接到 main 最新處"], ["git cherry-pick 雜湊", "b", u"複製單一 commit 到目前分支"],
            ["git remote -v", "r", u"列出遠端倉庫"], ["git remote add upstream 網址", "r", u"新增遠端"], ["git fetch", "r", u"取回遠端更新，不合併"], ["git pull", "r", u"取回並合併（--rebase 改用 rebase）"],
            ["git push -u origin 分支", "r", u"第一次推送分支並建立追蹤"], ["git push --force-with-lease", "r", u"安全的強制推送（只在自己的分支用）"],
            ["git restore 檔案", "u", u"丟棄工作目錄的修改"], ["git restore --staged 檔案", "u", u"移出暫存區"], ["git commit --amend", "u", u"修改上一個 commit（未 push 時）"],
            ["git reset --soft HEAD~1", "u", u"取消 commit，修改留在暫存區"], ["git reset --hard HEAD~1", "u", u"取消 commit 並丟掉修改"], ["git revert 雜湊", "u", u"新增反向 commit（已 push 時用）"],
            ["git reflog", "u", u"HEAD 走過的每一步，救回消失的 commit"], ["git merge --abort", "u", u"放棄進行中的合併"], ["git rm --cached 檔案", "u", u"停止追蹤但保留檔案"],
            ["git log --oneline --graph --all", "i", u"圖形化歷史"], ["git diff", "i", u"工作目錄 vs 暫存區；--staged 暫存區 vs commit"], ["git show 雜湊", "i", u"一個 commit 的完整內容"],
            ["git blame 檔案", "i", u"每一行最後是誰改的"], ["git bisect start 壞 好", "i", u"二分搜尋找出造成問題的 commit"], ["git cat-file -p 物件", "i", u"查看 Git 物件內容"]]})

MODULE_H = (u"模組 H｜救援與實戰", [

lesson(u"常見災難與解法",
  u"不要慌，Git 幾乎什麼都救得回來",
  [u"處理上傳了機密的情況", u"修正在錯的分支 commit", u"用 bisect 找出出錯的 commit"],
  [("h", u"災難一：把 .env 上傳了"),
   ] + gex("secret") + [
   ("p", u"<code>git rm --cached</code> 讓 Git 停止追蹤（檔案還在你的硬碟上），加入 .gitignore 後狀態變成 <code>!!</code>（已忽略）。但注意最後一行：<strong>舊的 commit 裡仍然有 .env</strong>。如果已經 push 到公開倉庫，第一件事是<strong>撤銷那把金鑰</strong>。"),
   ("h", u"災難二：在 main 上 commit 了本該在功能分支的東西"),
   ] + gex("wrongbranch") + [
   ("p", u"先用 <code>git branch</code> 在目前位置建立分支「保存」那個 commit，再把 main 退回去，最後切到新分支——commit 就搬家了。"),
   ("h", u"災難三：程式壞了，不知道是哪個 commit"),
   ] + gex("bisect") + [
   ("p", u"<code>git bisect</code> 用二分搜尋：告訴它一個壞的（HEAD）和一個好的（HEAD~6）commit，它會切到中間讓你測試。用 <code>git bisect run 指令</code>，指令成功（結束碼 0）表示好、失敗表示壞，Git 自動找到「第 4 版」是第一個壞掉的 commit。1000 個 commit 也只要測大約 10 次。"),
   _RESCUE,
  ],
  u"上傳 .env：git rm --cached 停止追蹤並加入 .gitignore，但舊 commit 仍有它，已 push 就要先撤銷金鑰（必要時用 git filter-repo 重寫歷史）。在錯的分支 commit：git branch 新分支保存、reset --hard HEAD~1 退回、switch 過去。找出出錯的 commit：git bisect start 壞 好，加 bisect run 自動以結束碼判斷，二分搜尋只需約 log2(N) 次。",
  [u"git rm --cached 會刪掉硬碟上的檔案嗎？", u"金鑰已經 push 到公開倉庫，第一步要做什麼？", u"git bisect run 怎麼判斷好壞？"]),

lesson(u"大型檔案：Git LFS",
  u"影片、設計檔、資料集",
  [u"知道 GitHub 的檔案大小限制", u"使用 Git LFS 管理大型檔案", u"了解 LFS 的取捨"],
  [("p", u"Git 為文字檔設計。把大型二進位檔（影片、PSD、遊戲素材、資料集、模型權重）直接放進 Git，每改一次就多存一整份，倉庫很快膨脹到幾 GB，每個人 clone 都要下載全部歷史版本。"),
   ("p", u"GitHub 的限制：單一檔案超過 <strong>50 MB</strong> 會警告，超過 <strong>100 MB</strong> 會直接拒絕 push。建議倉庫整體保持在 1 GB 以下（詳細數字以官方文件為準）。"),
   ("p", u"<strong>Git LFS</strong>（Large File Storage）的做法是：Git 裡只存一個幾行的「指標檔」，真正的大檔案放在另外的 LFS 伺服器，checkout 時才下載你需要的版本。"),
   cmd(u"git lfs install                  # 每台電腦執行一次\ngit lfs track \"*.psd\"            # 指定要用 LFS 管理的檔案類型\ngit add .gitattributes            # 追蹤規則存在這個檔案，要 commit\ngit add design.psd\ngit commit -m \"加入設計稿\"\ngit push\ngit lfs ls-files                  # 列出由 LFS 管理的檔案"),
   ("p", u"Git 裡存的指標檔長這樣："),
   ("code", u"version https://git-lfs.github.com/spec/v1\noid sha256:4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393\nsize 12345678"),
   ("ul", [u"<code>git lfs track</code> 要在加入檔案<strong>之前</strong>設定；已經 commit 進一般 Git 的大檔案，要用 <code>git lfs migrate</code> 轉換（會改寫歷史）。", u"GitHub 的 LFS 有免費的儲存與流量額度，超過要購買。",
           u"不是所有大檔都該進版本控制：可以重新產生的（編譯結果）或很少變動的大型資料集，放在雲端儲存並在 README 說明下載方式也很好。"]),
  ],
  u"大型二進位檔直接放 Git 會讓每個版本都存一整份、倉庫膨脹。GitHub 對超過 50 MB 的檔案警告、超過 100 MB 拒絕 push。Git LFS 只在 Git 中存放指標檔，實際檔案放在 LFS 伺服器：git lfs install、git lfs track \"*.psd\"、commit .gitattributes。track 要在加入檔案前設定，已存在的要用 lfs migrate；LFS 有額度限制，也可考慮雲端儲存。",
  [u"GitHub 會拒絕多大的單一檔案？", u"Git LFS 在 Git 裡存的是什麼？", u"為什麼要 commit .gitattributes？"]),

lesson(u"開源禮儀與授權",
  u"授權條款、貢獻指南、行為準則",
  [u"比較常見的開源授權", u"知道沒有授權條款的意義", u"成為受歡迎的貢獻者"],
  [("p", u"公開倉庫不等於開源。<strong>沒有 LICENSE 檔的程式碼，預設是「保留所有權利」</strong>——別人可以看，但法律上不能使用、修改或散布。想讓別人使用，就要選一個授權條款："),
   ("t", [u"授權", u"大意", u"常見於"],
    [[u"MIT", u"幾乎什麼都能做，只要保留版權聲明；不提供任何擔保", u"React、Rails 等大量專案"], [u"Apache 2.0", u"類似 MIT，另外明確授予專利權、要求標示修改", u"Kubernetes、Android 許多元件"],
     [u"GPL-3.0", u"可自由使用修改，但<strong>散布衍生作品時必須以 GPL 開放原始碼</strong>（copyleft）", u"許多 GNU 軟體"], [u"BSD", u"與 MIT 類似的寬鬆授權", u"FreeBSD 等"],
     [u"CC BY 4.0", u"給文章、圖片等非程式內容；需標示作者", u"文件、教材"]]),
   ("p", u"不知道怎麼選，可以參考 choosealicense.com。<em>本課提供的是一般性介紹，不構成法律意見；商業用途請諮詢專業人士。</em>"),
   ("h", u"當個受歡迎的貢獻者"),
   ("ol", [u"<strong>先讀</strong> README 與 CONTRIBUTING.md：很多專案規定了程式風格、測試方式、commit 格式。", u"<strong>先搜尋</strong> Issue：你的問題可能已經有人回報過。",
           u"大改動<strong>先開 Issue 討論</strong>，維護者同意方向再動手，免得白做。", u"從 <code>good first issue</code> 標籤開始。", u"PR 保持小而專注，附上測試；被要求修改時保持耐心。",
           u"維護者多半是志工，回覆慢是正常的。"]),
   ("p", u"<strong>CODE_OF_CONDUCT.md</strong>（行為準則）規範社群中的互動方式——尊重他人、不騷擾、不歧視，以及違反時如何處理。最常用的範本是 Contributor Covenant。"),
  ],
  u"沒有 LICENSE 的公開程式碼預設保留所有權利，別人不能合法使用。常見授權：MIT（寬鬆，保留版權聲明）、Apache 2.0（另授予專利權）、GPL-3.0（散布衍生作品須以 GPL 開源）、BSD、CC BY（非程式內容）；可參考 choosealicense.com（本課非法律意見）。貢獻前先讀 README 與 CONTRIBUTING、搜尋 Issue、大改動先討論、從 good first issue 開始、PR 小而專注並有耐心。CODE_OF_CONDUCT 規範社群互動。",
  [u"公開倉庫沒有 LICENSE 檔，別人可以拿去用嗎？", u"GPL 和 MIT 最大的差別是什麼？", u"想做大改動前應該先做什麼？"]),

lesson(u"實戰：從零到第一個 PR",
  u"把所有東西串起來",
  [u"獨立完成一次完整的協作流程", u"把指令與 GitHub 操作連起來", u"建立自己的工作習慣"],
  [("p", u"把整門課串成一次完整的練習。建議找一個朋友，或用兩個帳號自己扮演兩個角色。"),
   ("h", u"第一階段：建立專案（維護者）"),
   cmd(u"gh repo create todo-app --public --clone --add-readme --license mit\ncd todo-app\nprintf 'tasks = []\\n' > todo.py\nprintf '__pycache__/\\n.env\\n' > .gitignore\ngit add . && git commit -m \"feat: 建立待辦清單骨架\"\ngit push"),
   ("p", u"在 GitHub 設定：Settings → Rules → 新增規則集保護 main（要求 PR、至少 1 人核准）；新增一個 CI workflow（第 39 課）。開一個 Issue：「新增『加入待辦』功能」，加上 <code>good first issue</code> 標籤。"),
   ("h", u"第二階段：貢獻（貢獻者）"),
   cmd(u"gh repo fork ming/todo-app --clone\ncd todo-app\ngit switch -c feat/add-task\n# ……編輯 todo.py，加入 add_task 函式與測試……\ngit add todo.py test_todo.py\ngit commit -m \"feat: 新增 add_task 函式\" -m \"Fixes #1\"\ngit push -u origin feat/add-task\ngh pr create --fill"),
   ("h", u"第三階段：審查與合併"),
   ("ol", [u"維護者在 Files changed 留言，用 Suggest changes 提出修改。", u"貢獻者修改後再 commit、push，PR 自動更新。", u"CI 綠燈、維護者 Approve。",
           u"維護者選擇 <strong>Squash and merge</strong>，Issue #1 自動關閉。", u"貢獻者同步：<code>git switch main</code>、<code>git pull upstream main</code>（或在 GitHub 按 Sync fork）、<code>git branch -D feat/add-task</code>。"]),
   ("h", u"第四階段：發布"),
   cmd(u"git switch main && git pull\ngit tag -a v0.1.0 -m \"第一個版本\"\ngit push origin v0.1.0\ngh release create v0.1.0 --generate-notes"),
   ("p", u"走完一次，你就用過了本課程大部分的技能：設定、commit、分支、push、fork、PR、審查、CI、規則、合併、同步、標籤與發布。"),
  ],
  u"完整練習分四階段：維護者用 gh repo create 建立專案、加 .gitignore 並 push，設定 main 保護規則、CI 與 good first issue；貢獻者 fork、開分支、commit（Fixes #1）、push、gh pr create；維護者留言、貢獻者修改再 push、CI 綠燈並核准後 Squash and merge，Issue 自動關閉，貢獻者同步並刪分支；最後打 tag、推送、gh release create 發布。",
  [u"在這個練習中，Issue 是怎麼自動關閉的？", u"貢獻者合併後要做哪些清理？", u"發布 v0.1.0 需要哪幾個指令？"]),

lesson(u"總結與學習地圖",
  u"指令速查與下一步",
  [u"回顧整門課的重點", u"使用指令速查卡", u"規劃下一步的學習"],
  [_CARDS,
   ("h", u"十條最重要的心法"),
   ("ol", [u"Git 是工具，GitHub 是平台。", u"三個區域：工作目錄 →（add）→ 暫存區 →（commit）→ 儲存庫。", u"commit 在 push 之前只在你的電腦上。", u"小而頻繁的 commit，訊息說清楚「為什麼」。",
           u"永遠不要直接在 main 上改：開分支、發 PR。", u"已經 push 的歷史不要改寫：用 revert，不用 reset ＋ force。", u"衝突不可怕：讀標記、刪標記、add、commit。",
           u"機密永遠不進版本控制；外洩就先撤銷。", u"幾乎什麼都救得回來：reflog 是你的保險。", u"讓機器做重複的事：CI、Dependabot、規則。"]),
   ("h", u"下一步"),
   ("ul", [u"在自己的每個作業、筆記、小專案都用 Git——熟練來自每天使用。", u"讀《Pro Git》（git-scm.com/book，免費，有中文版），特別是「Git 內部原理」一章。",
           u"在 GitHub 上找一個你常用的開源專案，從 good first issue 開始貢獻。", u"深入 GitHub Actions：自動部署、排程任務、可重複使用的 workflow。", u"研究 <code>git rebase -i</code>、<code>git worktree</code>、<code>git submodule</code> 等進階工具。"]),
   _RESCUE,
  ],
  u"十條心法：Git 是工具 GitHub 是平台；三個區域；commit 在 push 前只在本機；小而頻繁、說明為什麼；不直接改 main；不改寫已 push 的歷史；衝突照步驟解；機密不進版本控制、外洩先撤銷；reflog 是保險；讓 CI、Dependabot、規則自動化。下一步：每天使用、讀 Pro Git、貢獻開源、深入 Actions、學 rebase -i、worktree、submodule。",
  [u"哪三個指令讓檔案從工作目錄進到 GitHub？", u"已經 push 的錯誤 commit 該怎麼處理？", u"免費的 Git 官方書籍叫什麼？"]),
])

MODULES = [MODULE_E, MODULE_F, MODULE_G, MODULE_H]
