# -*- coding: utf-8 -*-
"""一次 LLM 推論到底發生什麼：模組 A～D（第 1～20 課）。"""
from lf_common import *

lesson = lflesson

_JOURNEY = svg(
    title(u"一次請求的旅程"),
    flow([(u"文字", u"使用者輸入"), (u"Tokenizer", u"切成 token ID"), (u"Prefill", u"一次讀完整段輸入"), (u"Decode", u"一次生一個 token"), (u"Detokenize", u"轉回文字串流")], 60, 70),
    T(320, 162, u"Prefill 結束時吐出第一個 token（TTFT）；之後 decode 每一步再吐一個（TPOT）", 10, ACC),
)

_TWO = svg(
    title(u"兩個階段：讀題與寫答案"),
    box(20, 46, 290, 140, u"Prefill（預填）", [u"輸入：整段提示（數百到數十萬 token）", u"一次平行處理所有 token", u"產出：KV Cache ＋ 第一個 token", u"瓶頸：算力（compute-bound）"], GREEN),
    box(330, 46, 290, 140, u"Decode（解碼）", [u"輸入：上一步剛生成的 1 個 token", u"每一步只處理 1 個 token", u"讀取整個模型＋整個 KV Cache", u"瓶頸：記憶體頻寬（memory-bound）"], BLUE),
    T(320, 212, u"同一個模型、同一批權重，兩個階段的效能特性卻截然不同", 10, ACC),
)

_LAYER = svg(
    title(u"一個 Transformer 層（decoder-only）"),
    box(250, 196, 140, 30, u"輸入向量 x", [], GRAY),
    box(250, 146, 140, 32, u"RMSNorm → 注意力", [], BLUE), box(250, 92, 140, 32, u"RMSNorm → MLP", [], ORANGE), box(250, 40, 140, 30, u"輸出到下一層", [], GRAY),
    A(320, 196, 320, 180, MUTED, 1.3), A(320, 146, 320, 126, MUTED, 1.3), A(320, 92, 320, 72, MUTED, 1.3),
    P("M250 210 L210 210 L210 130 L248 130", PURPLE, sw=1.2, dash="4 3"), T(204, 172, u"殘差", 9.5, PURPLE, "end"),
    P("M390 140 L430 140 L430 78 L392 78", PURPLE, sw=1.2, dash="4 3"), T(436, 110, u"殘差", 9.5, PURPLE, "start"),
    T(470, 166, u"注意力：token 之間交換資訊", 9.5, BLUE, "start"), T(470, 112, u"MLP：每個 token 各自加工", 9.5, ORANGE, "start"),
    T(110, 60, u"重複數十層", 11, ACC), T(110, 78, u"（8B 模型 32 層，70B 模型 80 層）", 9, MUTED),
)

_QKV = svg(
    title(u"注意力：用 Q 去比對所有的 K，再加權平均 V"),
    box(20, 50, 130, 60, u"Query（Q）", [u"「我在找什麼」"], RED), box(20, 124, 130, 60, u"Key（K）", [u"「我有什麼標籤」"], BLUE),
    box(20, 198, 130, 46, u"Value（V）", [u"「我的內容」"], GREEN),
    box(200, 80, 160, 70, u"分數 ＝ Q·Kᵀ / √d", [u"softmax 成權重"], PURPLE), box(410, 130, 200, 70, u"輸出 ＝ 權重 × V", [u"把相關 token 的內容加總"], ORANGE),
    A(150, 80, 198, 105, MUTED, 1.3), A(150, 154, 198, 125, MUTED, 1.3), A(360, 115, 408, 150, MUTED, 1.3), A(150, 221, 408, 180, MUTED, 1.3),
)

_CACHE = svg(
    title(u"沒有 KV Cache vs 有 KV Cache"),
    box(20, 46, 290, 140, u"沒有快取", [u"生第 n 個 token 時", u"要重算前面 n−1 個 token 的 K、V", u"總計算量 ∝ n²", u"生 1000 個字 ≈ 重算 50 萬次"], RED),
    box(330, 46, 290, 140, u"有 KV Cache", [u"前面 token 的 K、V 存在記憶體裡", u"每步只算新 token 的 Q、K、V", u"每步計算量 ∝ 1（注意力讀取 ∝ n）", u"代價：大量記憶體"], GREEN),
    T(320, 212, u"用記憶體換計算——這個取捨決定了整個推論系統的設計", 10, ACC),
)

_GQA = svg(
    title(u"MHA → MQA → GQA：讓多個 Query 頭共用 K/V"),
    [C(60 + i * 22, 70, 8, RED, RED) for i in range(8)], [C(60 + i * 22, 130, 8, BLUE, BLUE) for i in range(8)], T(137, 166, u"MHA：8 個 Q 頭、8 組 KV", 10, MUTED),
    [C(260 + i * 22, 70, 8, RED, RED) for i in range(8)], C(337, 130, 8, BLUE, BLUE), T(337, 166, u"MQA：8 個 Q 頭共用 1 組 KV", 10, MUTED),
    [C(460 + i * 22, 70, 8, RED, RED) for i in range(8)], [C(471 + i * 44, 130, 8, BLUE, BLUE) for i in range(4)], T(537, 166, u"GQA：每 2 個 Q 頭共用 1 組", 10, MUTED),
    [P("M%d 78 L%d 122" % (60 + i * 22, 60 + i * 22), MUTED, sw=0.8) for i in range(8)], [P("M%d 78 L337 122" % (260 + i * 22), MUTED, sw=0.8) for i in range(8)],
    [P("M%d 78 L%d 122" % (460 + i * 22, 471 + (i // 2) * 44), MUTED, sw=0.8) for i in range(8)],
    T(320, 200, u"KV Cache 大小依序是 100%、12.5%、25%；品質損失 MQA 較明顯、GQA 很小", 10, ACC),
)

_PREFILL = svg(
    title(u"Prefill：所有 token 一起穿過每一層"),
    [R(40 + i * 28, 60, 24, 120, GREEN, "rgba(74,154,94,0.18)", 3, 1) for i in range(12)], T(200, 50, u"N 個輸入 token 排成一個大矩陣", 10, GREEN),
    A(390, 120, 440, 120, MUTED, 1.5),
    box(450, 70, 170, 100, u"矩陣 × 矩陣（GEMM）", [u"[N × d] × [d × d]", u"每讀一次權重", u"就用 N 次"], PURPLE),
    T(320, 210, u"權重讀一次、算 N 次 → 算術強度高 → GPU 的算力被充分使用", 10, ACC),
)

_DECODE = svg(
    title(u"Decode：每一步只有一個 token"),
    R(60, 90, 24, 60, BLUE, "rgba(58,110,165,0.25)", 3, 1), T(72, 80, u"1 個 token", 10, BLUE),
    A(100, 120, 150, 120, MUTED, 1.5),
    box(160, 70, 170, 100, u"矩陣 × 向量（GEMV）", [u"[1 × d] × [d × d]", u"每讀一次權重", u"只用 1 次"], RED),
    A(340, 120, 390, 120, MUTED, 1.5),
    box(400, 70, 220, 100, u"大部分時間在等記憶體", [u"8B 模型每步讀 16 GB", u"H100 頻寬 3.35 TB/s", u"→ 至少約 4.8 ms"], ORANGE),
    T(320, 204, u"算力閒置、頻寬塞滿 → batching 讓多個請求共用同一次權重讀取（第 27 課）", 10, ACC),
)


MODULES = [
(u"模組 A｜全景", [

lesson(u"從按下 Enter 到看到第一個字",
  u"一次請求的完整旅程",
  [u"建立 LLM 推論的整體圖像",
   u"認識請求經過的主要步驟",
   u"知道這門課的地圖"],
  [("p", u"你在聊天介面輸入一句話、按下 Enter，大約半秒後第一個字出現，接著文字像打字一樣一個一個冒出來。這背後發生了什麼？"),
   fig(_JOURNEY, 180, u"一次請求從文字到文字的旅程。"),
   ("ol", [u"<strong>排隊與路由</strong>：請求送到資料中心，排進某一台推論伺服器的佇列",
           u"<strong>Tokenize</strong>：文字被切成一串整數（token ID）",
           u"<strong>Prefill</strong>：GPU 一次把整段輸入「讀完」，建立 KV Cache，並算出第一個輸出 token",
           u"<strong>Decode</strong>：一次生成一個 token，每生一個就送回給你，直到遇到結束符號或長度上限",
           u"<strong>Detokenize 與串流</strong>：token 轉回文字，透過串流連線一點一點送到你的螢幕"]),
   lfw({"t": "timeline", "q": u"拉動輸入與輸出長度，看看時間花在哪裡："}),
   ("p", u"這門課的核心是第 3、4 步：<strong>prefill 與 decode</strong>。它們用的是同一個模型、同一批權重，效能特性卻天差地遠，幾乎所有推論最佳化技術都是圍繞這個差異設計的。想先了解模型本身，可以參考 " + u'<a href="../llm-models/index.html">〈大型語言模型〉</a>' + u"。"),
   ("t", [u"模組", u"內容"],
         [[u"A 全景", u"旅程、訓練 vs 推論、兩個階段、指標"], [u"B 輸入到向量", u"tokenizer、chat template、embedding、RoPE、Transformer 層"],
          [u"C 注意力與 KV Cache", u"QKV、因果遮罩、KV Cache 與它的大小、GQA／MLA、長上下文"], [u"D Prefill", u"FLOPs、算力受限、FlashAttention、chunked prefill"],
          [u"E Decode", u"自回歸、頻寬受限、roofline、速度上限、抽樣、結構化輸出"], [u"F 加速", u"batching、PagedAttention、prefix cache、量化、推測解碼、分離部署、MoE"],
          [u"G 硬體", u"GPU 結構、記憶體階層、平行化、互連、其他加速器"], [u"H 系統", u"排程、成本、benchmark、本地推論、總結"]]),
  ],
  u"一次請求經過排隊、tokenize、prefill、decode、detokenize 與串流；prefill 與 decode 用同一模型卻效能特性迥異，是推論最佳化的核心。",
  [u"一次請求經過哪幾個主要步驟？",
   u"第一個字是在哪個階段結束時產生的？",
   u"為什麼說 prefill 與 decode 是這門課的核心？"]),

lesson(u"訓練 vs 推論",
  u"為什麼推論是另一個世界",
  [u"比較訓練與推論的差異",
   u"理解推論成本的重要性",
   u"認識推論的獨特挑戰"],
  [("t", [u"", u"訓練", u"推論"],
         [[u"做什麼", u"調整權重", u"權重固定，只做前向計算"], [u"計算", u"前向＋反向傳播（約 3 倍前向）", u"只有前向"],
          [u"輸入形狀", u"大批次、固定長度、整段一起算", u"請求長短不一、隨時到達、一個一個 token 生成"],
          [u"在意什麼", u"總吞吐量、能不能收斂", u"延遲（使用者在等）、吞吐量、每個 token 的成本"],
          [u"發生幾次", u"一次（幾週到幾個月）", u"每天數億到數十億次"]]),
   ("p", u"訓練一個大模型可能要花數千萬到上億美元，但它只做一次；推論則是每次有人使用都要付出的成本。當一個模型被大量使用，<strong>推論的總成本很快就會超過訓練</strong>。這就是為什麼推論效率是 AI 公司最關心的工程問題之一。"),
   ("p", u"推論還有訓練沒有的挑戰：<strong>自回歸生成</strong>讓計算必須一步一步進行，無法像訓練那樣把整段序列一次算完；而使用者在螢幕前等待，延遲的每一百毫秒都會影響體驗。"),
  ],
  u"訓練調權重、做前向加反向、追求吞吐量且只做一次；推論權重固定、只做前向、在意延遲與成本、每天執行數十億次，總成本很快超過訓練。",
  [u"訓練和推論的計算有什麼不同？",
   u"為什麼推論成本可能超過訓練？",
   u"推論有什麼訓練沒有的挑戰？"]),

lesson(u"兩個階段：Prefill 與 Decode",
  u"讀題與寫答案",
  [u"認識 prefill 與 decode",
   u"理解兩者的根本差異",
   u"預覽後面的內容"],
  [("p", u"把 LLM 想成一個考生：<strong>prefill</strong> 是把整張考卷讀一遍，<strong>decode</strong> 是一個字一個字地寫答案。"),
   fig(_TWO, 226, u"Prefill 與 decode 的對比。"),
   ("p", u"為什麼讀題快、寫字慢？因為讀題時所有字都已經在眼前，可以「一起看」；寫答案時，下一個字取決於上一個字，只能一個一個來。"),
   ("p", u"在 GPU 上，這個差異變成了兩種完全不同的瓶頸："),
   ("ul", [u"<strong>Prefill</strong>：數千個 token 一起做矩陣乘法，GPU 的運算單元忙得不可開交——瓶頸是<strong>算力</strong>",
           u"<strong>Decode</strong>：每一步只處理一個 token，卻要把整個模型（數十 GB）從記憶體讀一遍——瓶頸是<strong>記憶體頻寬</strong>"]),
   ("p", u"這個差異貫穿整門課：模組 D 專講 prefill，模組 E 專講 decode，模組 F 的各種加速技術，幾乎都是在想辦法讓 decode 不那麼浪費。"),
  ],
  u"Prefill 像一次讀完整張考卷，平行處理、受算力限制；decode 像一字一字寫答案，每步只有一個 token 卻要讀整個模型，受頻寬限制。",
  [u"用考試比喻 prefill 與 decode。",
   u"prefill 的瓶頸是什麼？decode 呢？",
   u"為什麼 decode 不能平行？"]),

lesson(u"使用者感受到的指標",
  u"TTFT、TPOT、吞吐量與成本",
  [u"認識推論的主要效能指標",
   u"理解指標與兩個階段的對應",
   u"了解指標之間的取捨"],
  [("t", [u"指標", u"意義", u"主要由哪個階段決定"],
         [[u"TTFT（Time To First Token）", u"從送出請求到看到第一個字的時間", u"排隊時間 ＋ prefill"],
          [u"TPOT／ITL（Time Per Output Token／Inter-Token Latency）", u"之後每個字之間的間隔", u"decode 的每一步"],
          [u"E2E 延遲", u"整個回答完成的時間", u"TTFT ＋ TPOT × 輸出長度"],
          [u"吞吐量（throughput）", u"整台機器每秒產出多少 token", u"batching 與排程"],
          [u"每百萬 token 成本", u"硬體成本 ÷ 吞吐量", u"吞吐量與硬體價格"]]),
   ("p", u"人眼閱讀速度大約每秒 5～10 個中文字。只要 TPOT 小於 50～100 毫秒，使用者就會覺得「字一直在冒出來」，不會覺得卡。但 TTFT 超過一兩秒，使用者就會開始懷疑是不是當機了。"),
   ("p", u"這些指標之間常常互相衝突：把更多請求塞進同一個批次，<strong>吞吐量</strong>上升、每個 token 成本下降，但每個人的 <strong>TPOT</strong> 會變長；優先處理新請求的 prefill 可以降低 <strong>TTFT</strong>，卻會打斷正在 decode 的請求，讓它們的 TPOT 不穩定。推論系統的設計，就是在這些指標之間找平衡（第 40 課）。"),
  ],
  u"推論指標包括 TTFT（排隊加 prefill）、TPOT（decode 每步）、端到端延遲、吞吐量與每 token 成本；它們互相衝突，系統設計就是在其間取捨。",
  [u"TTFT 主要由什麼決定？",
   u"TPOT 多少以下使用者會覺得流暢？",
   u"為什麼提高吞吐量可能讓 TPOT 變長？"]),
]),

(u"模組 B｜從文字到向量", [

lesson(u"Tokenizer",
  u"文字怎麼變成數字",
  [u"理解 token 與 tokenizer",
   u"認識 BPE 演算法",
   u"了解 token 數量對成本與速度的影響"],
  [("p", u"模型不認識文字，只認識數字。<strong>Tokenizer</strong> 把文字切成一個個「token」，每個 token 對應詞彙表中的一個整數 ID。"),
   ("p", u"現代 LLM 大多使用 <strong>BPE</strong>（Byte Pair Encoding）的變形：從單一位元組開始，反覆把訓練資料中<strong>最常一起出現的兩個片段合併</strong>成一個新 token，直到詞彙表達到預定大小（通常三萬到二十多萬個）。所以常見的詞會變成一個 token，罕見的詞會被拆成幾個片段，完全沒見過的字則退回到 UTF-8 位元組。"),
   lfw({"t": "tok", "q": u"輸入文字，看看簡化版 tokenizer 如何切分（紅色是被拆成位元組的字）："}),
   ("ul", [u"<strong>token 數量就是成本</strong>：API 依 token 計費，prefill 的計算量與輸入 token 數成正比",
           u"<strong>語言不平等</strong>：詞彙表以英文為主訓練時，中文、泰文、阿拉伯文等常需要更多 token 表達同樣的意思。近年的詞彙表加入了更多非英語 token，差距已經縮小",
           u"<strong>奇怪的錯誤</strong>：模型「看」的是 token 而不是字母，所以數「strawberry 裡有幾個 r」這類問題曾經難倒很多模型"]),
  ],
  u"Tokenizer 用 BPE 把文字切成詞彙表中的 token ID，常見詞一個 token、罕見字退回位元組；token 數決定成本，非英語可能需要更多 token。",
  [u"BPE 是怎麼建立詞彙表的？",
   u"為什麼中文有時比英文花更多 token？",
   u"為什麼模型不擅長數字母？"]),

lesson(u"Chat template 與系統提示",
  u"模型實際看到的輸入",
  [u"了解對話如何被組成一段文字",
   u"認識特殊 token",
   u"理解系統提示與工具定義的成本"],
  [("p", u"你在介面上看到的是一則一則對話，但模型實際看到的是<strong>一長串 token</strong>。對話會依照模型的 <strong>chat template</strong> 被組裝起來，用特殊 token 標示角色與邊界，大致像這樣："),
   ("code", u"<|begin|><|system|>你是一個樂於助人的助理……<|end|>\n<|user|>今天台北天氣如何？<|end|>\n<|assistant|>"),
   ("p", u"模型的任務就是接著 <code>&lt;|assistant|&gt;</code> 之後繼續寫下去，直到生成代表結束的特殊 token。不同模型的 template 格式不同，用錯格式會讓模型表現明顯變差。"),
   ("ul", [u"<strong>系統提示</strong>：可能長達數千 token，每次請求都要 prefill 一次（除非有 prefix cache，第 30 課）",
           u"<strong>對話歷史</strong>：每一輪都要把之前的所有對話重新送進去——模型本身沒有記憶，「記憶」就是 prompt",
           u"<strong>工具定義、檢索的文件</strong>：同樣變成 prompt 的一部分"]),
   ("p", u"所以一段聊了很久的對話，每一次回覆的 prefill 成本都在增加。這也是為什麼長對話會越來越慢、越來越貴。"),
  ],
  u"對話依 chat template 以特殊 token 組成一長串輸入，模型從 assistant 標記後接著寫；系統提示、歷史對話與工具定義每次都要 prefill，長對話越來越貴。",
  [u"什麼是 chat template？",
   u"模型如何「記得」之前的對話？",
   u"為什麼長對話會越來越慢？"]),

lesson(u"Embedding",
  u"token ID 變成向量",
  [u"理解 embedding 的作用",
   u"知道 embedding 矩陣的大小",
   u"認識輸出端的 unembedding"],
  [("p", u"Token ID 只是一個編號，本身沒有意義。模型的第一步是查表：用 ID 去 <strong>embedding 矩陣</strong>中取出對應的一列，得到一個長度為 d 的向量（d 稱為隱藏維度，例如 Llama 3 8B 是 4096）。"),
   ("t", [u"項目", u"Llama 3 8B 的數字"],
         [[u"詞彙表大小", u"128,256"], [u"隱藏維度 d", u"4,096"], [u"Embedding 矩陣", u"128,256 × 4,096 ≈ 5.25 億個參數"], [u"每個 token 的向量", u"4,096 個數字"]]),
   ("p", u"訓練之後，意義相近的 token 在這個高維空間中會靠得比較近。接下來的每一層 Transformer，都是在一步一步地改寫這些向量，把上下文的資訊加進去。"),
   ("p", u"模型的最後一步則相反：把最後一層的向量乘上一個「<strong>unembedding</strong>」（輸出投影）矩陣，得到詞彙表中每個 token 的分數（<strong>logits</strong>），再由此抽出下一個 token（第 25 課）。這一步在 decode 時每個 token 都要做一次，詞彙表越大，這一步越花時間。"),
  ],
  u"Embedding 以 token ID 查表取得 d 維向量（Llama 3 8B 為 4096 維），各層逐步改寫向量；最後由 unembedding 投影成詞彙表大小的 logits。",
  [u"Embedding 矩陣的形狀是什麼？",
   u"什麼是 logits？",
   u"為什麼詞彙表越大，decode 每步越花時間？"]),

lesson(u"位置資訊：RoPE",
  u"模型怎麼知道字的順序",
  [u"理解位置編碼的必要性",
   u"認識 RoPE 的原理",
   u"了解它和長上下文的關係"],
  [("p", u"注意力機制本身不管順序：「狗咬人」和「人咬狗」如果沒有位置資訊，看起來是一樣的。所以模型必須以某種方式把<strong>位置</strong>加進去。"),
   ("p", u"現代 LLM 多半使用 <strong>RoPE</strong>（Rotary Position Embedding，旋轉位置編碼，2021 年提出）：把 Q 和 K 向量的每一對維度，依照 token 的位置<strong>旋轉一個角度</strong>。位置越後面，旋轉得越多。"),
   D(r"\text{RoPE}(x, m) = R(m\theta)\,x,\qquad \langle R(m\theta)q,\; R(n\theta)k\rangle \text{ 只取決於 } m-n"),
   ("p", u"這個設計的巧妙之處在於：兩個 token 的注意力分數，只取決於它們的<strong>相對距離</strong>，而不是絕對位置。而且每一對維度用不同的旋轉頻率，低頻的維度能表示很遠的距離。"),
   ("p", u"RoPE 也和長上下文息息相關：模型如果只在 8K 長度上訓練，直接拿去處理 128K 的輸入會表現很差。研究者發展出 NTK-aware 縮放、YaRN 等方法調整旋轉頻率，讓模型能以較少的額外訓練延伸上下文長度。"),
   ("note", u"推論上的影響", [("p", u"RoPE 是在每一層對 Q、K 做旋轉，計算量很小。KV Cache 中存的 K 通常已經是旋轉後的版本，所以 decode 時不必重算。")]),
  ],
  u"注意力本身不分順序，需要位置資訊；RoPE 依位置旋轉 Q、K，使注意力只取決於相對距離；調整旋轉頻率可延伸上下文長度。",
  [u"為什麼模型需要位置資訊？",
   u"RoPE 是怎麼編碼位置的？",
   u"RoPE 和長上下文有什麼關係？"]),

lesson(u"一個 Transformer 層裡有什麼",
  u"注意力、MLP、殘差、正規化",
  [u"認識 Transformer 層的結構",
   u"理解注意力與 MLP 的分工",
   u"知道參數主要在哪裡"],
  [("p", u"現代的 LLM 幾乎都是 <strong>decoder-only Transformer</strong>：由數十個結構相同的「層」疊起來。"),
   fig(_LAYER, 236, u"一個 Transformer 層的結構。"),
   ("t", [u"元件", u"作用", u"參數量（Llama 3 8B 每層）"],
         [[u"RMSNorm", u"把向量的大小正規化，讓訓練穩定", u"很少"], [u"注意力", u"讓每個 token 從前面的 token 收集資訊", u"約 4,200 萬（Q、K、V、O 四個投影）"],
          [u"MLP（SwiGLU）", u"對每個 token 各自做非線性的加工，被認為儲存了大量「知識」", u"約 1.76 億（三個矩陣，中間維度 14,336）"],
          [u"殘差連接", u"把輸入直接加到輸出，讓資訊與梯度可以穿過很多層", u"無"]]),
   ("p", u"可以看到，<strong>大約三分之二的參數在 MLP</strong>。32 層加起來約 70 億，再加上 embedding 與輸出層，就是「8B」。"),
   ("p", u"從推論的角度，每一層都是一串<strong>矩陣乘法</strong>：輸入向量乘上權重矩陣。無論是 prefill 還是 decode，每生成一個 token，所有層的所有權重都要參與計算一次——這是理解推論成本的關鍵。"),
  ],
  u"Decoder-only Transformer 由數十個相同的層組成，每層有正規化、注意力、MLP 與殘差；約三分之二參數在 MLP；每個 token 都要經過所有權重的矩陣乘法。",
  [u"注意力和 MLP 的分工是什麼？",
   u"Llama 3 8B 的參數主要在哪裡？",
   u"為什麼說每個 token 都要用到所有權重？"]),
]),

(u"模組 C｜注意力與 KV Cache", [

lesson(u"Q、K、V：注意力的直覺",
  u"像在資料庫中查詢",
  [u"理解 Query、Key、Value 的意義",
   u"理解注意力的計算",
   u"認識多頭注意力"],
  [("p", u"注意力機制可以想像成一次「模糊的資料庫查詢」：每個 token 都會產生三個向量："),
   fig(_QKV, 256, u"注意力的計算流程。"),
   D(r"\text{Attention}(Q,K,V) = \text{softmax}\!\left(\frac{QK^\top}{\sqrt{d_k}}\right)V"),
   ("p", u"例如在「貓坐在墊子上，牠很舒服」中，「牠」的 Query 會和「貓」的 Key 有很高的相似度，於是「牠」的輸出向量會加入大量「貓」的資訊——模型因此「知道」牠指的是貓。"),
   ("p", u"<strong>多頭注意力</strong>：每一層不是只做一次注意力，而是分成很多個「頭」（Llama 3 8B 有 32 個頭，每個頭 128 維），各自關注不同的關係——有的頭關注語法、有的關注指代、有的關注前一個字。"),
   lfw({"t": "attn", "q": u"點任一列，看看那個 token 把注意力放在哪裡："}),
  ],
  u"每個 token 產生 Query、Key、Value；以 Q 與所有 K 的內積經 softmax 得權重，再加權平均 V；多頭注意力讓不同的頭關注不同的關係。",
  [u"Q、K、V 各代表什麼？",
   u"為什麼要除以 √d？（提示：避免分數太大）",
   u"多頭注意力的好處是什麼？"]),

lesson(u"因果遮罩",
  u"只能看前面",
  [u"理解因果遮罩的作用",
   u"理解它與自回歸生成的關係",
   u"比較雙向與單向模型"],
  [("p", u"生成式 LLM 在訓練時被要求「看前面的字，預測下一個字」。為了不讓模型「偷看答案」，注意力被加上了<strong>因果遮罩</strong>（causal mask）：每個 token 只能注意自己和它前面的 token。"),
   ("p", u"在注意力分數矩陣中，這等於把右上三角的部分設為負無限大，softmax 之後權重為 0（上一課的互動中灰色的格子）。"),
   ("p", u"因果遮罩帶來一個對推論極為重要的性質：<strong>前面 token 的計算結果，不會因為後面加了新的 token 而改變</strong>。第 5 個 token 的 K 和 V，無論後面接了什麼，都是一樣的。"),
   ("p", u"這就是 KV Cache 能夠成立的前提——算過的 K、V 可以存起來重複使用（下一課）。"),
   ("t", [u"", u"雙向（例如 BERT）", u"單向／因果（例如 GPT、Llama）"],
         [[u"每個 token 看得到", u"前後所有 token", u"只有前面的 token"], [u"擅長", u"理解、分類、搜尋向量", u"生成文字"], [u"能否快取", u"加一個字，所有 token 都要重算", u"前面的結果可以快取"]]),
  ],
  u"因果遮罩讓每個 token 只能注意前面的 token；因此前面 token 的 K、V 不會因後面新增 token 而改變，這是 KV Cache 成立的前提。",
  [u"因果遮罩在注意力矩陣上長什麼樣子？",
   u"因果遮罩帶來了什麼重要性質？",
   u"為什麼 BERT 不適合逐字生成？"]),

lesson(u"KV Cache",
  u"用記憶體換計算",
  [u"理解 KV Cache 存了什麼",
   u"理解它省下了多少計算",
   u"理解 prefill 與 KV Cache 的關係"],
  [("p", u"生成第 n 個 token 時，它的 Query 需要和前面所有 n−1 個 token 的 Key、Value 做注意力。如果每次都重新計算前面所有 token，計算量會隨長度平方成長。"),
   fig(_CACHE, 226, u"KV Cache 的取捨。"),
   ("p", u"<strong>KV Cache</strong> 的做法是：每算出一個 token 在每一層的 K 和 V，就存在 GPU 記憶體裡。之後的每一步只需要："),
   ("ol", [u"為新的 token 計算它的 Q、K、V（只有一個 token）",
           u"把新的 K、V 加進快取",
           u"用新的 Q 和快取中所有的 K、V 做注意力"]),
   ("p", u"現在可以更精確地定義兩個階段了："),
   ("ul", [u"<strong>Prefill</strong> ＝ 為整段輸入一次建立 KV Cache（並算出第一個輸出 token）",
           u"<strong>Decode</strong> ＝ 每一步讀取 KV Cache、加入一個新 token 的 K、V"]),
   ("p", u"KV Cache 是推論系統中最重要、也最麻煩的資料結構：它讓 decode 變得可行，卻佔用大量記憶體，而且大小隨著上下文長度與同時服務的人數不斷增長（下一課）。"),
  ],
  u"KV Cache 存下每個 token 在每層的 K、V，讓 decode 每步只算新 token；prefill 是為整段輸入建立快取，decode 是讀取並擴充快取；它以大量記憶體換取計算。",
  [u"KV Cache 存了什麼？",
   u"沒有 KV Cache 時計算量如何成長？",
   u"用 KV Cache 重新定義 prefill 與 decode。"]),

lesson(u"KV Cache 有多大",
  u"自己算算看",
  [u"學會計算 KV Cache 的大小",
   u"理解影響大小的因素",
   u"理解它對服務容量的影響"],
  [("p", u"每個 token 的 KV Cache 大小是："),
   D(r"\text{KV}_\text{per token} = 2 \times L \times n_\text{kv} \times d_\text{head} \times \text{bytes}"),
   ("p", u"其中 2 是 K 和 V、L 是層數、n_kv 是 KV 頭數、d_head 是每個頭的維度。以 Llama 3 8B（BF16）為例：2 × 32 × 8 × 128 × 2 ＝ 131,072 bytes ＝ <strong>128 KiB</strong>。"),
   lfw({"t": "kv", "q": u"選擇模型、上下文長度與同時服務的請求數，看 KV Cache 佔用多少記憶體："}),
   ("t", [u"情境（Llama 3 70B，BF16）", u"KV Cache"],
         [[u"一個請求、8K tokens", u"約 2.5 GiB"], [u"一個請求、128K tokens", u"約 40 GiB"], [u"32 個請求、各 8K tokens", u"約 80 GiB"]]),
   ("p", u"這說明了幾件事：長上下文非常昂貴；同時服務的人越多，KV Cache 越大；而 GPU 記憶體在放了模型權重之後，剩下的空間<strong>決定了能同時服務多少人</strong>。"),
  ],
  u"每 token 的 KV Cache ＝ 2 × 層數 × KV 頭數 × 頭維度 × 位元組數，Llama 3 8B 為 128 KiB；長上下文與高並發讓它急速增長，剩餘記憶體決定服務容量。",
  [u"Llama 3 8B 每個 token 的 KV Cache 是多少？",
   u"Llama 3 70B 處理 128K tokens 需要多少 KV Cache？",
   u"為什麼 KV Cache 決定了服務容量？"]),

lesson(u"MHA、MQA、GQA、MLA",
  u"為了縮小 KV Cache 的架構演變",
  [u"認識四種注意力架構",
   u"理解它們如何縮小 KV Cache",
   u"了解品質與效率的取捨"],
  [("p", u"既然 KV Cache 這麼大，模型設計者開始從架構上想辦法縮小它："),
   fig(_GQA, 214, u"不同注意力架構的 KV 頭數。"),
   ("t", [u"架構", u"提出", u"做法", u"代表模型"],
         [[u"MHA（多頭注意力）", u"2017", u"每個 Q 頭都有自己的 K、V", u"GPT-3、Llama 2 7B"],
          [u"MQA（多查詢注意力）", u"Shazeer，2019", u"所有 Q 頭共用一組 K、V", u"PaLM、Falcon"],
          [u"GQA（分組查詢注意力）", u"Ainslie 等，2023", u"Q 頭分組，每組共用一組 K、V", u"Llama 2 70B、Llama 3、Mistral"],
          [u"MLA（多頭潛在注意力）", u"DeepSeek-V2，2024", u"把 K、V 壓縮成一個低維的潛在向量存起來，用時再展開", u"DeepSeek-V2、V3"]]),
   ("p", u"GQA 是目前最主流的折衷：Llama 3 8B 有 32 個 Q 頭、8 個 KV 頭，KV Cache 只有 MHA 的四分之一，品質幾乎沒有損失。"),
   ("p", u"MLA 則走得更遠：DeepSeek-V3 每層每個 token 只存一個 576 維的向量，雖然模型有 6710 億參數，KV Cache 卻比許多小得多的模型還小。代價是計算變得更複雜。"),
   ("p", u"其他縮小 KV Cache 的方法還有：<strong>滑動視窗注意力</strong>（只看最近的 N 個 token，例如 Mistral 7B）、<strong>KV Cache 量化</strong>（用 FP8 或更低精度存）、以及部分層不做全域注意力的混合架構。"),
  ],
  u"MHA 每個 Q 頭有自己的 KV；MQA 全部共用；GQA 分組共用是主流折衷；MLA 將 KV 壓成潛在向量；另有滑動視窗與 KV 量化等方法。",
  [u"GQA 的做法是什麼？",
   u"MLA 如何縮小 KV Cache？",
   u"舉一個不改架構的 KV Cache 縮小方法。"]),

lesson(u"長上下文的代價",
  u"注意力的平方成本",
  [u"理解注意力計算的平方成長",
   u"理解長上下文對兩個階段的影響",
   u"認識長上下文的工程對策"],
  [("p", u"注意力有一個本質的成本問題：每個 token 都要和前面所有 token 比對。"),
   ("t", [u"階段", u"注意力的成本", u"MLP 等其他部分"],
         [[u"Prefill N 個 token", u"∝ N²（每個 token 和前面所有 token 比對）", u"∝ N"],
          [u"Decode 第 n 個 token", u"∝ n（讀取整個 KV Cache）", u"固定（讀一次權重）"]]),
   ("p", u"在短上下文時，MLP 的計算佔大部分，注意力的平方項不明顯。但當上下文到了數萬甚至數十萬 token，注意力會變成主要成本："),
   ("ul", [u"<strong>Prefill 變慢</strong>：一次讀十萬 token 的文件，TTFT 可能從幾百毫秒變成十幾秒",
           u"<strong>Decode 變慢</strong>：每一步都要讀取巨大的 KV Cache，讀 KV 的時間可能超過讀權重的時間",
           u"<strong>記憶體爆炸</strong>：KV Cache 隨長度線性成長，能同時服務的人數大幅下降"]),
   ("p", u"工程上的對策包括：FlashAttention 減少記憶體讀寫（第 19 課）、chunked prefill（第 20 課）、prefix caching 避免重算（第 30 課）、序列平行把長序列切到多張卡上，以及前面提到的 GQA、MLA、滑動視窗等架構改良。"),
  ],
  u"Prefill 的注意力成本隨長度平方成長，decode 每步隨長度線性成長；長上下文讓 TTFT、TPOT 與記憶體都惡化，需要 FlashAttention、chunked prefill、prefix cache 等對策。",
  [u"Prefill 的注意力成本如何隨長度成長？",
   u"長上下文對 decode 有什麼影響？",
   u"舉兩個長上下文的工程對策。"]),
]),

(u"模組 D｜Prefill 階段", [

lesson(u"Prefill 做了什麼",
  u"一次平行處理整段輸入",
  [u"理解 prefill 的計算過程",
   u"理解為什麼 prefill 可以平行",
   u"認識 prefill 的輸出"],
  [("p", u"Prefill 階段，整段輸入的 N 個 token 被排成一個 N × d 的矩陣，<strong>一起</strong>穿過每一層。"),
   fig(_PREFILL, 226, u"Prefill 以矩陣乘矩陣的方式處理所有 token。"),
   ("p", u"為什麼可以一起算？因為輸入的所有 token 都已經知道了，而因果遮罩保證每個 token 只依賴前面的 token——這和訓練時的「teacher forcing」完全相同。所以 prefill 的計算方式和訓練的前向傳播幾乎一模一樣。"),
   ("p", u"Prefill 結束時產出兩樣東西："),
   ("ol", [u"<strong>整段輸入的 KV Cache</strong>：每一層、每個 token 的 K 和 V",
           u"<strong>第一個輸出 token</strong>：只需要用最後一個 token 位置的輸出向量算 logits"]),
   ("p", u"注意第 2 點：雖然 prefill 為每個位置都算了輸出向量，但只有最後一個位置會被拿來預測下一個 token。前面位置的輸出只用來產生下一層需要的 K、V。"),
  ],
  u"Prefill 把 N 個輸入 token 排成矩陣一起穿過每層，因所有 token 已知且有因果遮罩，與訓練前向傳播相同；產出整段 KV Cache 與第一個輸出 token。",
  [u"為什麼 prefill 可以平行處理？",
   u"Prefill 產出哪兩樣東西？",
   u"為什麼只有最後一個位置的輸出被用來預測？"]),

lesson(u"矩陣乘法與 FLOPs",
  u"算一算 prefill 的運算量",
  [u"學會估算 prefill 的運算量",
   u"理解「2 × 參數 × token 數」的由來",
   u"估算 prefill 的時間"],
  [("p", u"一個 m × k 的矩陣乘上一個 k × n 的矩陣，需要 m × k × n 次乘法和差不多一樣多的加法，所以約 <strong>2mkn 次浮點運算</strong>（FLOPs）。"),
   ("p", u"對 Transformer 來說，每個 token 經過一個 d × d 的權重矩陣需要 2 × d × d 次運算——也就是「每個參數 2 次運算」。把所有層的權重加起來："),
   D(r"\text{FLOPs}_\text{prefill} \approx 2 \times P \times N \;+\; \text{注意力項}"),
   ("p", u"P 是參數量、N 是輸入 token 數。例如 Llama 3 8B 處理 2,000 個 token："),
   D(r"2 \times 8\times10^9 \times 2000 = 3.2\times10^{13}\ \text{FLOPs} = 32\ \text{TFLOP}"),
   ("p", u"H100 的 BF16 稠密算力約 989 TFLOPS，實際利用率（MFU）約 40%～60%，所以這次 prefill 約需 <strong>55～80 毫秒</strong>。"),
   lfw({"t": "speed", "q": u"換不同的 GPU 和模型，比較 prefill 與 decode 的時間："}),
   ("note", u"注意力項", [("p", u"注意力的 QKᵀ 與乘 V 的運算量約為 2 × 2 × L × N² × d（因果遮罩可省一半），在 N 遠小於 d 的若干倍時可以忽略；在長上下文時就不能忽略了。")]),
  ],
  u"矩陣乘法約 2mkn FLOPs，每個 token 每個參數約 2 次運算，所以 prefill 約 2 × 參數 × token 數；8B 模型讀 2000 token 約 32 TFLOP，H100 上約 55～80 毫秒。",
  [u"為什麼每個參數約做 2 次運算？",
   u"Llama 3 8B prefill 2000 tokens 約需多少 FLOPs？",
   u"什麼是 MFU？"]),

lesson(u"為什麼 prefill 是算力受限",
  u"算術強度的概念",
  [u"理解算術強度",
   u"理解 prefill 的算術強度",
   u"理解什麼是 compute-bound"],
  [("p", u"GPU 做一次運算需要兩樣東西：<strong>資料</strong>（從記憶體讀進來）和<strong>運算單元</strong>（Tensor Core）。哪一個先不夠用，就是瓶頸。"),
   ("p", u"<strong>算術強度</strong>（arithmetic intensity）＝ 運算次數 ÷ 讀寫的位元組數。強度越高，代表每讀一份資料能做越多事。"),
   ("p", u"Prefill 時，一個 d × d 的權重矩陣（d² × 2 bytes）被讀進來一次，卻要和 N 個 token 相乘（2 × d² × N 次運算）："),
   D(r"\text{算術強度} \approx \frac{2 d^2 N}{2 d^2} = N\ \text{FLOP/byte}"),
   ("p", u"一段 2,000 token 的輸入，強度約 2,000。而 H100 的「轉折點」（算力 ÷ 頻寬）約 295 FLOP/byte。強度遠高於轉折點，代表資料供應綽綽有餘，瓶頸在運算單元——這就是 <strong>compute-bound</strong>。"),
   ("p", u"一個實用的結論：只要 prefill 的 token 數超過幾百個，它就能把 GPU 的算力用得很滿。進一步加快 prefill 只能靠更多的算力（更快的 GPU、更多張卡）或更少的運算（更小的模型、prefix cache 避免重算）。"),
  ],
  u"算術強度是運算次數除以讀寫位元組數；prefill 的強度約等於 token 數 N，遠高於 H100 的轉折點約 295，所以 prefill 是算力受限。",
  [u"什麼是算術強度？",
   u"Prefill 的算術強度大約是多少？",
   u"什麼是 compute-bound？"]),

lesson(u"FlashAttention",
  u"不把大矩陣寫回記憶體",
  [u"理解標準注意力的記憶體問題",
   u"理解 FlashAttention 的核心想法",
   u"認識它的演進"],
  [("p", u"標準的注意力實作會先算出完整的 N × N 分數矩陣、寫回 GPU 的主記憶體（HBM），再讀出來做 softmax、再寫回、再讀出來乘 V。N 很大時，這個矩陣非常巨大，而且大量的讀寫讓注意力變成了<strong>頻寬受限</strong>。"),
   ("p", u"2022 年，Tri Dao 等人提出 <strong>FlashAttention</strong>，核心想法是："),
   ("ul", [u"<strong>分塊（tiling）</strong>：把 Q、K、V 切成小塊，每次只載入能放進 GPU 晶片上高速 SRAM 的大小",
           u"<strong>線上 softmax</strong>：用一個數學技巧，邊算邊更新 softmax 的最大值與總和，不需要先看到整列",
           u"<strong>不寫回中間結果</strong>：N × N 的分數矩陣從來不會完整地出現在 HBM 中"]),
   ("p", u"結果是：計算量完全相同（是精確計算，不是近似），但記憶體讀寫大幅減少，速度提升數倍，而且記憶體用量從 N² 變成 N，讓長上下文成為可能。"),
   ("t", [u"版本", u"年份", u"重點"],
         [[u"FlashAttention", u"2022", u"分塊＋線上 softmax"], [u"FlashAttention-2", u"2023", u"更好的平行化與工作分配"],
          [u"FlashAttention-3", u"2024", u"針對 Hopper（H100）的非同步與 FP8 最佳化"], [u"FlashDecoding", u"2023", u"針對 decode 階段：把長 KV Cache 切開平行讀取"]]),
  ],
  u"標準注意力需讀寫巨大的 N×N 矩陣；FlashAttention 以分塊、線上 softmax 與不寫回中間結果，在相同計算量下大幅減少記憶體讀寫，讓長上下文可行。",
  [u"標準注意力有什麼記憶體問題？",
   u"FlashAttention 的三個核心想法是什麼？",
   u"FlashAttention 是近似計算嗎？"]),

lesson(u"Chunked prefill",
  u"把長輸入切段處理",
  [u"理解長 prefill 對其他請求的影響",
   u"理解 chunked prefill 的做法",
   u"了解它的取捨"],
  [("p", u"在一台同時服務很多人的推論伺服器上，如果有人送來一段 10 萬 token 的文件，它的 prefill 可能要花好幾秒。如果這段時間 GPU 只做這件事，其他正在 decode 的使用者就會<strong>卡住好幾秒</strong>——他們的文字突然停止冒出來。"),
   ("p", u"<strong>Chunked prefill</strong>（分塊預填）的做法是：把長輸入切成固定大小的段（例如每段 512 或 2048 個 token），每一個推論步驟只處理一段 prefill，<strong>同時</strong>搭配其他請求的 decode 一起算。"),
   ("ul", [u"<strong>好處一</strong>：正在 decode 的使用者不會被長時間打斷，TPOT 更穩定",
           u"<strong>好處二</strong>：decode 是頻寬受限、prefill 是算力受限，把兩者混在同一步裡，可以同時用滿頻寬與算力（「搭便車」）",
           u"<strong>代價</strong>：長請求本身的 TTFT 會稍微變長；每段之間需要讀取已經建立的部分 KV Cache"]),
   ("p", u"Chunked prefill 由 Sarathi 等研究提出，現在已是 vLLM、SGLang、TensorRT-LLM 等推論框架的標準功能。它也是第 33 課「prefill 與 decode 分離」的另一種思路：與其把兩者分開，不如讓它們和平共處。"),
  ],
  u"長 prefill 會長時間阻塞其他使用者的 decode；chunked prefill 把長輸入切段，每步搭配其他請求的 decode 一起算，穩定 TPOT 並同時用滿算力與頻寬。",
  [u"長 prefill 會對其他使用者造成什麼影響？",
   u"Chunked prefill 怎麼做？",
   u"為什麼混合 prefill 與 decode 可以提高效率？"]),
]),
]
