# -*- coding: utf-8 -*-
"""一次 LLM 推論到底發生什麼：模組 E～H（第 21～44 課）。"""
from lf_common import *

lesson = lflesson

_AR = svg(
    title(u"自回歸迴圈：每一步的輸出變成下一步的輸入"),
    box(30, 80, 120, 60, u"新 token", [u"（上一步的輸出）"], BLUE),
    box(200, 60, 170, 100, u"穿過所有層", [u"讀全部權重", u"讀 KV Cache", u"寫入新的 K、V"], PURPLE),
    box(420, 80, 90, 60, u"logits", [u"詞彙表分數"], ORANGE), box(540, 80, 80, 60, u"抽樣", [u"選一個"], GREEN),
    A(150, 110, 198, 110, MUTED, 1.4), A(370, 110, 418, 110, MUTED, 1.4), A(510, 110, 538, 110, MUTED, 1.4),
    P("M580 140 L580 190 L90 190 L90 142", GREEN, sw=1.4, dash="5 3"), T(335, 206, u"重複，直到生成結束符號或達到長度上限", 10, GREEN),
)

_HIER = svg(
    title(u"GPU 記憶體階層（以 H100 為例，數量級）"),
    box(40, 44, 560, 34, u"暫存器：每個 SM 256 KB，延遲約 1 個週期", [], RED),
    box(90, 88, 460, 34, u"SRAM（L1／共享記憶體）：每 SM 約 228 KB，總計約 30 MB 級", [], ORANGE),
    box(140, 132, 360, 34, u"L2 快取：50 MB，數 TB/s 以上", [], GOLD),
    box(190, 176, 260, 34, u"HBM：80 GB，3.35 TB/s", [], BLUE),
    box(240, 220, 160, 34, u"主機記憶體（PCIe）", [], GRAY),
    T(30, 232, u"↑ 越往上：越小、越快", 10, RED, "start"), T(30, 250, u"↓ 越往下：越大、越慢", 10, GRAY, "start"),
)

_PAR = svg(
    title(u"三種切模型的方法"),
    box(20, 46, 190, 150, u"張量平行（TP）", [u"每一層的矩陣切成 N 份", u"每張卡算一部分", u"每層都要同步（all-reduce）", u"需要極快互連", u"通常限於單機 8 卡"], BLUE),
    box(225, 46, 190, 150, u"管線平行（PP）", [u"把層切成幾段", u"每張卡負責幾層", u"只在段落之間傳遞", u"通訊少，延遲加長", u"可以跨機器"], GREEN),
    box(430, 46, 190, 150, u"專家平行（EP）", [u"MoE 的專家分到各卡", u"token 被送到對應專家", u"all-to-all 通訊", u"適合大型 MoE", u"負載平衡是難題"], ORANGE),
    T(320, 220, u"實務上常組合使用，例如單機內 TP＋跨機 PP 或 EP", 10, ACC),
)

_DISAG = svg(
    title(u"Prefill／Decode 分離部署"),
    box(20, 60, 180, 110, u"Prefill 叢集", [u"算力強", u"批次大、算力受限", u"專心壓低 TTFT"], GREEN),
    box(440, 60, 180, 110, u"Decode 叢集", [u"頻寬大、記憶體大", u"大批次 decode", u"專心穩定 TPOT"], BLUE),
    A(200, 115, 438, 115, PURPLE, 2), T(320, 104, u"傳送 KV Cache", 10, PURPLE), T(320, 134, u"（RDMA／NVLink）", 9, MUTED),
    T(320, 200, u"兩個階段各自調整機器數量與平行策略；代價是要搬運 KV Cache", 10, ACC),
)

_MOE = svg(
    title(u"MoE：每個 token 只用到少數專家"),
    box(20, 90, 100, 50, u"token", [], BLUE), box(150, 90, 100, 50, u"路由器", [u"選 top-k"], PURPLE),
    [box(300 + (i % 4) * 82, 50 + (i // 4) * 80, 72, 50, u"專家 %d" % (i + 1), [], ORANGE if i in (1, 6) else GRAY) for i in range(8)],
    A(120, 115, 148, 115, MUTED, 1.4), A(250, 110, 418, 102, ORANGE, 1.6), A(250, 120, 500, 128, ORANGE, 1.6),
    T(320, 222, u"記憶體要放全部專家，但每個 token 的計算只用到被選中的少數", 10, ACC),
)


MODULES = [
(u"模組 E｜Decode 階段", [

lesson(u"自回歸生成",
  u"一次只能生一個 token",
  [u"理解自回歸生成的迴圈",
   u"理解為什麼 decode 無法平行",
   u"知道 decode 每一步讀了什麼"],
  [("p", u"Prefill 產出第一個 token 後，進入 <strong>decode 迴圈</strong>："),
   fig(_AR, 220, u"自回歸生成的迴圈。"),
   ("p", u"關鍵在於：第 n+1 個 token 取決於第 n 個 token 是什麼，而第 n 個 token 要等這一步算完、抽樣之後才知道。所以<strong>同一個請求的 decode 步驟只能一步一步來</strong>，無法像 prefill 那樣把所有位置一起算。"),
   ("p", u"每一步 decode 要做的事："),
   ("ol", [u"把新 token 的 embedding 送進第一層",
           u"在每一層，為這一個 token 算 Q、K、V，把 K、V 寫入快取，用 Q 對整個 KV Cache 做注意力，再過 MLP",
           u"最後一層的輸出乘上 unembedding 得到 logits",
           u"從 logits 抽樣出下一個 token"]),
   ("p", u"一個回答有 500 個 token，就要跑這個迴圈 500 次，每次都要把整個模型的權重讀一遍。這就是為什麼長回答總是比長問題花更多時間。"),
  ],
  u"Decode 迴圈每步把上一個 token 送進所有層、讀 KV Cache、算 logits 並抽樣；下一個 token 取決於上一個，所以同一請求的 decode 無法平行。",
  [u"為什麼 decode 不能像 prefill 一樣平行？",
   u"Decode 每一步要做哪些事？",
   u"為什麼輸出長度比輸入長度更影響總時間？"]),

lesson(u"為什麼 decode 是頻寬受限",
  u"每生一個字都要讀整個模型",
  [u"計算 decode 的算術強度",
   u"理解頻寬受限的意義",
   u"估算 decode 的速度"],
  [("p", u"回顧第 18 課：prefill 的算術強度約等於 token 數 N。Decode 每一步只有一個 token，N = 1："),
   D(r"\text{算術強度}_\text{decode} \approx \frac{2 d^2 \times 1}{2 d^2} = 1\ \text{FLOP/byte}"),
   ("p", u"H100 的轉折點約 295 FLOP/byte，decode 的強度只有 1——運算單元有 99% 以上的時間在<strong>等資料</strong>。這就是 <strong>memory-bound（頻寬受限）</strong>。"),
   ("p", u"這時候決定速度的不是算力，而是「把整個模型從 HBM 讀一遍要多久」："),
   D(r"\text{每步時間} \gtrsim \frac{\text{權重大小} + \text{KV Cache 大小}}{\text{記憶體頻寬}}"),
   ("p", u"以 Llama 3 8B（BF16，16 GB）在 H100（3.35 TB/s）上為例：16 ÷ 3350 ≈ 4.8 毫秒，也就是單一請求最多約 <strong>每秒 210 個 token</strong>。實際上還有 kernel 啟動等開銷，通常能達到理論值的 60%～80%。"),
   ("note", u"一個反直覺的結論", [("p", u"在 decode 階段，換一張算力強一倍但頻寬相同的 GPU，單一請求幾乎不會變快；換一張頻寬大一倍的 GPU，速度幾乎翻倍。這就是為什麼新一代 GPU 都拚命增加 HBM 頻寬。")]),
  ],
  u"Decode 每步只處理 1 個 token，算術強度約 1，遠低於轉折點，因此受記憶體頻寬限制；每步時間至少是權重加 KV Cache 大小除以頻寬。",
  [u"Decode 的算術強度大約是多少？",
   u"Llama 3 8B 在 H100 上的 decode 理論上限約多少 token/s？",
   u"為什麼提高算力對單一請求的 decode 幫助不大？"]),

lesson(u"Roofline 模型",
  u"一張圖看懂兩種瓶頸",
  [u"認識 roofline 圖",
   u"在圖上定位 prefill 與 decode",
   u"理解轉折點的意義"],
  [("p", u"<strong>Roofline 模型</strong>（Williams 等，2009）把「算力」和「頻寬」兩種限制畫在同一張圖上："),
   ("ul", [u"橫軸：算術強度（FLOP/byte，對數刻度）",
           u"縱軸：可達到的運算速度（FLOP/s，對數刻度）",
           u"左邊的斜線：頻寬的限制（速度 ＝ 頻寬 × 強度）",
           u"右邊的水平線：算力的上限（屋頂）",
           u"兩者交會處：<strong>轉折點</strong>（ridge point）＝ 算力 ÷ 頻寬"]),
   lfw({"t": "roof", "ai": 1, "q": u"拉動算術強度、切換 GPU，看看工作點落在斜線（頻寬受限）還是屋頂（算力受限）："}),
   ("t", [u"GPU", u"BF16 稠密算力", u"HBM 頻寬", u"轉折點"],
         [[u"A100 80GB", u"312 TFLOPS", u"2.04 TB/s", u"約 153"], [u"H100 SXM", u"989 TFLOPS", u"3.35 TB/s", u"約 295"],
          [u"H200", u"989 TFLOPS", u"4.8 TB/s", u"約 206"], [u"B200", u"2,250 TFLOPS", u"8 TB/s", u"約 281"]]),
   ("p", u"轉折點逐代升高或維持在高位，代表算力成長得比頻寬快——decode 這種低強度的工作，在新硬體上浪費的算力比例只會更高。這正是 batching、推測解碼等技術的動機：<strong>想辦法把 decode 的算術強度往右推</strong>。"),
  ],
  u"Roofline 圖以算術強度為橫軸、運算速度為縱軸，左斜線是頻寬限制、屋頂是算力上限，交點是轉折點；prefill 在屋頂、decode 在斜線底部。",
  [u"Roofline 圖的兩條線各代表什麼？",
   u"H100 的轉折點約是多少？",
   u"為什麼說加速 decode 就是把工作點往右推？"]),

lesson(u"Decode 速度的上限",
  u"不同模型與硬體的估算",
  [u"用頻寬估算 decode 速度",
   u"理解模型大小與精度的影響",
   u"理解多卡如何加速"],
  [("p", u"單一請求的 decode 速度上限，可以簡單估算為："),
   D(r"\text{tokens/s} \lesssim \frac{\text{總頻寬}}{\text{模型位元組數}} = \frac{\text{頻寬} \times \text{GPU 數}}{\text{參數量} \times \text{每參數位元組}}"),
   lfw({"t": "speed", "q": u"切換模型、精度與 GPU 數量，看看 decode 的理論上限："}),
   ("t", [u"情境", u"模型大小", u"理論上限"],
         [[u"Llama 3 8B BF16，1 × H100", u"16 GB", u"約 210 tok/s"], [u"Llama 3 70B BF16，1 × H100", u"140 GB", u"放不下"],
          [u"Llama 3 70B BF16，4 × H100（TP）", u"140 GB", u"約 96 tok/s"], [u"Llama 3 70B 4-bit，1 × H100", u"35 GB", u"約 96 tok/s"],
          [u"Llama 3 8B 4-bit，RTX 4090", u"4 GB", u"約 250 tok/s"]]),
   ("ul", [u"<strong>量化</strong>讓模型變小，直接提升 decode 速度（第 31 課）",
           u"<strong>張量平行</strong>讓多張卡一起讀，總頻寬相加；但每層都要同步，實際加速低於線性（第 37 課）",
           u"<strong>長上下文</strong>時還要加上讀 KV Cache 的量，速度會再下降"]),
  ],
  u"單一請求 decode 上限約為總頻寬除以模型位元組數；量化縮小模型、張量平行增加總頻寬都能加速，長上下文的 KV Cache 讀取則讓速度下降。",
  [u"寫出 decode 速度上限的估算式。",
   u"為什麼 4-bit 的 70B 模型在單張 H100 上和 4 張卡跑 BF16 速度相近？",
   u"為什麼多卡加速不是完全線性？"]),

lesson(u"抽樣",
  u"從 logits 到下一個 token",
  [u"理解 softmax 與溫度",
   u"認識 top-k 與 top-p",
   u"了解抽樣參數對輸出的影響"],
  [("p", u"模型每一步輸出的是詞彙表中每個 token 的分數（logits）。要決定下一個 token，需要先把分數轉成機率："),
   D(r"p_i = \frac{e^{z_i / T}}{\sum_j e^{z_j / T}}"),
   ("ul", [u"<strong>溫度 T</strong>：T < 1 讓分布更尖銳（更保守、更確定），T > 1 讓分布更平坦（更有創意、更容易出錯）；T → 0 等於永遠選最高分（貪婪解碼）",
           u"<strong>Top-k</strong>：只保留分數最高的 k 個候選，其他機率設為 0",
           u"<strong>Top-p（nucleus）</strong>：由高到低累加機率，保留累積達到 p 的最小集合",
           u"<strong>重複懲罰</strong>：降低已經出現過的 token 的分數，避免鬼打牆"]),
   lfw({"t": "sample", "q": u"「我家養了一隻＿＿」的下一個詞：調整溫度、top-k、top-p，然後抽樣看看："}),
   ("p", u"抽樣本身的計算量很小，但它讓同一個問題每次的回答都不同。寫程式、做數學時常用低溫度追求穩定；寫故事、腦力激盪時用較高溫度。"),
   ("note", u"為什麼溫度 0 也可能不一樣？", [("p", u"理論上貪婪解碼是確定的，但實際伺服器中，同一批次裡的其他請求會改變矩陣運算的切分與加總順序，浮點數的捨入差異偶爾會讓兩個分數接近的 token 互換。")]),
  ],
  u"Logits 經溫度調整的 softmax 變成機率；top-k 保留前 k 個、top-p 保留累積機率達 p 的集合；溫度越低越保守，越高越多樣。",
  [u"溫度如何影響分布？",
   u"Top-k 和 top-p 有什麼不同？",
   u"為什麼溫度設 0 也可能得到不同結果？"]),

lesson(u"停止條件與結構化輸出",
  u"什麼時候停、怎麼保證格式",
  [u"認識生成的停止條件",
   u"理解受限解碼",
   u"了解它對推論系統的影響"],
  [("p", u"Decode 迴圈什麼時候結束？常見的停止條件有："),
   ("ul", [u"<strong>結束 token</strong>：模型生成了代表「回答結束」的特殊 token（例如 <code>&lt;|eot_id|&gt;</code>）",
           u"<strong>長度上限</strong>：達到使用者或系統設定的最大輸出 token 數",
           u"<strong>停止字串</strong>：輸出中出現指定的字串（例如程式碼區塊結束）",
           u"<strong>使用者取消</strong>：關掉視窗或按下停止，伺服器要及時釋放 KV Cache"]),
   ("p", u"推論系統事先<strong>不知道</strong>一個請求會生成多少 token。這讓排程變得困難：KV Cache 該預留多少空間？要不要接受新的請求？這也是 PagedAttention 要解決的問題之一（第 29 課）。"),
   ("h", u"受限解碼（constrained decoding）"),
   ("p", u"當應用程式需要模型輸出合法的 JSON、符合某個 schema 或某種文法時，可以在抽樣前<strong>把不合法的 token 的機率設為 0</strong>。例如目前已經輸出了 <code>{\"age\": </code>，下一個 token 就只允許數字。"),
   ("p", u"實作上，系統把 JSON schema 或文法轉成一個有限狀態機，每一步計算哪些 token 合法。挑戰在於詞彙表有十幾萬個 token，每一步都要快速算出遮罩；Outlines、XGrammar 等函式庫用預先計算與快取讓這個開銷變得很小。"),
  ],
  u"生成在遇到結束 token、長度上限、停止字串或使用者取消時停止，輸出長度事先未知；受限解碼在抽樣前遮掉不合文法的 token，保證輸出格式。",
  [u"列出三種停止條件。",
   u"為什麼「不知道輸出多長」會讓排程困難？",
   u"受限解碼如何保證 JSON 格式？"]),
]),

(u"模組 F｜加速技術", [

lesson(u"Batching",
  u"讓多個請求共用一次權重讀取",
  [u"理解 batching 為什麼有效",
   u"理解吞吐量與延遲的取捨",
   u"知道 batch 大小的上限"],
  [("p", u"Decode 時 GPU 大部分時間都在等權重讀進來。既然權重反正要讀，何不讓<strong>多個請求一起用</strong>？把 B 個請求的 token 排成一個 B × d 的矩陣，讀一次權重就能算 B 個 token。"),
   D(r"\text{算術強度}_\text{batch decode} \approx B"),
   lfw({"t": "batch", "q": u"拉動上下文長度，看 batch 大小如何影響每步時間與總吞吐量："}),
   ("ul", [u"<strong>B 小</strong>：每步時間幾乎不變（主要是讀權重），吞吐量隨 B 線性成長——幾乎是免費的",
           u"<strong>B 大</strong>：開始接近算力上限，每步時間變長，每個使用者的 TPOT 變慢",
           u"<strong>KV Cache</strong>：每個請求都有自己的 KV Cache，不能共用。B 越大，讀 KV 的時間越多，記憶體也越快耗盡"]),
   ("p", u"所以 batch 大小同時受到三個限制：延遲目標（TPOT 不能太慢）、算力（轉折點）、記憶體（KV Cache 放不放得下）。在實務上，記憶體往往是最先碰到的上限——這就是為什麼 GQA、KV 量化、PagedAttention 這麼重要。"),
  ],
  u"Batching 讓 B 個請求共用一次權重讀取，算術強度約為 B；B 小時吞吐量幾乎免費提升，B 大時 TPOT 變慢；上限由延遲目標、算力與 KV Cache 記憶體決定。",
  [u"為什麼 batching 對 decode 特別有效？",
   u"Batch 越大，每個使用者會感受到什麼？",
   u"Batch 大小受到哪三個限制？"]),

lesson(u"Continuous batching",
  u"不等整批結束就換人",
  [u"理解靜態 batching 的問題",
   u"理解 continuous batching 的做法",
   u"了解它帶來的效益"],
  [("p", u"最早的 batching 是<strong>靜態</strong>的：湊齊一批請求，一起 prefill、一起 decode，等全部結束再換下一批。問題是每個請求的輸出長度差很多：一個請求寫 20 個字就結束了，另一個寫 2000 個字，前者的位置在剩下的時間裡就<strong>空轉</strong>。"),
   ("p", u"2022 年的 <strong>Orca</strong>（OSDI 2022）提出 <strong>iteration-level scheduling</strong>，後來通稱 <strong>continuous batching</strong>："),
   ("ul", [u"排程的單位從「一批請求」變成「一步 decode」",
           u"每一步結束時，已完成的請求立刻離開，新的請求立刻加入",
           u"新請求的 prefill 可以和其他請求的 decode 合在同一步（搭配 chunked prefill）"]),
   ("p", u"結果是 GPU 幾乎永遠滿載，吞吐量可以比靜態 batching 高出數倍，同時新請求不必等整批結束，TTFT 也大幅改善。"),
   ("p", u"Continuous batching 現在是所有主流推論框架的標準做法。它的實現依賴兩件事：能處理長度不一的序列的注意力 kernel，以及能動態配置與釋放的 KV Cache 管理（下一課）。"),
  ],
  u"靜態 batching 讓已完成的請求空轉；continuous batching 以每一步 decode 為排程單位，完成的請求立刻離開、新請求立刻加入，大幅提升吞吐量與 TTFT。",
  [u"靜態 batching 有什麼問題？",
   u"Continuous batching 的排程單位是什麼？",
   u"它依賴哪兩項技術？"]),

lesson(u"PagedAttention 與 vLLM",
  u"像作業系統一樣管理 KV Cache",
  [u"理解 KV Cache 的碎片化問題",
   u"理解 PagedAttention 的做法",
   u"認識 vLLM"],
  [("p", u"早期系統為每個請求預先配置一塊<strong>連續</strong>的 KV Cache 空間，大小按最大長度預留。但大多數請求遠遠用不到最大長度，加上不同大小的空間來來去去造成碎片，研究發現<strong>六到八成的 KV Cache 記憶體被浪費</strong>。"),
   ("p", u"2023 年，UC Berkeley 團隊在 SOSP 發表 <strong>PagedAttention</strong>，靈感直接來自作業系統的虛擬記憶體："),
   ("t", [u"作業系統", u"PagedAttention"],
         [[u"程序", u"請求"], [u"虛擬頁面", u"邏輯 KV 區塊（例如每 16 個 token 一塊）"], [u"實體頁框", u"GPU 記憶體中的實體區塊"], [u"頁表", u"區塊表"], [u"寫入時複製", u"多個請求共用相同前綴的區塊"]]),
   ("ul", [u"<strong>按需配置</strong>：每生成 16 個 token 才配置一個新區塊，浪費最多只有最後一塊",
           u"<strong>不需連續</strong>：區塊可以散落在記憶體任何地方，注意力 kernel 透過區塊表找到它們",
           u"<strong>可以共用</strong>：平行抽樣多個回答、或多個請求有相同的系統提示時，共用的部分只存一份"]),
   ("p", u"同一團隊開源的 <strong>vLLM</strong> 以 PagedAttention 為核心，把記憶體浪費降到 4% 以下，吞吐量比當時的系統高出 2～4 倍，迅速成為最廣泛使用的開源推論引擎之一。SGLang、TensorRT-LLM 等其他框架也都採用了類似的分頁管理。"),
  ],
  u"連續預留 KV Cache 造成大量浪費與碎片；PagedAttention 借用虛擬記憶體的分頁概念，按需配置不連續的區塊並允許共用，vLLM 以此大幅提升吞吐量。",
  [u"早期 KV Cache 管理浪費在哪裡？",
   u"PagedAttention 和作業系統的哪個概念對應？",
   u"區塊共用在什麼情況下有用？"]),

lesson(u"Prefix caching",
  u"相同的開頭不用算第二次",
  [u"理解 prefix caching 的原理",
   u"認識它的應用場景",
   u"了解它對成本的影響"],
  [("p", u"因果遮罩保證：<strong>相同的前綴，KV Cache 一定相同</strong>。如果很多請求都以同一段系統提示開頭，或者同一段對話的下一輪要重送所有歷史，那麼前面那一段的 KV Cache 根本不必重算。"),
   ("p", u"<strong>Prefix caching</strong> 把算過的 KV 區塊依內容（雜湊）保存下來。新的請求進來時，先找出最長的已快取前綴，只需要 prefill 剩下的部分。"),
   ("ul", [u"<strong>系統提示</strong>：數千 token 的系統提示只算一次，所有使用者共用",
           u"<strong>多輪對話</strong>：每一輪只需 prefill 新增的使用者訊息",
           u"<strong>長文件問答</strong>：對同一份文件問多個問題",
           u"<strong>agent</strong>：工具呼叫的迴圈中，前面的步驟每次都相同"]),
   ("p", u"SGLang 的 <strong>RadixAttention</strong> 用基數樹（radix tree）管理快取的前綴，能高效地找出最長共同前綴；vLLM 則以區塊雜湊實作自動前綴快取。許多 API 服務也提供「提示快取」功能，對命中快取的輸入 token 收取較低的費用。"),
   ("note", u"實用建議", [("p", u"想讓快取命中，就把<strong>不變的內容放前面</strong>（系統提示、工具定義、文件），把會變的內容（使用者問題、時間戳記）放後面。任何前面的改動，都會讓後面的快取全部失效。")]),
  ],
  u"相同前綴的 KV Cache 必然相同，prefix caching 依內容保存 KV 區塊，新請求只需 prefill 未命中的部分；適用於系統提示、多輪對話、文件問答與 agent。",
  [u"為什麼相同前綴可以重複使用 KV Cache？",
   u"舉出三個 prefix caching 的應用情境。",
   u"為什麼要把不變的內容放在 prompt 前面？"]),

lesson(u"量化",
  u"用更少的位元存權重",
  [u"理解量化對推論的好處",
   u"認識主要的量化方法",
   u"了解量化的取捨"],
  [("p", u"Decode 受頻寬限制，模型越小讀得越快。<strong>量化</strong>把權重從 16 位元浮點數改成 8 位元、4 位元甚至更低，模型大小直接減半或剩四分之一。"),
   ("t", [u"格式", u"每參數", u"70B 模型大小", u"說明"],
         [[u"BF16", u"2 bytes", u"140 GB", u"訓練與推論的基準"], [u"FP8", u"1 byte", u"70 GB", u"H100 之後硬體原生支援，品質幾乎無損"],
          [u"INT8", u"1 byte", u"70 GB", u"整數量化，需處理離群值"], [u"INT4／4-bit", u"0.5 byte", u"35 GB", u"GPTQ、AWQ 等方法，常見於本地推論"],
          [u"FP4", u"0.5 byte", u"35 GB", u"Blackwell 世代硬體原生支援"]]),
   ("ul", [u"<strong>僅權重量化</strong>（weight-only）：權重以低精度存放，運算時展開回 16 位元。省頻寬、加速 decode，但不加速運算",
           u"<strong>權重＋啟動值量化</strong>（例如 FP8 W8A8）：運算也用低精度，Tensor Core 速度加倍，同時加速 prefill",
           u"<strong>KV Cache 量化</strong>：把 KV Cache 存成 FP8 等格式，讓 batch 更大、上下文更長"]),
   ("p", u"代表性的方法：<strong>GPTQ</strong>（2022）用二階資訊逐層修正量化誤差；<strong>AWQ</strong>（2023）發現少數重要的權重通道需要保護；llama.cpp 的 <strong>GGUF</strong> 格式提供從 2 位元到 8 位元的多種方案。一般而言 8 位元幾乎無損，4 位元在大模型上損失很小，3 位元以下則開始明顯退化。"),
  ],
  u"量化把權重改用 8 或 4 位元存放，模型縮小、decode 加速；僅權重量化省頻寬，W8A8 也加速運算，KV 量化擴大容量；8 位元幾乎無損，4 位元損失小。",
  [u"為什麼量化可以加速 decode？",
   u"僅權重量化和 W8A8 有什麼差別？",
   u"GPTQ 和 AWQ 各有什麼特點？"]),

lesson(u"推測解碼",
  u"讓小模型先猜，大模型一次驗證",
  [u"理解推測解碼的原理",
   u"理解它為什麼不損失品質",
   u"估算加速比"],
  [("p", u"Decode 時大模型的算力大量閒置。如果能讓它一次驗證多個 token，就能把閒置的算力利用起來——驗證 5 個 token 的時間和生成 1 個 token 差不多，因為瓶頸是讀權重。"),
   ("p", u"<strong>推測解碼</strong>（speculative decoding，Leviathan 等與 Chen 等，2023）的做法："),
   ("ol", [u"用一個小而快的<strong>草稿模型</strong>連續猜出 γ 個 token",
           u"大模型用<strong>一次</strong>前向計算同時處理這 γ 個 token（像小型的 prefill）",
           u"由左到右檢查：接受和大模型一致的 token，遇到第一個不一致就停下，並用大模型的結果補上一個 token"]),
   ("p", u"巧妙的是，透過特殊的接受／拒絕抽樣規則，輸出的<strong>機率分布與大模型單獨生成完全相同</strong>——這是精確加速，不是近似。"),
   D(r"\text{加速比} = \frac{1-\alpha^{\gamma+1}}{(1-\alpha)(\gamma c+1)}"),
   ("p", u"α 是每個草稿 token 被接受的機率，c 是草稿模型與大模型每步時間的比例。"),
   lfw({"t": "spec", "q": u"調整接受率 α、猜測長度 γ 與草稿成本 c，看看加速比，並模擬一次推測過程："}),
   ("p", u"變形包括：不用另一個模型、而是在大模型上加幾個預測頭（<strong>Medusa</strong>、<strong>EAGLE</strong>）；DeepSeek-V3 訓練時加入的<strong>多 token 預測</strong>（MTP）；或者直接從輸入中找重複片段當草稿（適合程式碼修改）。"),
  ],
  u"推測解碼讓草稿模型猜 γ 個 token、大模型一次驗證，利用 decode 閒置的算力；接受／拒絕抽樣保證分布完全相同；加速比取決於接受率與草稿成本。",
  [u"為什麼大模型驗證 5 個 token 和生成 1 個差不多快？",
   u"推測解碼為什麼不損失品質？",
   u"接受率低時會發生什麼？"]),

lesson(u"Prefill／Decode 分離",
  u"把兩個階段交給不同的機器",
  [u"理解兩個階段互相干擾的問題",
   u"理解分離部署的做法",
   u"了解它的代價"],
  [("p", u"Prefill 和 decode 擠在同一張 GPU 上，會互相干擾：一個長 prefill 會讓 decode 的使用者卡頓；為了穩定 TPOT 而限制 prefill，又會讓 TTFT 變長。更根本的是，兩者需要的硬體特性與平行策略完全不同。"),
   fig(_DISAG, 220, u"分離部署：prefill 與 decode 在不同的機器群上執行。"),
   ("p", u"<strong>分離部署</strong>（disaggregation）讓不同的 GPU 群各自專心做一件事："),
   ("ul", [u"<strong>Prefill 節點</strong>：處理新請求，產生 KV Cache 與第一個 token，然後把 KV Cache 傳給 decode 節點",
           u"<strong>Decode 節點</strong>：接收 KV Cache，以大批次持續生成",
           u"兩邊可以依流量各自增減機器、各自選擇平行策略與 batch 大小"]),
   ("p", u"代表研究包括 <strong>DistServe</strong>（2024）、<strong>Splitwise</strong>（2024），以及月之暗面為 Kimi 服務設計的 <strong>Mooncake</strong>（2024），後者還加入了跨機器的 KV Cache 池。DeepSeek 也公開說明其 V3 服務採用了 prefill 與 decode 分離的部署。"),
   ("p", u"代價是要在機器之間搬運 KV Cache：一個 8K token 的 Llama 3 70B 請求有約 2.5 GB 的 KV，需要高速網路（RDMA）才能讓傳輸時間不明顯增加 TTFT。所以它適合大規模的服務，小規模部署用 chunked prefill 通常就夠了。"),
  ],
  u"同機的 prefill 與 decode 互相干擾且需求不同；分離部署讓 prefill 與 decode 節點各自擴充與最佳化，代價是需以高速網路搬運 KV Cache。",
  [u"Prefill 與 decode 在同一張卡上會如何互相干擾？",
   u"分離部署的流程是什麼？",
   u"分離部署的主要代價是什麼？"]),

lesson(u"MoE 模型的推論",
  u"參數很多、計算很少",
  [u"理解 MoE 架構",
   u"理解 MoE 對推論的影響",
   u"認識專家平行"],
  [("p", u"<strong>混合專家</strong>（Mixture of Experts, MoE）模型把 MLP 換成很多個「專家」，每個 token 由路由器挑選其中少數幾個來計算。"),
   fig(_MOE, 236, u"MoE 的路由。"),
   ("t", [u"模型", u"總參數", u"每 token 啟用參數"],
         [[u"Mixtral 8x7B", u"約 470 億", u"約 130 億（8 選 2）"], [u"DeepSeek-V3", u"6,710 億", u"約 370 億（256 個路由專家選 8＋1 共享）"]]),
   ("p", u"對推論來說，MoE 是一把雙面刃："),
   ("ul", [u"<strong>計算少</strong>：每個 token 的 FLOPs 只和啟用參數有關，prefill 很便宜",
           u"<strong>記憶體大</strong>：所有專家都要放在 GPU 記憶體中，671B 模型即使用 FP8 也要約 700 GB",
           u"<strong>小 batch 時頻寬吃虧</strong>：batch 中不同 token 選了不同專家，batch 一大幾乎每個專家都要讀，讀取量接近總參數",
           u"<strong>大 batch 時划算</strong>：每個專家分到足夠多的 token，算術強度回升"]),
   ("p", u"所以 MoE 特別適合大規模服務：用<strong>專家平行</strong>把專家分散到數十甚至上百張 GPU 上，每張卡只放幾個專家，token 透過 all-to-all 通訊送到對應的卡。挑戰在於負載平衡——熱門的專家會成為瓶頸。"),
  ],
  u"MoE 讓每個 token 只用少數專家，計算量低但所有專家都要放進記憶體；小 batch 時頻寬吃虧，大 batch 時划算，適合用專家平行做大規模部署。",
  [u"MoE 的總參數和啟用參數有什麼不同？",
   u"為什麼 MoE 在小 batch 時不划算？",
   u"專家平行的挑戰是什麼？"]),
]),

(u"模組 G｜硬體", [

lesson(u"GPU 的結構",
  u"成千上萬個運算單元",
  [u"認識 GPU 的基本組成",
   u"理解 Tensor Core 的角色",
   u"理解為什麼 GPU 適合矩陣運算"],
  [("p", u"GPU 是為大量平行計算設計的處理器。以 NVIDIA H100 SXM 為例："),
   ("t", [u"元件", u"數量", u"作用"],
         [[u"SM（串流多處理器）", u"132 個", u"GPU 的基本運算單位，每個有自己的排程器、暫存器與共享記憶體"],
          [u"CUDA Core", u"每 SM 128 個", u"一般的浮點與整數運算"], [u"Tensor Core", u"每 SM 4 個", u"專門做小矩陣乘加，提供絕大部分的 AI 算力"],
          [u"HBM3", u"80 GB", u"主記憶體，堆疊在晶片旁"], [u"L2 快取", u"50 MB", u"所有 SM 共用"]]),
   ("p", u"<strong>Tensor Core</strong> 是 AI 推論的主角：它在一個時脈內完成一個小矩陣塊的乘加（例如 BF16 的 16×16 區塊），速度比 CUDA Core 快一個數量級以上。989 TFLOPS 的 BF16 算力幾乎全部來自 Tensor Core。"),
   ("p", u"程式透過 <strong>kernel</strong> 在 GPU 上執行：一個 kernel 被分成成千上萬個執行緒區塊，分配到各個 SM 上。推論引擎的效能很大一部分取決於 kernel 寫得好不好——FlashAttention、各種量化 GEMM、融合（fusion）多個運算以減少記憶體讀寫，都是 kernel 層級的最佳化。"),
   ("p", u"另一個常見的瓶頸是 <strong>kernel 啟動開銷</strong>：decode 每一步要啟動數百個小 kernel，每個都有幾微秒的開銷。<strong>CUDA Graphs</strong> 把整個 decode 步驟錄製起來一次重播，可以明顯降低小 batch 時的延遲。"),
  ],
  u"GPU 由上百個 SM 組成，Tensor Core 提供幾乎全部 AI 算力；程式以 kernel 執行，kernel 品質與融合決定效能；CUDA Graphs 降低 decode 的 kernel 啟動開銷。",
  [u"H100 有多少個 SM？",
   u"Tensor Core 和 CUDA Core 有什麼差別？",
   u"CUDA Graphs 解決什麼問題？"]),

lesson(u"記憶體階層",
  u"HBM、SRAM 與資料搬運",
  [u"認識 GPU 的記憶體階層",
   u"理解 HBM 的角色",
   u"理解為什麼搬資料比算還貴"],
  [fig(_HIER, 270, u"GPU 記憶體階層：越上層越小越快。"),
   ("p", u"推論的所有權重和 KV Cache 都放在 <strong>HBM</strong>（高頻寬記憶體）中。HBM 是把多層 DRAM 晶片堆疊起來、透過矽中介層緊貼著 GPU 晶片，提供每秒數 TB 的頻寬——比一般電腦的 DDR5 記憶體快數十倍。"),
   ("p", u"但即使如此，HBM 和晶片上的 SRAM 相比仍然很慢。每次運算都要把資料從 HBM 搬到 SRAM、暫存器，算完再寫回。一個經驗法則是：<strong>搬一個位元組的能量和時間，遠超過對它做一次運算</strong>。"),
   ("p", u"這解釋了很多最佳化技術的共同邏輯："),
   ("ul", [u"<strong>FlashAttention</strong>：在 SRAM 裡把注意力算完，不把中間結果寫回 HBM",
           u"<strong>Kernel 融合</strong>：把多個小運算合成一個 kernel，資料只讀寫一次",
           u"<strong>量化</strong>：讓要搬的位元組變少",
           u"<strong>Batching</strong>：讓搬來的每個位元組被用更多次"]),
   ("p", u"HBM 的容量也是推論的硬限制：H100 80 GB、H200 141 GB、B200 與 MI300X 192 GB。模型權重加上 KV Cache 必須放得下，否則就要用多張卡。"),
  ],
  u"GPU 記憶體從暫存器、SRAM、L2 到 HBM 越來越大越慢；權重與 KV Cache 放在 HBM，搬資料比運算昂貴；FlashAttention、融合、量化與 batching 都在減少或攤提搬運。",
  [u"HBM 為什麼比一般記憶體快？",
   u"為什麼說搬資料比運算貴？",
   u"舉兩個減少資料搬運的最佳化。"]),

lesson(u"多卡平行",
  u"張量、管線與專家平行",
  [u"理解為什麼需要多卡",
   u"認識三種平行方式",
   u"了解它們的通訊需求"],
  [("p", u"一張 H100 只有 80 GB，放不下 BF16 的 70B 模型（140 GB），更不用說 671B 的 DeepSeek-V3。而且即使放得下，多張卡的總頻寬也能讓 decode 更快。"),
   fig(_PAR, 236, u"三種平行方式。"),
   ("ul", [u"<strong>張量平行（TP）</strong>：Megatron-LM 的做法，把每個矩陣按行或列切開。每一層都需要一到兩次 all-reduce 同步，通訊量大且頻繁，所以只適合在 NVLink 相連的同一台機器內（通常 2～8 卡）",
           u"<strong>管線平行（PP）</strong>：第 1～20 層在卡 1、第 21～40 層在卡 2……每個 token 依序穿過。通訊只發生在段落邊界，可以跨機器，但單一請求的延遲不會降低",
           u"<strong>專家平行（EP）</strong>：MoE 的專家分散到不同卡上，需要 all-to-all 通訊",
           u"<strong>資料平行（DP）</strong>：每組 GPU 放一份完整模型，各自服務不同請求——最簡單的擴充方式"]),
   ("p", u"實際部署往往是組合：例如 70B 模型在一台 8 卡機器內用 TP=4 或 TP=8，再用多台機器做資料平行；超大的 MoE 模型則用 EP 跨數十張卡，注意力部分再搭配 TP 或 DP。選擇平行策略，就是在延遲、吞吐量與通訊成本之間找平衡。"),
  ],
  u"模型放不下或需要更多頻寬時用多卡：張量平行切矩陣、每層同步、限機器內；管線平行切層、可跨機；專家平行分散 MoE 專家；資料平行複製模型。",
  [u"張量平行為什麼通常限於同一台機器內？",
   u"管線平行能降低單一請求的延遲嗎？",
   u"什麼是資料平行？"]),

lesson(u"互連",
  u"NVLink、InfiniBand 與網路",
  [u"認識 GPU 之間的互連",
   u"理解頻寬對平行策略的影響",
   u"了解叢集網路的角色"],
  [("p", u"多卡平行的效率取決於卡與卡之間的通訊速度。"),
   ("t", [u"互連", u"範圍", u"頻寬（數量級）"],
         [[u"PCIe 5.0 x16", u"GPU 與 CPU、一般擴充", u"約 64 GB/s 單向"], [u"NVLink（H100）", u"同一台機器內的 GPU", u"900 GB/s（雙向合計）"],
          [u"NVLink（Blackwell）", u"機器內，及 NVL72 機櫃內 72 張卡", u"1.8 TB/s"], [u"InfiniBand／RoCE", u"機器之間", u"每張卡 400～800 Gb/s（50～100 GB/s）"]]),
   ("p", u"可以看到機器內與機器間的頻寬差了一個數量級。這就是為什麼張量平行留在機器內，跨機器時改用通訊量較小的管線平行或資料平行。"),
   ("p", u"<strong>NVSwitch</strong> 讓同一台機器內的 8 張 GPU 兩兩以全速互連。Blackwell 世代的 <strong>NVL72</strong> 把 72 張 GPU 以 NVLink 連成一個大型的共享網域，讓超大 MoE 模型的專家平行能在高速網路中進行。AMD 的 Infinity Fabric、Google TPU 的 ICI 也扮演類似的角色。"),
   ("p", u"對推論來說，互連還有一個重要用途：在分離部署中傳送 KV Cache，以及在多台機器之間共享 prefix cache。這些都需要 RDMA（遠端直接記憶體存取），讓資料不經過 CPU 直接在 GPU 記憶體之間搬運。"),
  ],
  u"機器內 NVLink 每卡約 900 GB/s，機器間 InfiniBand 每卡約 50～100 GB/s，差一個數量級；因此 TP 留在機器內，跨機用 PP、DP；RDMA 支援 KV Cache 傳輸。",
  [u"NVLink 和 InfiniBand 的頻寬差多少？",
   u"這個差距如何影響平行策略？",
   u"NVL72 有什麼特別之處？"]),

lesson(u"TPU 與其他加速器",
  u"GPU 之外的選擇",
  [u"認識主要的 AI 加速器",
   u"理解它們的設計取向",
   u"理解推論原理的普遍性"],
  [("p", u"NVIDIA GPU 是目前最普遍的推論硬體，但並非唯一："),
   ("t", [u"加速器", u"特色"],
         [[u"AMD Instinct（MI300X 等）", u"GPU 架構，192 GB HBM、5.3 TB/s，大記憶體適合大模型推論；以 ROCm 軟體堆疊支援 vLLM 等框架"],
          [u"Google TPU", u"以脈動陣列（systolic array）為核心的矩陣運算專用晶片，透過 ICI 互連組成大型 pod，Google 的 Gemini 在 TPU 上訓練與服務"],
          [u"AWS Trainium／Inferentia", u"雲端自研晶片，以 Neuron SDK 支援"], [u"Groq LPU", u"大量晶片上 SRAM、無 HBM，以許多晶片放一個模型，追求極低的單一請求延遲"],
          [u"Cerebras WSE", u"整片晶圓大小的晶片，數十 GB 的晶片上 SRAM，頻寬極高"], [u"手機與筆電 NPU", u"Apple Neural Engine、高通 Hexagon 等，用於裝置上的小模型"]]),
   ("p", u"無論硬體怎麼設計，這門課的原理都適用：<strong>prefill 需要算力、decode 需要頻寬，KV Cache 需要記憶體</strong>。不同硬體只是在這三者之間做不同的取捨。例如 Groq 與 Cerebras 用昂貴的 SRAM 換取極高的頻寬，所以單一請求的 decode 速度可以非常快；但 SRAM 容量有限，需要很多晶片才能放下大模型。"),
   ("p", u"軟體生態是另一個關鍵：CUDA 經過近二十年的累積，大部分推論最佳化都先在 NVIDIA 上實作。其他平台正透過 Triton、ROCm、XLA／JAX 等工具縮小差距。"),
  ],
  u"除 NVIDIA GPU 外還有 AMD Instinct、Google TPU、雲端自研晶片、Groq、Cerebras 與裝置 NPU；它們都在算力、頻寬、記憶體之間做不同取捨，推論原理相同。",
  [u"TPU 的核心運算結構是什麼？",
   u"Groq 和 Cerebras 為什麼 decode 可以很快？",
   u"為什麼說這門課的原理適用所有硬體？"]),
]),

(u"模組 H｜系統與實務", [

lesson(u"排程：延遲與吞吐量的取捨",
  u"推論伺服器怎麼決定先做誰",
  [u"理解推論排程的目標",
   u"認識常見的排程策略",
   u"理解 SLO 的概念"],
  [("p", u"推論伺服器像一間餐廳的廚房：請求不斷湧入，GPU 是有限的爐子。排程器每一步都要決定：這一步要做哪些請求的 decode？要不要開始新請求的 prefill？記憶體不夠時要暫停誰？"),
   ("p", u"這是一個典型的排隊問題（參考 " + XL("qt") + u"）：當到達率接近服務能力，排隊時間會急速上升，TTFT 跟著爆炸。"),
   ("ul", [u"<strong>先到先服務（FCFS）</strong>：最簡單、最公平，但長請求可能擋住短請求",
           u"<strong>Prefill 優先</strong>：新請求盡快開始，TTFT 低，但 decode 會被打斷",
           u"<strong>Decode 優先</strong>：正在生成的請求不中斷，TPOT 穩定，但新請求要等",
           u"<strong>搶佔（preemption）</strong>：記憶體不夠時暫停某些請求，把它的 KV Cache 換出到 CPU 記憶體或直接丟棄、之後重算"]),
   ("p", u"實際的服務通常訂有 <strong>SLO</strong>（服務水準目標），例如「99% 的請求 TTFT 小於 1 秒、TPOT 小於 50 毫秒」。在滿足 SLO 的前提下吞吐量能做到多高，稱為 <strong>goodput</strong>——這是比單純吞吐量更有意義的指標。"),
   ("p", u"此外，大規模服務還要在多台伺服器之間做<strong>路由</strong>：把同一段對話送到持有它 prefix cache 的機器（快取親和性），同時避免某些機器過載。"),
  ],
  u"推論排程決定每步做哪些 decode、何時 prefill、記憶體不足時搶佔誰；策略在 TTFT 與 TPOT 間取捨，以 SLO 為目標、goodput 衡量；跨機路由兼顧快取親和與負載平衡。",
  [u"為什麼負載接近容量時 TTFT 會急速上升？",
   u"Prefill 優先和 decode 優先各有什麼取捨？",
   u"什麼是 goodput？"]),

lesson(u"成本結構",
  u"為什麼輸出 token 比較貴",
  [u"理解推論成本的組成",
   u"理解輸入與輸出 token 的成本差異",
   u"了解影響成本的因素"],
  [("p", u"推論服務的成本，本質上是 <strong>GPU 時間</strong>（硬體折舊、電力、機房）除以產出的 token 數。從前面學到的原理，可以理解許多 API 的定價結構："),
   ("ul", [u"<strong>輸出 token 比輸入 token 貴</strong>（常見數倍）：輸入在 prefill 中平行處理、充分使用算力；輸出要一步一步 decode，每一步都要讀整個模型，GPU 的算力大部分閒置",
           u"<strong>快取命中的輸入比較便宜</strong>：prefix cache 讓這些 token 不必重新 prefill",
           u"<strong>長上下文可能更貴</strong>：KV Cache 佔用記憶體、降低 batch 大小，注意力計算也更多",
           u"<strong>批次 API 比較便宜</strong>：不要求即時回應，伺服器可以在空閒時以大 batch 處理，把吞吐量拉到最高",
           u"<strong>小模型便宜很多</strong>：參數少，讀得快、算得快、需要的卡也少"]),
   ("p", u"從系統的角度，降低成本就是提高<strong>每張 GPU 每秒產出的 token 數</strong>。這門課提到的所有技術——batching、PagedAttention、量化、推測解碼、prefix cache、MoE、分離部署——最終都反映在這個數字上。過去幾年，同等能力模型的推論價格下降了一到兩個數量級，硬體進步與這些軟體最佳化都功不可沒。"),
   ("note", u"推理模型的成本", [("p", u"會先「思考」再回答的推理模型，可能在給出答案前生成數千到數萬個思考 token。這些都是 decode，讓輸出 token 的比例大增，也讓 decode 效率變得更加關鍵。")]),
  ],
  u"推論成本是 GPU 時間除以 token 數；輸出 token 需逐步 decode、算力閒置所以較貴，快取命中與批次 API 較便宜；所有最佳化最終都在提升每 GPU 每秒 token 數。",
  [u"為什麼輸出 token 比輸入 token 貴？",
   u"批次 API 為什麼可以比較便宜？",
   u"推理模型為什麼讓 decode 效率更重要？"]),

lesson(u"怎麼測推論效能",
  u"Benchmark 的陷阱",
  [u"認識推論 benchmark 的主要指標",
   u"理解測試條件的影響",
   u"學會判讀效能數字"],
  [("p", u"「這個引擎每秒能跑 10,000 個 token！」——這樣的數字在沒有條件的情況下幾乎沒有意義。推論效能高度取決於測試條件："),
   ("t", [u"條件", u"影響"],
         [[u"輸入／輸出長度", u"長輸入考驗 prefill，長輸出考驗 decode；兩者的比例決定結果"], [u"並發數或請求速率", u"並發越高吞吐量越高，但每人延遲越長"],
          [u"模型與精度", u"BF16 和 FP8、4-bit 的速度差很多"], [u"硬體與卡數", u"不同 GPU、不同平行策略"],
          [u"是否命中 prefix cache", u"重複的 prompt 會讓 TTFT 看起來極快"], [u"抽樣與輸出長度控制", u"是否固定輸出長度、是否忽略結束 token"]]),
   ("p", u"可靠的 benchmark 應該："),
   ("ul", [u"報告<strong>延遲的分布</strong>（P50、P90、P99），而不只是平均",
           u"畫出<strong>吞吐量對延遲</strong>的曲線：在不同負載下各量一次，看在某個延遲目標下能達到多少吞吐量",
           u"使用接近真實流量的資料集（例如真實對話的長度分布）",
           u"說明所有測試條件，並與相同條件下的基準比較"]),
   ("p", u"常用的工具包括各推論框架附帶的 benchmark 腳本、MLPerf Inference 等產業基準。對使用者來說，最實際的方法是用<strong>自己的實際工作負載</strong>來測——別人的數字只能當參考。"),
  ],
  u"推論效能高度取決於輸入輸出長度、並發、精度、硬體與快取命中；可靠的 benchmark 報告延遲分布、畫吞吐量對延遲曲線、用真實流量並說明條件。",
  [u"為什麼單一的 token/s 數字沒有意義？",
   u"為什麼要看 P99 延遲？",
   u"什麼是吞吐量對延遲曲線？"]),

lesson(u"本地推論",
  u"在自己的電腦上跑模型",
  [u"認識本地推論的工具",
   u"用本課原理估算本地速度",
   u"了解本地推論的取捨"],
  [("p", u"不需要資料中心，一台筆電或桌機也能跑 LLM。代表性的工具有："),
   ("ul", [u"<strong>llama.cpp</strong>：以 C/C++ 撰寫的推論引擎，支援 CPU、Apple Silicon、NVIDIA、AMD 等多種硬體，使用 GGUF 量化格式",
           u"<strong>Ollama</strong>、<strong>LM Studio</strong>：建立在 llama.cpp 等引擎上的易用介面，一行指令下載並執行模型",
           u"<strong>MLX</strong>：Apple 為 Apple Silicon 設計的陣列框架",
           u"<strong>vLLM、SGLang</strong>：也可以在單張消費級 GPU 上執行，適合要服務多人的情境"]),
   ("p", u"本地推論完全適用這門課的原理："),
   ("t", [u"硬體", u"記憶體頻寬", u"8B 4-bit（約 4.5 GB）decode 上限"],
         [[u"雙通道 DDR5 桌機（CPU）", u"約 80 GB/s", u"約 18 tok/s"], [u"Apple M 系列 Max 晶片", u"約 400～550 GB/s", u"約 90～120 tok/s"],
          [u"RTX 4090", u"約 1 TB/s", u"約 220 tok/s"]]),
   ("p", u"所以本地推論的關鍵是<strong>記憶體頻寬與容量</strong>：統一記憶體的 Apple Silicon 可以把很大的模型放進記憶體；獨立 GPU 頻寬高但 VRAM 有限（24 GB 左右），模型放不下時部分層放到 CPU，速度會大幅下降。"),
   ("p", u"本地推論通常只服務一個人，batch = 1，正好是最受頻寬限制的情境。好處是隱私、離線可用、沒有按 token 計費；代價是只能跑較小或量化較多的模型，prefill 長文件也比資料中心慢得多（因為算力小）。"),
  ],
  u"llama.cpp、Ollama、MLX 等讓 LLM 在個人電腦上執行；batch 為 1 時速度約為頻寬除以模型大小，關鍵是記憶體頻寬與容量；好處是隱私與離線，代價是模型較小。",
  [u"為什麼 CPU 跑 LLM 比 GPU 慢很多？",
   u"Apple Silicon 在本地推論上有什麼優勢？",
   u"本地推論的 prefill 為什麼比較慢？"]),

lesson(u"總結：一次推論的全貌",
  u"把所有概念串起來",
  [u"回顧一次請求的完整流程",
   u"整理 prefill 與 decode 的對比",
   u"建立推論最佳化的地圖"],
  [("p", u"再走一次那趟旅程，這次帶著所有學過的概念："),
   ("ol", [u"請求進入佇列，排程器依 SLO 決定何時開始（第 40 課）",
           u"文字依 chat template 組合、tokenize 成 token ID（第 5、6 課）",
           u"檢查 prefix cache，跳過已經算過的前綴（第 30 課）",
           u"Prefill：剩餘的 token 以矩陣乘矩陣的方式穿過所有層，FlashAttention 計算注意力，KV Cache 寫入分頁的區塊中；長輸入可能被切段（第 16～20 課）",
           u"抽樣出第一個 token，送回使用者——TTFT 結束（第 25 課）",
           u"Decode 迴圈：與其他請求組成 batch，每一步讀一次權重與各自的 KV Cache，生成一個 token；可能有推測解碼一次多生幾個（第 21～32 課）",
           u"遇到結束 token 或長度上限，釋放 KV Cache（第 26 課）"]),
   ("t", [u"", u"Prefill", u"Decode"],
         [[u"處理", u"整段輸入一起", u"一次一個 token"], [u"運算形式", u"矩陣 × 矩陣", u"矩陣 × 向量（batch 後變小矩陣）"],
          [u"算術強度", u"≈ 輸入 token 數", u"≈ batch 大小"], [u"瓶頸", u"算力", u"記憶體頻寬、KV Cache 容量"],
          [u"決定的指標", u"TTFT", u"TPOT"], [u"主要最佳化", u"FlashAttention、chunked prefill、prefix cache", u"batching、PagedAttention、量化、推測解碼、GQA／MLA"]]),
   ("p", u"記住一句話：<strong>prefill 是算力問題，decode 是頻寬問題，KV Cache 是記憶體問題</strong>。幾乎所有推論的新技術，都可以放進這三個問題中的一個來理解。"),
   ("p", u"想了解模型本身是怎麼訓練出來的，可以接著讀 " + u'<a href="../llm-models/index.html">〈大型語言模型〉</a>' + u"；想深入排隊與排程，可以讀 " + XL("qt") + u"。"),
  ],
  u"一次推論經過排程、tokenize、prefix cache、prefill、抽樣、batch decode 與釋放快取；prefill 是算力問題、decode 是頻寬問題、KV Cache 是記憶體問題。",
  [u"按順序說出一次請求經過的步驟。",
   u"比較 prefill 與 decode 的算術強度與瓶頸。",
   u"把推測解碼、量化、PagedAttention 分別歸到三個問題中的哪一個。"]),
]),
]
