# -*- coding: utf-8 -*-
"""親手訓練一個小 LLM：模組 A～D（第 1～24 課）。"""
from ng_common import *

lesson = nglesson

_GOAL = svg(
    title(u"這門課要做的事"),
    flow([(u"下載唐詩", u"3.6 萬首"), (u"Tokenizer", u"字 → 數字"), (u"寫出 GPT", u"約 200 行"), (u"訓練", u"CPU 約 20 分鐘"), (u"寫詩", u"抽樣生成"), (u"微調", u"LoRA 聽指令")], 60, 56),
    T(320, 150, u"每一步都附可以直接執行的程式碼與實際輸出", 10.5, ACC),
)

_FILES = svg(
    title(u"範例檔案"),
    box(20, 40, 190, 130, u"核心程式", [u"prepare_data.py：下載語料", u"tokenizer.py：切字", u"gpt.py：模型", u"train.py：訓練"], BLUE),
    box(225, 40, 190, 130, u"使用模型", [u"sample.py：寫詩", u"chat.py：互動", u"lora.py：微調"], GREEN),
    box(430, 40, 190, 130, u"各課小實驗", [u"s01～s14：", u"每課一支", u"可以單獨執行"], ORANGE),
)

_NEXT = svg(
    title(u"訓練資料：答案就是往右移一格"),
    [R(40 + i * 64, 50, 56, 36, BLUE, "rgba(58,110,165,0.12)") for i in range(8)], [T(68 + i * 64, 74, c, 14, BLUE) for i, c in enumerate(u"床前明月光，疑是")],
    [R(40 + i * 64, 120, 56, 36, GREEN, "rgba(74,154,94,0.12)") for i in range(8)], [T(68 + i * 64, 144, c, 14, GREEN) for i, c in enumerate(u"前明月光，疑是地")],
    [A(68 + i * 64, 88, 68 + i * 64, 118, MUTED, 1.2) for i in range(8)],
    T(20, 72, u"x", 12, BLUE, "start"), T(20, 142, u"y", 12, GREEN, "start"),
    T(320, 186, u"一段 8 個字的文字 ＝ 8 道「看前面、猜下一個」的題目", 10.5, ACC),
)

_EMB = svg(
    title(u"Token embedding ＋ 位置 embedding"),
    box(30, 50, 160, 40, u"token id：2214（月）", None, BLUE), A(190, 70, 240, 70, MUTED),
    box(240, 40, 170, 60, u"查表：第 2214 列", [u"192 個數字"], BLUE),
    box(30, 130, 160, 40, u"位置：第 3 個字", None, PURPLE), A(190, 150, 240, 150, MUTED),
    box(240, 120, 170, 60, u"查表：第 3 列", [u"192 個數字"], PURPLE),
    C(470, 110, 16, ACC), T(470, 115, u"＋", 14, ACC), A(410, 70, 456, 102, MUTED), A(410, 150, 456, 118, MUTED),
    A(486, 110, 530, 110, MUTED), box(530, 85, 90, 50, u"輸入向量", [u"192 維"], GREEN),
)

_BLOCK = svg(
    title(u"一個 Block（Pre-LN）"),
    box(230, 200, 180, 28, u"x", None, GRAY),
    box(230, 150, 180, 32, u"LayerNorm → 注意力", None, BLUE), box(230, 96, 180, 32, u"LayerNorm → MLP", None, ORANGE), box(230, 44, 180, 28, u"輸出", None, GRAY),
    C(450, 134, 10, GREEN), T(450, 138, u"＋", 12, GREEN), C(450, 80, 10, GREEN), T(450, 84, u"＋", 12, GREEN),
    A(320, 200, 320, 184, MUTED), A(410, 166, 444, 140, MUTED), A(450, 124, 410, 116, MUTED), A(410, 112, 444, 86, MUTED), A(450, 70, 410, 60, MUTED),
    P("M230 214 L190 214 L190 134 L440 134", PURPLE, sw=1.3, dash="4 3"), P("M320 128 L320 135", LINE), T(184, 176, u"殘差", 9.5, PURPLE, "end"),
    T(540, 110, u"x ＝ x ＋ attn(ln1(x))", 10, ACC, "middle"), T(540, 128, u"x ＝ x ＋ mlp(ln2(x))", 10, ACC, "middle"),
)

MODULE_A = (u"模組 A｜準備", [

lesson(u"這門課要做出什麼",
  u"一個會寫唐詩的 GPT",
  [u"知道整門課的目標與流程", u"看到最後做出來的成果", u"了解需要的背景知識"],
  [("fig", _GOAL, "0 0 640 170", u"從下載資料到微調，整門課的流程。"),
   ("p", u"這門課要從零開始，用 Python 和 PyTorch 一行一行寫出一個 GPT，讓它讀完 3.6 萬首唐詩之後學會寫詩。整個模型約 300 萬個參數，<strong>一般筆電的 CPU 就能訓練</strong>，不需要 GPU。"),
   ("p", u"這是本課程訓練好的模型寫的詩（給它一個開頭的字，它自己接下去）："),
  ] + output("sample") + [
   ("p", u"它當然不懂詩的意思，常常前後不連貫，但已經學會了五言、七言的格式、對仗的節奏和唐詩常用的字詞。這些全部都是從資料裡「猜下一個字」學出來的，沒有人教它任何規則。"),
   ("h", u"你需要的背景"),
   ("ul", [u"會基本的 Python（變數、函式、迴圈、類別）。", u"知道神經網路、梯度下降、注意力機制的概念——不熟的話可以先看 <a href=\"../deep-learning/index.html\">〈神經網路與深度學習〉</a>。",
           u"不需要 GPU；有 NVIDIA 顯示卡或 Apple M 系列晶片會快很多。"]),
   ("fig", _FILES, "0 0 640 190", u"所有範例檔都可以在每課下載，或在課程首頁的參考頁下載整包。"),
  ],
  u"這門課從零寫一個約 300 萬參數的 GPT，用 3.6 萬首唐詩在 CPU 上訓練，讓它學會寫詩，最後再用 LoRA 微調讓它聽懂指令。每一步都附可執行的程式與實際輸出。",
  [u"這門課的模型用什麼資料訓練？", u"模型大約有多少參數？需要 GPU 嗎？", u"模型學會寫詩靠的是什麼訓練目標？"]),

lesson(u"環境：Python、PyTorch、GPU／Mac／CPU",
  u"把工具裝起來",
  [u"安裝 Python 與 PyTorch", u"知道 CPU、CUDA、MPS 三種裝置", u"下載並整理唐詩語料"],
  [("h", u"安裝"),
   ("code", u"# 1. 安裝 Python 3.9 以上（python.org 或 Anaconda）\n# 2. 建立虛擬環境（建議）\npython -m venv llm\nsource llm/bin/activate          # Windows：llm\\Scripts\\activate\n\n# 3. 安裝 PyTorch：到 pytorch.org 依作業系統與顯示卡選擇指令，例如\npip install torch"),
   ("h", u"三種裝置"),
   ("t", [u"裝置", u"PyTorch 名稱", u"說明"], [[u"NVIDIA 顯示卡", u"cuda", u"最快，訓練本課模型約幾分鐘"], [u"Apple M 系列", u"mps", u"比 CPU 快數倍"], [u"一般 CPU", u"cpu", u"本課程的實測環境，4 核心約 20 分鐘"]]),
   ("p", u"本課程的程式會自動選擇："),
   src("train", "device = "),
   ("h", u"下載唐詩"),
  ] + ex("prepare_data", u"語料來自 GitHub 上的開源專案 chinese-poetry（MIT 授權）收錄的《全唐詩》。我們只留下格式工整的五言、七言絕句與律詩，方便模型學習。") + [
   ("note", u"為什麼要過濾？", [("p", u"原始資料裡有缺字符號、註解、長短不一的古體詩。先把資料整理乾淨，模型學得快很多——「垃圾進，垃圾出」在 LLM 訓練裡同樣成立，真實的 LLM 團隊會花大量心力在資料清洗上。")]),
  ],
  u"安裝 Python 與 PyTorch，程式會自動選擇 cuda、mps 或 cpu。prepare_data.py 從 chinese-poetry 下載《全唐詩》，只留下格式工整的五言、七言絕句律詩，共約 3.6 萬首。",
  [u"PyTorch 在 Mac 上用哪個裝置名稱？", u"我們過濾掉了哪些詩？為什麼？", u"整理後的語料約有多少字？"]),

lesson(u"PyTorch 速成：tensor 與 autograd",
  u"兩個你一定要會的東西",
  [u"會建立和操作 tensor", u"看懂 tensor 的形狀", u"理解自動微分"],
  [("p", u"PyTorch 的核心只有兩樣：<strong>tensor</strong>（多維陣列，可以放在 GPU 上算）和 <strong>autograd</strong>（自動算梯度）。"),
  ] + ex("s01_tensor") + [
   ("h", u"形狀是最重要的事"),
   ("p", u"寫 Transformer 時，最常見的張量形狀是 <code>(B, T, C)</code>：B 段文字（batch）、每段 T 個 token、每個 token C 維。注意力會再多一個頭的維度 <code>(B, H, T, hd)</code>。寫程式時隨時印出 <code>x.shape</code>，可以省下很多除錯時間。"),
   ("h", u"autograd"),
   ("p", u"設定 <code>requires_grad=True</code> 的張量，PyTorch 會記錄所有對它的運算。呼叫 <code>loss.backward()</code> 後，每個參數的 <code>.grad</code> 就是損失對它的偏導數——反向傳播完全自動。"),
  ],
  u"PyTorch 的兩個核心是 tensor 和 autograd。Transformer 裡最常見的形狀是 (B, T, C)；設定 requires_grad 後呼叫 backward()，就能自動得到每個參數的梯度。",
  [u"(32, 80, 192) 這個形狀分別代表什麼？", u"loss.backward() 之後梯度存在哪裡？", u"矩陣乘法和逐元素相乘的運算子分別是什麼？"]),

lesson(u"nn.Module 與訓練迴圈",
  u"所有模型的骨架",
  [u"會寫一個 nn.Module", u"記住訓練迴圈的五個步驟", u"知道 optimizer 在做什麼"],
  [("p", u"PyTorch 的模型都繼承 <code>nn.Module</code>：在 <code>__init__</code> 裡建立參數和子模組，在 <code>forward</code> 裡寫計算。我們先用最簡單的直線練習。"),
  ] + ex("s02_module") + [
   ("h", u"訓練迴圈五步驟"),
   ("ol", [u"前向：<code>pred = model(x)</code>", u"損失：<code>loss = ...</code>", u"清梯度：<code>opt.zero_grad()</code>（PyTorch 的梯度預設會累加）", u"反向：<code>loss.backward()</code>", u"更新：<code>opt.step()</code>"]),
   ("p", u"20 步之後 w 和 b 就很接近 2 和 1 了。我們的 GPT 只是把「一條直線」換成「300 萬個參數的 Transformer」、把 MSE 換成交叉熵，迴圈完全一樣。"),
  ],
  u"模型繼承 nn.Module，在 forward 寫計算。訓練迴圈是前向、算損失、清梯度、反向、更新五步。從一條直線到 GPT，迴圈都一樣。",
  [u"為什麼每一步都要 zero_grad？", u"nn.Linear(1, 1) 裡有幾個參數？", u"把這個迴圈套用到 GPT，要換掉哪些部分？"]),

lesson(u"準備語料：下載、清理、切分",
  u"先認識你的資料",
  [u"統計語料的基本數字", u"知道字的分布非常不平均", u"了解訓練集與驗證集的切分"],
  [("p", u"訓練前先看看資料：有多少首詩、多少個不同的字、哪些字最常見。"),
  ] + ex("s03_data") + [
   ("h", u"觀察"),
   ("ul", [u"約 6,750 個不同的字，但前幾百個常用字就佔了大部分。這種「少數很常見、多數很罕見」的分布叫<strong>長尾分布</strong>。",
           u"有一千多個字只出現一次——模型幾乎不可能學會它們。",
           u"五言律詩最多，五言絕句最少。模型寫出來的詩，也會偏向資料裡比較多的體裁。"]),
   ("h", u"切分"),
   ("p", u"我們把整份文字的前 95% 當訓練集、後 5% 當驗證集。驗證集模型從沒看過，用來檢查它是真的學會寫詩，還是只是背下訓練資料。"),
   src("train", "# ---- 資料", "train_data, val_data"),
  ],
  u"語料約 3.6 萬首、162 萬字、6,750 個不同的字，字頻是長尾分布。前 95% 當訓練集、後 5% 當驗證集，用來檢查模型是否真的學會而不是背誦。",
  [u"什麼是長尾分布？", u"只出現一次的字，模型為什麼學不會？", u"驗證集的用途是什麼？"]),
])

MODULE_B = (u"模組 B｜Tokenizer", [

lesson(u"字元級 tokenizer",
  u"最簡單的開始",
  [u"理解 tokenizer 的工作", u"實作字元級 tokenizer", u"知道 encode 與 decode"],
  [("p", u"神經網路只吃數字。<strong>Tokenizer</strong> 負責把文字切成一個個 token，再對應成整數 id（encode），以及反過來（decode）。最簡單的做法：<strong>每個字就是一個 token</strong>。"),
   src("tokenizer", "class CharTokenizer", "return cls(chars)"),
  ] + ex("s04_char_tok", show_src=True) + [
   ("p", u"詞彙表依字的 Unicode 順序排列，所以換行（\\n）是 0 號。我們把換行當成「一首詩結束」的記號：模型生成到換行，就代表這首詩寫完了。"),
   ("note", u"中文很適合字元級", [("p", u"英文只有 26 個字母，用字母當 token 序列會太長；中文一個字本身就有意義，常用字也只有幾千個，字元級 tokenizer 對唐詩來說很合理。")]),
  ],
  u"Tokenizer 把文字切成 token 並對應成整數。字元級 tokenizer 讓每個字一個 token，詞彙量約 6,758；換行代表一首詩結束。中文因為單字有意義，很適合字元級。",
  [u"encode 和 decode 分別做什麼？", u"我們的詞彙量是多少？", u"為什麼英文通常不用字母級 tokenizer？"]),

lesson(u"從頭實作 BPE",
  u"GPT 用的切字法",
  [u"理解 BPE 的演算法", u"親手跑 BPE 的合併過程", u"看懂 BPETokenizer 的程式"],
  [("p", u"GPT、Llama、Claude 都用 <strong>BPE（Byte Pair Encoding）</strong> 或它的變形。演算法很簡單："),
   ("ol", [u"從最小的單位開始（GPT 系列是 256 個位元組）。", u"數出所有相鄰兩個 token 的組合，找出<strong>最常出現的一對</strong>。", u"把這一對合併成一個新 token，加進詞彙表。", u"重複，直到詞彙表達到想要的大小（例如 5 萬、10 萬）。"]),
   ngw({"t": "bpe", "q": u"按「合併一次」看每一步合併了什麼；也可以把文字換成你自己的句子。"}),
   src("tokenizer", "    def train(cls, text, n_merges", "        return tok"),
   ("p", u"常見的組合會變成一個 token，罕見的字則保持拆開。這讓詞彙表大小可以控制，又能表示任何文字（最壞的情況就是一個位元組一個 token）。"),
  ],
  u"BPE 從位元組開始，反覆把最常相鄰出現的一對合併成新 token，直到詞彙表夠大。常見片段成為單一 token，罕見的保持拆開，所以任何文字都能表示。",
  [u"BPE 每一步合併的是哪一對？", u"GPT 的 BPE 從什麼單位開始？", u"為什麼 BPE 能表示任何文字？"]),

lesson(u"中文的 BPE 會遇到什麼",
  u"一個字三個位元組",
  [u"看懂位元組層級 BPE 在中文上的行為", u"理解壓縮率", u"知道為什麼中文常比英文花更多 token"],
  [("p", u"用唐詩訓練 400 次合併，看看前幾次合併了什麼："),
  ] + ex("s05_bpe") + [
   ("h", u"觀察"),
   ("ul", [u"中文字在 UTF-8 裡通常是 3 個位元組。最早的合併常是把常見的「前兩個位元組」黏起來（顯示成 ‹e5 a4›），因為很多中文字共用同樣的開頭位元組。",
           u"標點「，」「。」很快就成為完整的 token；接著還會出現跨字的組合，例如「，」加上下一個字的第一個位元組——BPE 只看頻率，不管字的邊界。", u"常見字（山、月、日）最後變成一個 token；罕見字還是 2～3 個 token。",
           u"在沒看過的詩上，BPE 用的 token 數約是字數的 1.5 倍，比字元級還多——因為我們只合併了 400 次，連常用字都還沒完全學完。"]),
   ("note", u"真實的 LLM", [("p", u"GPT-4 等模型的詞彙表有 10 萬到 20 萬個 token，常用中文字大多是一個 token，但在詞彙表以英文為主的模型上，同樣意思的中文常比英文花更多 token，費用和速度都受影響（見〈LLM 模型全解〉）。")]),
  ],
  u"位元組層級 BPE 會先合併中文字常見的位元組開頭，常用字最後變成單一 token、罕見字仍拆開。合併次數太少時，中文 token 數甚至比字數還多；真實模型用 10 萬以上的詞彙表。",
  [u"一個中文字在 UTF-8 裡通常佔幾個位元組？", u"為什麼 BPE 的 token 有時顯示成 ‹e5 a4› 這種樣子？", u"為什麼中文常比英文花更多 token？"]),

lesson(u"特殊 token 與編碼、解碼",
  u"告訴模型「開始」和「結束」",
  [u"知道特殊 token 的用途", u"理解我們用換行代表一首詩結束", u"處理不在詞彙表裡的字"],
  [("p", u"除了一般的字，tokenizer 通常還有幾個<strong>特殊 token</strong>："),
   ("t", [u"特殊 token", u"例子", u"用途"], [[u"文件結束", u"<code>&lt;|endoftext|&gt;</code>（GPT-2）", u"分隔不同文件，生成到這裡就停"], [u"對話角色", u"<code>&lt;|im_start|&gt;user</code>", u"標出誰在說話（chat template）"],
                                       [u"填充", u"<code>&lt;pad&gt;</code>", u"把不同長度的序列補成一樣長"]]),
   ("p", u"我們的設計很簡單："),
   src("tokenizer", "SPECIAL = "),
   ("ul", [u"<strong>換行</strong>：一首詩結束，同時也代表下一首詩的開始。所以生成時，我們會在提示前面先加一個換行，告訴模型「這是一首新詩的開頭」；生成到下一個換行就停。", u"<strong>〔 〕和空白</strong>：先保留，第 39 課做指令微調時，用來寫「〔七言絕句 春〕」這種指令。"]),
   ("h", u"沒看過的字"),
   ("p", u"字元級 tokenizer 遇到詞彙表沒有的字（例如「咖啡」）就無法編碼。chat.py 的做法是先把這些字濾掉。BPE 則沒有這個問題，最壞就拆成位元組——這是 BPE 成為主流的重要原因。"),
  ],
  u"特殊 token 用來標記文件結束、對話角色、填充。我們用換行代表一首詩結束，並預留〔〕給指令格式。字元級 tokenizer 無法處理沒看過的字，BPE 則可以拆成位元組。",
  [u"GPT-2 用什麼特殊 token 分隔文件？", u"我們的模型怎麼知道一首詩寫完了？", u"字元級 tokenizer 遇到沒看過的字會怎樣？"]),

lesson(u"實作：訓練自己的 tokenizer",
  u"tokenizer.py 完整程式",
  [u"看懂完整的 tokenizer.py", u"知道 tokenizer 要存檔、和模型一起使用", u"選擇本課程要用的 tokenizer"],
  [("p", u"兩種 tokenizer 的完整程式："),
  ] + ex("tokenizer", cmd=u"（由其他程式匯入使用）") + [
   ("h", u"Tokenizer 和模型綁在一起"),
   ("p", u"train.py 第一次執行時會建立字元級 tokenizer 並存成 <code>tokenizer.json</code>，之後的 sample.py、chat.py、lora.py 都讀同一份檔案。<strong>換了 tokenizer，模型就得重新訓練</strong>——因為 token id 對應的字全變了。"),
   ("h", u"本課程的選擇"),
   ("t", [u"", u"字元級", u"BPE（400 次合併）"], [[u"詞彙量", u"6,758", u"656"], [u"〈登鸛雀樓〉的 token 數", u"24", u"31"], [u"沒看過的字", u"無法處理", u"可以"], [u"實作難度", u"很簡單", u"較複雜"]]),
   ("p", u"唐詩的字都在詞彙表裡、序列也短，我們選<strong>字元級</strong>。如果要訓練處理一般文章的模型，應該改用 BPE，並把合併次數提高到數萬次。"),
  ],
  u"tokenizer.py 包含字元級與 BPE 兩種實作。Tokenizer 要存檔並與模型一起使用，換了就得重訓。唐詩語料短且字都在詞彙表內，所以本課程用字元級。",
  [u"為什麼換 tokenizer 就要重新訓練模型？", u"tokenizer.json 存了什麼？", u"什麼情況下應該改用 BPE？"]),
])

MODULE_C = (u"模組 C｜最小的語言模型", [

lesson(u"Bigram 模型：只看前一個字",
  u"最簡單的語言模型",
  [u"理解 bigram 模型", u"會用數次數的方法建立機率表", u"體驗 bigram 的生成"],
  [("p", u"最簡單的語言模型只看<strong>前一個字</strong>，預測下一個字。它就是一張 V × V 的表格：第 a 列第 b 行是「a 後面接 b」的機率。"),
   ngw({"t": "bigram", "q": u"輸入一個字，看它後面最常接什麼字（用 400 首唐詩統計）。"}),
   ("p", u"做法就是數次數：\\[P(b \\mid a) = \\frac{\\text{「ab」出現的次數}}{\\text{「a」出現的次數}}\\]"),
   src("s06_bigram", "# 1. 數次數", "print("),
   ("note", u"也可以用神經網路學", [("p", u"<code>nn.Embedding(V, V)</code> 就是一張 V × V 的可學習表格，用梯度下降和交叉熵訓練，最後學到的機率會和數次數幾乎一樣——只是慢很多（我們的表有 4,500 萬格）。GPT 的最後一層，本質上也是在輸出這樣一列機率。")]),
  ],
  u"Bigram 模型只看前一個字，是一張 V×V 的機率表，數「a 後面接 b」的次數再除以 a 的次數即可。用神經網路學會得到相同結果，GPT 也是輸出下一個字的機率。",
  [u"Bigram 的機率表有多大？", u"P(明 | 月) 要怎麼算？", u"用 nn.Embedding(V, V) 訓練 bigram 會得到什麼？"]),

lesson(u"損失與困惑度",
  u"怎麼量一個語言模型好不好",
  [u"理解語言模型的交叉熵損失", u"理解困惑度（perplexity）", u"知道平滑的作用"],
  [("p", u"語言模型的損失是：每個位置上，模型給「正確的下一個字」的機率取 −log，再平均。\\[L = -\\frac{1}{N}\\sum_i \\log P(\\text{正確的字}_i)\\]"),
   ("p", u"<strong>困惑度</strong> ＝ \\(e^{L}\\)，直覺意義是「模型平均在幾個字之間猶豫」。完全亂猜時困惑度等於詞彙量；完美的模型困惑度是 1。"),
  ] + output("s06_bigram", head=5) + [
   ("ul", [u"亂猜：困惑度 6,758。", u"Bigram 在訓練集上約 155，驗證集約 450——好很多，但仍然在幾百個字之間猶豫。",
           u"驗證集比訓練集差很多，因為驗證集裡有許多訓練集沒出現過的兩字組合。"]),
   ("h", u"平滑"),
   ("p", u"如果某個組合在訓練集從沒出現，機率就是 0，−log 0 是無限大。所以每一格都加上一個很小的數（我們用 0.03）再算機率，叫做<strong>平滑</strong>。神經網路語言模型的 softmax 永遠不會給出 0，天生就沒有這個問題。"),
  ],
  u"語言模型的損失是正確下一個字機率的 −log 平均，困惑度 e^L 代表平均在幾個字間猶豫。亂猜的困惑度等於詞彙量；bigram 在驗證集上約 450。平滑避免沒看過的組合機率為 0。",
  [u"困惑度 1 代表什麼？", u"為什麼驗證集的困惑度比訓練集高？", u"不做平滑會發生什麼問題？"]),

lesson(u"抽樣生成第一段文字",
  u"讓模型自己寫",
  [u"理解自回歸生成", u"會從機率分布抽樣", u"觀察 bigram 生成的品質"],
  [("p", u"生成的方法：給一個開頭的字，從它那一列的機率<strong>抽樣</strong>出下一個字，再用新的字繼續抽，直到抽到換行。每一步都把自己的輸出當成下一步的輸入，叫做<strong>自回歸生成</strong>——GPT 也是這樣生成的。"),
   src("s06_bigram", "def sample(start", "    return out"),
  ] + output("s06_bigram", tail=5) + [
   ("p", u"每兩個相鄰的字都還算通順（「月明」「山遠」「早晚」），但整句毫無意義，也不知道五言七言、什麼時候該斷句。因為它<strong>只記得前一個字</strong>。"),
   ("p", u"注意這裡用的是 <code>torch.multinomial</code> 按機率抽樣，而不是每次都選機率最高的字。如果每次都選最高，「月」後面永遠是「，」，很快就會陷入重複。第 32 課會詳細討論。"),
  ],
  u"自回歸生成每次依機率抽出下一個字，再把它當作下一步的輸入，GPT 也是這樣。Bigram 只記得前一個字，所以相鄰兩字通順，整句卻沒有意義也沒有格式。",
  [u"什麼是自回歸生成？", u"為什麼生成時用抽樣而不是每次選機率最高的字？", u"bigram 生成的詩有什麼問題？"]),

lesson(u"為什麼 bigram 不夠",
  u"需要看更遠",
  [u"理解 n-gram 的限制", u"知道為什麼不能直接加大 n", u"理解神經網路語言模型的優勢"],
  [("p", u"直覺的改進是看前兩個字（trigram）、前三個字……統稱 <strong>n-gram</strong>。但表格大小是 \\(V^n\\)："),
   ("t", [u"模型", u"看前面幾個字", u"表格格數（V＝6,758）"], [[u"bigram", u"1", u"約 4,600 萬"], [u"trigram", u"2", u"約 3,100 億"], [u"4-gram", u"3", u"約 2 京"]]),
   ("p", u"而且大多數格子在資料裡從沒出現過（bigram 就只有 0.87% 的格子出現過），根本估計不出機率。"),
   ("h", u"神經網路的解法"),
   ("ul", [u"<strong>共享知識</strong>：「春風」和「秋風」的 embedding 相近，學到一個，另一個也受益。表格做不到這一點。",
           u"<strong>參數不隨 n 爆炸</strong>：Transformer 看 80 個字還是 1000 個字，參數量幾乎一樣（只多了位置 embedding）。",
           u"<strong>注意力</strong>：直接決定要看前文的哪幾個字，而不是死記每一種組合。"]),
   ("p", u"接下來的模組，我們就一步一步把 bigram 升級成 Transformer。"),
  ],
  u"n-gram 的表格大小是 V^n，看前 3 個字就要 2 京格，而且大多數組合從沒出現過。神經網路透過 embedding 共享知識、參數不隨上下文長度爆炸，並用注意力選擇要看哪些字。",
  [u"trigram 的表格大約有多少格？", u"「春風」和「秋風」的例子說明神經網路的什麼優勢？", u"Transformer 看更長的上下文，參數會暴增嗎？"]),
])

MODULE_D = (u"模組 D｜一行一行寫 Transformer", [

lesson(u"Token embedding 與位置 embedding",
  u"把 id 變成向量",
  [u"理解 embedding 查表", u"理解為什麼需要位置資訊", u"看懂模型開頭的程式"],
  [("fig", _EMB, "0 0 640 190", u"每個 token 查表得到一個向量，再加上它所在位置的向量。"),
   ("p", u"<code>nn.Embedding(V, d)</code> 是一張 V 列、d 行的表。token id 是 2214，就取出第 2214 列——一個 d 維向量。這些數字一開始是隨機的，訓練時跟著其他參數一起學。"),
   ("p", u"注意力本身不知道順序，所以再加一張<strong>位置 embedding</strong> 表：第 0 個位置一個向量、第 1 個位置一個向量……把兩者相加，就是送進 Transformer 的輸入。"),
   src("gpt", "    def forward(self, idx, targets=None", "        x = self.drop(x)"),
   ("p", u"這是 GPT-2 的做法（學出來的絕對位置）。缺點是只能處理訓練時看過的長度（我們是 80）。第 35 課會換成現代 LLM 用的 RoPE。"),
  ],
  u"Token embedding 是一張 V×d 的表，用 token id 查出向量；位置 embedding 另一張表提供順序資訊，兩者相加後送進 Transformer。GPT-2 用學出來的絕對位置。",
  [u"nn.Embedding(6758, 192) 有多少個參數？", u"為什麼需要位置 embedding？", u"學出來的絕對位置 embedding 有什麼限制？"]),

lesson(u"單頭 self-attention",
  u"讓每個字去看其他字",
  [u"一步步算出注意力", u"理解 Q、K、V 的計算", u"看懂分數、softmax、加權平均"],
  [("p", u"每個 token 的向量 x 乘上三個矩陣，得到 Query、Key、Value。用 Q 和所有 K 做內積得到分數，除以 √d，softmax 變成權重，再用權重加總 V。"),
  ] + ex("s07_attention") + [
   ("p", u"整個注意力只有三個矩陣乘法和一個 softmax，全部可以平行計算——這就是 Transformer 在 GPU 上這麼快的原因。"),
  ],
  u"單頭注意力把 x 乘上 W_Q、W_K、W_V 得到 Q、K、V，計算 QKᵀ/√d 的分數、softmax 成權重，再加權平均 V。全部是矩陣運算，可以平行計算。",
  [u"Q、K、V 是怎麼從 x 算出來的？", u"注意力分數為什麼要除以 √d？", u"softmax 之後每一列的權重加起來是多少？"]),

lesson(u"因果遮罩",
  u"不准偷看答案",
  [u"理解因果遮罩的作用", u"理解一段文字等於很多道題目", u"看懂 masked_fill 的寫法"],
  [("fig", _NEXT, "0 0 640 200", u"訓練資料的答案就是輸入往右移一格。"),
   ("p", u"訓練時，我們一次給模型 80 個字，要它在<strong>每個位置</strong>都猜下一個字。但第 3 個位置如果能看到第 4 個字，就可以直接抄答案。"),
   ngw({"t": "mask", "q": u"點選不同的列，看每個位置能看到哪些字；把遮罩關掉看看會怎樣。"}),
   ("p", u"做法：把「未來」位置的分數設成 −∞，softmax 之後權重就是 0。"),
   src("gpt", "        att = (q @ k.transpose", "        att = self.drop(F.softmax"),
   ("p", u"<code>self.mask</code> 是一個下三角矩陣（<code>torch.tril</code>），在建立模型時就先準備好。"),
  ],
  u"因果遮罩把未來位置的注意力分數設為 −∞，softmax 後權重為 0，讓每個位置只能看自己和前面的字。這樣一段 T 個字的文字就能同時當成 T 道猜下一個字的題目。",
  [u"沒有因果遮罩，模型會學到什麼？", u"遮罩矩陣是什麼形狀？", u"為什麼一段 80 字的文字可以變成 80 道題目？"]),

lesson(u"多頭注意力",
  u"同時看好幾種關係",
  [u"理解多頭注意力", u"看懂 view 與 transpose 的形狀轉換", u"理解輸出投影"],
  [("p", u"一個注意力頭只能學一種「看」法。<strong>多頭注意力</strong>把 d 維切成 H 份（我們是 4 頭 × 48 維），每個頭各自做注意力，最後接回 d 維、再經過一個線性層（輸出投影）。"),
   src("gpt", "class CausalSelfAttention", "        return self.drop(self.proj(y))"),
   ("h", u"形狀變化"),
   ("code", u"x                 (B, T, 192)\nqkv(x)            (B, T, 576)      一次算出 Q、K、V\nsplit             3 × (B, T, 192)\nview              (B, T, 4, 48)    切成 4 個頭\ntranspose(1, 2)   (B, 4, T, 48)    把「頭」移到前面，各頭平行計算\nq @ kᵀ            (B, 4, T, T)     每個頭一張注意力表\natt @ v           (B, 4, T, 48)\ntranspose + view  (B, T, 192)      接回來\nproj              (B, T, 192)"),
   ("p", u"一次用一個 <code>nn.Linear(d, 3d)</code> 算出 Q、K、V，比分三次快。KV cache 的部分（cache 參數）先跳過，第 33 課再講。"),
  ],
  u"多頭注意力把 d 維切成 H 個頭各自做注意力，再接回並經過輸出投影。用 view 和 transpose 在 (B, T, C) 與 (B, H, T, hd) 之間轉換，一次線性層同時算出 Q、K、V。",
  [u"我們的模型有幾個頭、每頭幾維？", u"transpose(1, 2) 的目的是什麼？", u"輸出投影 proj 的作用是什麼？"]),

lesson(u"FFN：每個字各自加工",
  u"參數的大頭",
  [u"理解前饋網路的結構", u"知道 4 倍擴張的慣例", u"理解注意力和 FFN 的分工"],
  [("p", u"注意力負責讓 token <strong>互相交換資訊</strong>；前饋網路（FFN，也叫 MLP）則對<strong>每個 token 各自</strong>做兩層全連接：先放大到 4 倍維度、經過 GELU、再縮回來。"),
   src("gpt", "class MLP", "        return self.drop(self.proj(F.gelu(self.fc(x))))"),
   ("p", u"一個 FFN 有 \\(2 \\times d \\times 4d = 8d^2\\) 個權重，是注意力（\\(4d^2\\)）的兩倍。研究發現，模型學到的很多「知識」（例如「巴黎是法國的首都」）似乎就儲存在 FFN 的權重裡。"),
   ("p", u"現代 LLM 把它換成 SwiGLU（第 36 課），程式裡的 <code>modern</code> 分支就是。"),
  ],
  u"FFN 對每個 token 各自做兩層全連接（d → 4d → d，中間 GELU），權重 8d² 是注意力的兩倍。注意力負責 token 間交流，FFN 負責各自加工，知識多半存在 FFN 裡。",
  [u"FFN 的中間層通常是幾倍寬？", u"FFN 和注意力的參數量比例大約是多少？", u"注意力和 FFN 的分工是什麼？"]),

lesson(u"殘差與 LayerNorm",
  u"讓深網路訓練得動",
  [u"理解殘差連接在 Transformer 中的寫法", u"理解 LayerNorm", u"知道 Pre-LN 與 Post-LN 的差別"],
  [("fig", _BLOCK, "0 0 640 240", u"每個子層的輸出加回輸入（殘差），子層前先做 LayerNorm（Pre-LN）。"),
   ("p", u"<strong>殘差連接</strong>：<code>x = x + attn(x)</code>，讓資訊和梯度可以繞過子層直接傳遞。整個模型可以想成一條「殘差流」，每一層都在上面加一點修正。"),
   ("p", u"<strong>LayerNorm</strong>：把每個 token 的向量調整成平均 0、標準差 1，再乘上可學的縮放。讓每一層的輸入保持穩定。"),
   ("h", u"Pre-LN 與 Post-LN"),
   ("t", [u"", u"Post-LN（原始 Transformer）", u"Pre-LN（GPT-2 之後）"], [[u"寫法", u"x = LN(x + f(x))", u"x = x + f(LN(x))"], [u"訓練穩定度", u"深了容易不穩、需要仔細 warmup", u"穩定，現在的主流"]]),
   ("p", u"Pre-LN 讓殘差流保持「乾淨」，梯度可以毫無阻礙地從最後一層流回第一層。所以最後還要在輸出前再做一次 LayerNorm（<code>ln_f</code>）。"),
  ],
  u"殘差連接 x = x + f(x) 讓資訊與梯度直通，形成殘差流；LayerNorm 穩定每層輸入。現代模型用 Pre-LN（先正規化再進子層），比原始的 Post-LN 穩定，輸出前再加一次 ln_f。",
  [u"殘差連接的寫法是什麼？", u"Pre-LN 和 Post-LN 的差別是什麼？", u"為什麼 Pre-LN 最後要多一個 ln_f？"]),

lesson(u"組成一個 Block",
  u"兩行程式",
  [u"看懂 Block 的完整程式", u"理解 Block 的輸入輸出形狀相同", u"知道為什麼可以一直疊"],
  [("p", u"把前面的零件組起來，一個 Block 的 forward 只有兩行："),
   src("gpt", "class Block", "        return x"),
   ("p", u"Block 的輸入和輸出形狀都是 (B, T, d)，所以可以像積木一樣疊起來。GPT-2 small 疊 12 層、GPT-3 疊 96 層、我們疊 4 層。"),
   ("note", u"一層 Block 的參數", [("p", u"注意力 4d²、FFN 8d²，再加上偏差和兩個 LayerNorm，約 \\(12d^2 + 13d\\)。我們 d = 192，一層約 44 萬個參數。")]),
  ],
  u"一個 Block 就是 x = x + attn(ln1(x)) 和 x = x + mlp(ln2(x)) 兩行。輸入輸出形狀相同，所以可以一直疊；一層約 12d² 個參數。",
  [u"Block 的 forward 有哪兩行？", u"為什麼 Block 可以一直疊？", u"d = 192 時，一層 Block 大約有多少參數？"]),

lesson(u"堆疊成 GPT",
  u"完整的模型",
  [u"看懂 GPT 類別", u"理解權重綁定", u"理解初始化與損失計算"],
  [src("gpt", "class GPT(nn.Module)", "        self.apply(self._init)"),
   ("p", u"（這裡節錄建構子，完整程式見第 24 課。）"),
   ("h", u"三個細節"),
   ("ul", [u"<strong>輸出層</strong>：最後的 <code>head</code> 把 d 維向量轉成 V 個 logits，就是對整個詞彙表的分數。",
           u"<strong>權重綁定</strong>：輸出層和 token embedding 共用同一張表。輸入時「字 → 向量」、輸出時「向量 → 每個字的分數」，用同一組權重很合理，還能省下 V×d 個參數（我們省了 130 萬）。",
           u"<strong>初始化</strong>：所有權重用標準差 0.02 的常態分布，偏差設 0，這是 GPT-2 的設定。"]),
   src("gpt", "        logits = self.head(self.ln_f(x))", "        return logits, loss"),
   ("p", u"損失就是對每個位置的 logits 做交叉熵，PyTorch 一行搞定。"),
  ],
  u"GPT 由 token／位置 embedding、N 個 Block、最後的 LayerNorm 與輸出層組成。輸出層和 token embedding 權重綁定以節省參數，權重以標準差 0.02 初始化，損失是每個位置的交叉熵。",
  [u"輸出層產生的 logits 有幾個數字？", u"什麼是權重綁定？有什麼好處？", u"GPT-2 的權重初始化標準差是多少？"]),

lesson(u"數參數：我的模型有多大",
  u"手算和程式算要一樣",
  [u"會計算 GPT 的參數量", u"知道小模型裡 embedding 佔比很高", u"把參數量換算成記憶體"],
  ex("s08_params") + [
   ("p", u"公式算出來和程式數出來完全一樣。注意 embedding 佔了約四成——小模型的詞彙表相對很「貴」。大模型則相反，Llama 3 8B 的 embedding 只佔約一成三。"),
   ngw({"t": "params", "q": u"調整詞彙量、維度、層數，看參數分布和訓練所需的記憶體。"}),
   ("p", u"更多大型模型的參數計算（GQA、MoE 等），見〈LLM 模型全解〉第 14～21 課。"),
  ],
  u"GPT 的參數量約 V·d + T·d + L·(12d² + 13d)，本課程模型約 309 萬，embedding 佔四成。訓練時每個參數約需 16 bytes（FP32 權重、梯度與 Adam 狀態）。",
  [u"寫出 GPT 參數量的近似公式。", u"為什麼小模型的 embedding 佔比特別高？", u"用 AdamW 訓練時，每個參數大約要幾 bytes？"]),

lesson(u"程式碼總檢查：完整的 GPT",
  u"約 200 行",
  [u"讀懂 gpt.py 的每一部分", u"知道 modern 開關切換了什麼", u"準備開始訓練"],
  [("p", u"這是完整的 <code>gpt.py</code>。<code>modern=True</code> 的分支（RoPE、RMSNorm、SwiGLU）和 KV cache 的部分，之後的課程會再說明，現在可以先略過。"),
  ] + ex("gpt", cmd=u"（由 train.py 匯入使用）") + [
   ("h", u"自我檢查清單"),
   ("ul", [u"每個 Linear、Embedding 的形狀你都說得出來嗎？", u"(B, T, C) 在注意力裡怎麼變成 (B, H, T, hd)？", u"loss 是對哪幾個位置算的？", u"為什麼 <code>head.weight = tok_emb.weight</code>？"]),
   ("note", u"和 nanoGPT 比較", [("p", u"這份程式的結構參考了 Andrej Karpathy 的開源專案 nanoGPT（MIT 授權）。nanoGPT 再多了 FlashAttention、從 OpenAI 載入 GPT-2 權重、多卡訓練等功能，讀完本課程後很適合接著讀。")]),
  ],
  u"完整的 gpt.py 約 200 行，包含 embedding、多頭因果注意力、MLP、Block、權重綁定與生成函式，並用 modern 開關切換 Llama 風格的元件。結構參考 nanoGPT。",
  [u"gpt.py 裡的 modern 開關切換了哪三個元件？", u"注意力的形狀是怎麼變化的？", u"讀完本課程後可以接著讀哪個開源專案？"]),
])

MODULES = [MODULE_A, MODULE_B, MODULE_C, MODULE_D]
