# -*- coding: utf-8 -*-
"""台灣廟宇常見神明資料,供「廟裡的神明」模組與「神明速查」參考頁共用。

誕辰為農曆,依台灣通行說法;各地、各廟可能不同。代表廟宇僅舉例,不代表排名。
每一項:dict(name, alias, origin, role, bday, temples, tags, lesson)
"""

TAGS = [u"平安", u"求財", u"事業", u"求學", u"姻緣", u"求子", u"健康", u"地方守護", u"航海", u"冥界與度亡", u"族群原鄉"]

GODS = [
    dict(name=u"玉皇大帝", alias=u"天公、玉皇上帝", origin=u"天界最高主宰的神格化;宋代以後在民間地位確立",
         role=u"統領天界眾神,掌管三界", bday=u"正月初九(天公生)", temples=u"台南天壇等", tags=[u"平安"], lesson=38),
    dict(name=u"三官大帝", alias=u"三界公", origin=u"源於早期天師道對天、地、水的祭祀",
         role=u"天官賜福、地官赦罪、水官解厄", bday=u"正月十五、七月十五、十月十五(三元節)", temples=u"各地三界公廟",
         tags=[u"平安", u"冥界與度亡"], lesson=38),
    dict(name=u"媽祖", alias=u"天上聖母、天后、媽祖婆", origin=u"宋代福建莆田湄洲的林默,傳說生前救護海難,死後被奉為神",
         role=u"海上守護神,後擴及全方位的守護", bday=u"三月二十三", temples=u"北港朝天宮、大甲鎮瀾宮、鹿港天后宮、台南大天后宮",
         tags=[u"航海", u"平安", u"地方守護"], lesson=39),
    dict(name=u"關聖帝君", alias=u"關公、恩主公、協天大帝", origin=u"三國蜀漢名將關羽,以忠義著稱,歷代加封",
         role=u"忠義之神、武財神、商人的守護神;佛教亦尊為伽藍菩薩", bday=u"六月二十四(另有正月十三之說)",
         temples=u"台北行天宮、台南祀典武廟", tags=[u"事業", u"求財", u"平安"], lesson=40),
    dict(name=u"福德正神", alias=u"土地公、伯公(客家)", origin=u"源於古代的社神(土地神)信仰",
         role=u"守護一方土地、五穀豐收、生意興隆", bday=u"二月初二(頭牙)", temples=u"新北中和烘爐地南山福德宮、屏東車城福安宮",
         tags=[u"地方守護", u"求財", u"事業"], lesson=41),
    dict(name=u"城隍爺", alias=u"城隍尊神", origin=u"源於城池(城牆與護城河)的守護神,後成為陰間的地方官",
         role=u"守護城市、審理陰間善惡", bday=u"各廟不同(台北霞海城隍為五月十三)", temples=u"新竹都城隍廟、台北霞海城隍廟",
         tags=[u"地方守護", u"冥界與度亡"], lesson=41),
    dict(name=u"保生大帝", alias=u"大道公、吳真人", origin=u"北宋福建同安的醫者吳夲,以行醫濟世著稱",
         role=u"醫神,保佑健康", bday=u"三月十五", temples=u"台北大龍峒保安宮、台南學甲慈濟宮",
         tags=[u"健康", u"族群原鄉"], lesson=42),
    dict(name=u"王爺", alias=u"千歲爺、代天巡狩", origin=u"來源多元,常與驅除瘟疫的信仰有關,姓氏眾多",
         role=u"代天巡狩、驅瘟逐疫、保境安民", bday=u"依各府王爺而不同", temples=u"台南南鯤鯓代天府、屏東東港東隆宮",
         tags=[u"平安", u"健康", u"地方守護"], lesson=42),
    dict(name=u"文昌帝君", alias=u"文昌星、梓潼帝君", origin=u"結合星辰信仰與四川梓潼神",
         role=u"主管功名、文運、考試", bday=u"二月初三", temples=u"各地文昌祠,常與孔廟、書院相鄰",
         tags=[u"求學", u"事業"], lesson=43),
    dict(name=u"魁星爺", alias=u"魁斗星君", origin=u"北斗七星的前四顆「魁星」的神格化",
         role=u"主管科舉考試,「魁星點斗」", bday=u"七月初七", temples=u"常配祀於文昌廟",
         tags=[u"求學"], lesson=43),
    dict(name=u"月下老人", alias=u"月老", origin=u"唐代小說〈定婚店〉中以紅線繫足定姻緣的老人",
         role=u"主管姻緣", bday=u"八月十五", temples=u"台北霞海城隍廟等",
         tags=[u"姻緣"], lesson=43),
    dict(name=u"註生娘娘", alias=u"註生媽", origin=u"主管生育的女神,常與臨水夫人等信仰相關",
         role=u"求子、保佑懷孕與生產", bday=u"三月二十", temples=u"常配祀於媽祖廟、觀音廟",
         tags=[u"求子"], lesson=43),
    dict(name=u"臨水夫人", alias=u"順天聖母、陳靖姑", origin=u"唐代福建的女性法師陳靖姑",
         role=u"保護婦女生產與孩童", bday=u"正月十五", temples=u"台南臨水夫人媽廟",
         tags=[u"求子", u"健康"], lesson=43),
    dict(name=u"玄天上帝", alias=u"上帝公、北極大帝、真武大帝", origin=u"北方星宿(玄武)的神格化;明代以武當山為祖庭",
         role=u"鎮守北方、降妖伏魔", bday=u"三月初三", temples=u"南投松柏嶺受天宮",
         tags=[u"平安", u"事業"], lesson=44),
    dict(name=u"中壇元帥", alias=u"太子爺、哪吒三太子", origin=u"源於佛教護法神,經《封神演義》等小說廣為人知",
         role=u"統領天兵五營、護佑孩童", bday=u"九月初九", temples=u"台南新營太子宮",
         tags=[u"平安", u"地方守護"], lesson=44),
    dict(name=u"財神", alias=u"趙公明、五路財神", origin=u"武財神趙公明等;五路指東西南北中",
         role=u"招財進寶", bday=u"三月十五(趙公明);正月初五迎財神", temples=u"各地財神廟,或配祀於廟中",
         tags=[u"求財", u"事業"], lesson=44),
    dict(name=u"虎爺", alias=u"虎爺將軍", origin=u"神明的坐騎與部將,常安座於神桌下",
         role=u"守護廟宇、護佑孩童、傳統上也被祈求財運", bday=u"常見說法為六月初六(各地不一)", temples=u"多配祀於神桌下",
         tags=[u"平安", u"求財"], lesson=44),
    dict(name=u"觀世音菩薩", alias=u"觀音佛祖、觀音媽", origin=u"佛教菩薩,在台灣也廣泛出現在民間廟宇",
         role=u"大慈大悲、聞聲救苦", bday=u"二月十九(另六月十九、九月十九為成道、出家紀念日)", temples=u"台北艋舺龍山寺",
         tags=[u"平安", u"求子", u"健康"], lesson=45),
    dict(name=u"灶君", alias=u"灶神、司命真君", origin=u"古代的灶神信仰",
         role=u"家庭的守護神,年底上天報告一家善惡", bday=u"八月初三;送神為十二月二十四", temples=u"多供奉於家中廚房",
         tags=[u"平安"], lesson=45),
    dict(name=u"地藏王菩薩", alias=u"地藏王", origin=u"佛教菩薩,發願「地獄不空,誓不成佛」",
         role=u"救度冥界眾生、超度亡者", bday=u"七月三十", temples=u"各地地藏庵、地藏殿",
         tags=[u"冥界與度亡"], lesson=45),
    dict(name=u"開漳聖王", alias=u"陳聖王、陳元光", origin=u"唐代開發漳州的將領陳元光",
         role=u"漳州移民的守護神", bday=u"二月十五", temples=u"台北內湖碧山巖",
         tags=[u"族群原鄉", u"地方守護"], lesson=46),
    dict(name=u"清水祖師", alias=u"祖師公、陳昭應", origin=u"宋代福建安溪的僧人,以祈雨濟民著稱",
         role=u"安溪移民的守護神", bday=u"正月初六", temples=u"新北三峽長福巖(三峽祖師廟)",
         tags=[u"族群原鄉", u"地方守護"], lesson=46),
    dict(name=u"三山國王", alias=u"三山國王", origin=u"廣東潮州一帶三座山的山神",
         role=u"潮州、客家移民的守護神", bday=u"二月二十五", temples=u"客家與潮州移民聚落多見",
         tags=[u"族群原鄉", u"地方守護"], lesson=46),
    dict(name=u"義民爺", alias=u"褒忠義民爺", origin=u"清代在地方動亂中犧牲的客家鄉勇",
         role=u"客家族群的守護與精神象徵", bday=u"七月二十前後舉行義民祭", temples=u"新竹新埔褒忠亭(義民廟)",
         tags=[u"族群原鄉", u"地方守護"], lesson=46),
    dict(name=u"孚佑帝君", alias=u"呂洞賓、呂祖、仙公", origin=u"唐代傳說人物,八仙之一,全真教尊為祖師",
         role=u"濟世度人,常見於鸞堂信仰", bday=u"四月十四", temples=u"台北木柵指南宮",
         tags=[u"平安", u"事業"], lesson=19),
    dict(name=u"太上老君", alias=u"道德天尊", origin=u"老子的神格化,三清之一",
         role=u"道教的教主之一,道德的化身", bday=u"二月十五", temples=u"道觀中與三清同祀",
         tags=[u"平安"], lesson=18),
]
