# -*- coding: utf-8 -*-
# LeetCode 題解主題的題目清單。
# 新增一題：在 PROBLEMS 裡加一筆，並在 bodies/ 放對應的 NNNN.html。

PROBLEMS = [
    {
        "num": 1,
        "en": "Two Sum",
        "zh": "兩數之和",
        "difficulty": "Easy",
        "tags": ["陣列", "雜湊表"],
        "desc": "從暴力法到一趟雜湊表：四種解法、複雜度對照與常見陷阱。",
    },
    {
        "num": 2,
        "en": "Add Two Numbers",
        "zh": "兩數相加",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "數學", "遞迴"],
        "desc": "鏈結串列上的直式加法：虛擬頭節點、進位處理、遞迴版本，以及「轉成整數再加」為何是陷阱。",
    },
    {
        "num": 3,
        "en": "Longest Substring Without Repeating Characters",
        "zh": "無重複字元的最長子字串",
        "difficulty": "Medium",
        "tags": ["雜湊表", "字串", "滑動視窗"],
        "desc": "滑動視窗的標準範本：從 O(n³) 暴力法一路優化到一趟掃描的 O(n)。",
    },
    {
        "num": 4,
        "en": "Median of Two Sorted Arrays",
        "zh": "兩個有序陣列的中位數",
        "difficulty": "Hard",
        "tags": ["陣列", "二分搜尋", "分治"],
        "desc": "從合併 O(m+n) 到「切一刀」的 O(log(min(m,n)))：二分搜尋分割點的完整推導。",
    },
    {
        "num": 5,
        "en": "Longest Palindromic Substring",
        "zh": "最長回文子字串",
        "difficulty": "Medium",
        "tags": ["字串", "動態規劃", "雙指標"],
        "desc": "中心擴展、動態規劃與 Manacher 演算法三種解法對照。",
    },
    {
        "num": 6,
        "en": "Zigzag Conversion",
        "zh": "Z 字形變換",
        "difficulty": "Medium",
        "tags": ["字串"],
        "desc": "模擬走訪與直接推導索引公式兩種思路。",
    },
    {
        "num": 7,
        "en": "Reverse Integer",
        "zh": "整數反轉",
        "difficulty": "Medium",
        "tags": ["數學"],
        "desc": "32 位元溢位怎麼在沒有大整數的語言裡判斷——Python 反而要自己補上這個檢查。",
    },
    {
        "num": 8,
        "en": "String to Integer (atoi)",
        "zh": "字串轉換整數",
        "difficulty": "Medium",
        "tags": ["字串"],
        "desc": "一題考規格閱讀的題目：狀態機寫法與逐步解析寫法。",
    },
    {
        "num": 9,
        "en": "Palindrome Number",
        "zh": "回文數",
        "difficulty": "Easy",
        "tags": ["數學"],
        "desc": "不轉字串的做法：反轉一半數字就夠了。",
    },
    {
        "num": 10,
        "en": "Regular Expression Matching",
        "zh": "正規表示式匹配",
        "difficulty": "Hard",
        "tags": ["字串", "動態規劃", "遞迴"],
        "desc": "* 的兩種選擇：記憶化遞迴與自底向上 DP 的完整狀態轉移推導。",
    },
    {
        "num": 11,
        "en": "Container With Most Water",
        "zh": "盛最多水的容器",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標", "貪心"],
        "desc": "雙指標為什麼可以放心捨棄一邊——附完整的正確性證明。",
    },
    {
        "num": 12,
        "en": "Integer to Roman",
        "zh": "整數轉羅馬數字",
        "difficulty": "Medium",
        "tags": ["雜湊表", "數學", "字串"],
        "desc": "把減法形式（IV、IX）直接放進對照表，貪心就成立了。",
    },
    {
        "num": 13,
        "en": "Roman to Integer",
        "zh": "羅馬數字轉整數",
        "difficulty": "Easy",
        "tags": ["雜湊表", "數學", "字串"],
        "desc": "「小的在大的左邊就是減」——一趟掃描的判斷規則。",
    },
    {
        "num": 14,
        "en": "Longest Common Prefix",
        "zh": "最長公共前綴",
        "difficulty": "Easy",
        "tags": ["字串", "字典樹"],
        "desc": "垂直掃描、水平掃描、分治與 zip 技巧。",
    },
    {
        "num": 15,
        "en": "3Sum",
        "zh": "三數之和",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標", "排序"],
        "desc": "排序後固定一個數 + 雙指標，重點在三處去重。",
    },
    {
        "num": 16,
        "en": "3Sum Closest",
        "zh": "最接近的三數之和",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標", "排序"],
        "desc": "與 15 題同一套骨架，把「等於」改成「最接近」。",
    },
    {
        "num": 17,
        "en": "Letter Combinations of a Phone Number",
        "zh": "電話號碼的字母組合",
        "difficulty": "Medium",
        "tags": ["雜湊表", "字串", "回溯"],
        "desc": "回溯法的入門題：遞迴與迭代兩種寫法。",
    },
    {
        "num": 18,
        "en": "4Sum",
        "zh": "四數之和",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標", "排序"],
        "desc": "kSum 的通用遞迴框架，以及兩層剪枝。",
    },
    {
        "num": 19,
        "en": "Remove Nth Node From End of List",
        "zh": "刪除鏈結串列的倒數第 N 個節點",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "雙指標"],
        "desc": "快慢指標一趟解決，虛擬頭節點處理刪除頭節點的邊界。",
    },
    {
        "num": 20,
        "en": "Valid Parentheses",
        "zh": "有效的括號",
        "difficulty": "Easy",
        "tags": ["字串", "堆疊"],
        "desc": "堆疊的入門題：三個邊界條件決定對錯。",
    },
    {
        "num": 21,
        "en": "Merge Two Sorted Lists",
        "zh": "合併兩個有序串列",
        "difficulty": "Easy",
        "tags": ["鏈結串列", "遞迴"],
        "desc": "虛擬頭節點的標準用法，迭代與遞迴對照。",
    },
    {
        "num": 22,
        "en": "Generate Parentheses",
        "zh": "括號生成",
        "difficulty": "Medium",
        "tags": ["字串", "動態規劃", "回溯"],
        "desc": "回溯 + 剪枝，以及卡塔蘭數的 DP 解法。",
    },
    {
        "num": 23,
        "en": "Merge k Sorted Lists",
        "zh": "合併 K 個升序串列",
        "difficulty": "Hard",
        "tags": ["鏈結串列", "分治", "堆積"],
        "desc": "最小堆積 O(N log k) 與兩兩合併分治的對照。",
    },
    {
        "num": 24,
        "en": "Swap Nodes in Pairs",
        "zh": "兩兩交換串列中的節點",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "遞迴"],
        "desc": "指標重接的順序問題，畫圖比看程式碼有用。",
    },
    {
        "num": 25,
        "en": "Reverse Nodes in k-Group",
        "zh": "K 個一組翻轉串列",
        "difficulty": "Hard",
        "tags": ["鏈結串列", "遞迴"],
        "desc": "把「翻轉一段」拆成獨立子問題，再處理接合。",
    },
    {
        "num": 26,
        "en": "Remove Duplicates from Sorted Array",
        "zh": "刪除有序陣列中的重複項",
        "difficulty": "Easy",
        "tags": ["陣列", "雙指標"],
        "desc": "原地修改的快慢指標範本。",
    },
    {
        "num": 27,
        "en": "Remove Element",
        "zh": "移除元素",
        "difficulty": "Easy",
        "tags": ["陣列", "雙指標"],
        "desc": "同向雙指標與相向雙指標，後者在「要刪的很少」時更快。",
    },
    {
        "num": 28,
        "en": "Find the Index of the First Occurrence in a String",
        "zh": "找出字串中第一個匹配項的下標",
        "difficulty": "Easy",
        "tags": ["雙指標", "字串", "字串匹配"],
        "desc": "暴力比對、KMP 與 Rabin–Karp 三種字串匹配演算法。",
    },
    {
        "num": 29,
        "en": "Divide Two Integers",
        "zh": "兩數相除",
        "difficulty": "Medium",
        "tags": ["位元運算", "數學"],
        "desc": "不用乘除法做除法：倍增減法與位元運算。",
    },
    {
        "num": 30,
        "en": "Substring with Concatenation of All Words",
        "zh": "串聯所有單詞的子串",
        "difficulty": "Hard",
        "tags": ["雜湊表", "字串", "滑動視窗"],
        "desc": "固定長度的滑動視窗，以 word 為單位跳躍。",
    },
    {
        "num": 31,
        "en": "Next Permutation",
        "zh": "下一個排列",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標"],
        "desc": "字典序下一個排列的三步驟：找降序點、找交換點、反轉尾段。",
    },
    {
        "num": 32,
        "en": "Longest Valid Parentheses",
        "zh": "最長有效括號",
        "difficulty": "Hard",
        "tags": ["字串", "動態規劃", "堆疊"],
        "desc": "堆疊、DP 與左右兩趟計數三種解法。",
    },
    {
        "num": 33,
        "en": "Search in Rotated Sorted Array",
        "zh": "搜尋旋轉排序陣列",
        "difficulty": "Medium",
        "tags": ["陣列", "二分搜尋"],
        "desc": "旋轉後仍然有一半是有序的——二分搜尋的變形。",
    },
    {
        "num": 34,
        "en": "Find First and Last Position of Element in Sorted Array",
        "zh": "在排序陣列中查找元素的第一個和最後一個位置",
        "difficulty": "Medium",
        "tags": ["陣列", "二分搜尋"],
        "desc": "左界與右界兩次二分，以及 bisect 的對應關係。",
    },
    {
        "num": 35,
        "en": "Search Insert Position",
        "zh": "搜尋插入位置",
        "difficulty": "Easy",
        "tags": ["陣列", "二分搜尋"],
        "desc": "二分搜尋的標準模板，重點在迴圈不變式。",
    },
    {
        "num": 36,
        "en": "Valid Sudoku",
        "zh": "有效的數獨",
        "difficulty": "Medium",
        "tags": ["陣列", "雜湊表", "矩陣"],
        "desc": "三組集合一趟掃完，宮格索引的公式推導。",
    },
    {
        "num": 37,
        "en": "Sudoku Solver",
        "zh": "解數獨",
        "difficulty": "Hard",
        "tags": ["陣列", "回溯", "矩陣"],
        "desc": "回溯 + 約束傳播，以及位元遮罩的加速。",
    },
    {
        "num": 38,
        "en": "Count and Say",
        "zh": "外觀數列",
        "difficulty": "Medium",
        "tags": ["字串"],
        "desc": "逐層產生，用雙指標數連續相同字元。",
    },
    {
        "num": 39,
        "en": "Combination Sum",
        "zh": "組合總和",
        "difficulty": "Medium",
        "tags": ["陣列", "回溯"],
        "desc": "可重複取用的回溯，用起始索引避免重複組合。",
    },
    {
        "num": 40,
        "en": "Combination Sum II",
        "zh": "組合總和 II",
        "difficulty": "Medium",
        "tags": ["陣列", "回溯"],
        "desc": "每個元素只能用一次 + 有重複元素，去重是重點。",
    },
    {
        "num": 41,
        "en": "First Missing Positive",
        "zh": "缺失的第一個正數",
        "difficulty": "Hard",
        "tags": ["陣列", "雜湊表"],
        "desc": "O(n) 時間 O(1) 空間：把陣列自己當成雜湊表。",
    },
    {
        "num": 42,
        "en": "Trapping Rain Water",
        "zh": "接雨水",
        "difficulty": "Hard",
        "tags": ["陣列", "雙指標", "動態規劃", "堆疊"],
        "desc": "四種解法：暴力、前後綴極值、單調堆疊、雙指標。",
    },
    {
        "num": 43,
        "en": "Multiply Strings",
        "zh": "字串相乘",
        "difficulty": "Medium",
        "tags": ["數學", "字串", "模擬"],
        "desc": "直式乘法的索引規律：i + j 與 i + j + 1。",
    },
    {
        "num": 44,
        "en": "Wildcard Matching",
        "zh": "通配符匹配",
        "difficulty": "Hard",
        "tags": ["字串", "動態規劃", "貪心"],
        "desc": "與 10 題對照：* 的語意不同導致貪心可行。",
    },
    {
        "num": 45,
        "en": "Jump Game II",
        "zh": "跳躍遊戲 II",
        "difficulty": "Medium",
        "tags": ["陣列", "貪心", "動態規劃"],
        "desc": "把它看成 BFS 分層，貪心就自然了。",
    },
    {
        "num": 46,
        "en": "Permutations",
        "zh": "全排列",
        "difficulty": "Medium",
        "tags": ["陣列", "回溯"],
        "desc": "交換法與 used 陣列法兩種回溯骨架。",
    },
    {
        "num": 47,
        "en": "Permutations II",
        "zh": "全排列 II",
        "difficulty": "Medium",
        "tags": ["陣列", "回溯"],
        "desc": "有重複元素時的去重規則與它的正確性。",
    },
    {
        "num": 48,
        "en": "Rotate Image",
        "zh": "旋轉圖像",
        "difficulty": "Medium",
        "tags": ["陣列", "數學", "矩陣"],
        "desc": "轉置 + 翻轉，以及四點一組的原地旋轉。",
    },
    {
        "num": 49,
        "en": "Group Anagrams",
        "zh": "字母異位詞分組",
        "difficulty": "Medium",
        "tags": ["陣列", "雜湊表", "字串", "排序"],
        "desc": "兩種簽章：排序後的字串與 26 維計數。",
    },
    {
        "num": 50,
        "en": "Pow(x, n)",
        "zh": "Pow(x, n)",
        "difficulty": "Medium",
        "tags": ["數學", "遞迴"],
        "desc": "快速冪：二分遞迴與位元迭代兩種寫法。",
    },
    {
        "num": 51,
        "en": "N-Queens",
        "zh": "N 皇后",
        "difficulty": "Hard",
        "tags": ["陣列", "回溯"],
        "desc": "用三組集合 O(1) 判斷衝突，對角線索引的公式。",
    },
    {
        "num": 52,
        "en": "N-Queens II",
        "zh": "N 皇后 II",
        "difficulty": "Hard",
        "tags": ["回溯"],
        "desc": "只數數量，順便介紹位元運算版本。",
    },
    {
        "num": 53,
        "en": "Maximum Subarray",
        "zh": "最大子陣列和",
        "difficulty": "Medium",
        "tags": ["陣列", "分治", "動態規劃"],
        "desc": "Kadane 演算法的推導，以及分治解法。",
    },
    {
        "num": 54,
        "en": "Spiral Matrix",
        "zh": "螺旋矩陣",
        "difficulty": "Medium",
        "tags": ["陣列", "矩陣", "模擬"],
        "desc": "四邊界收縮法，重點在中間那一行/列的重複問題。",
    },
    {
        "num": 55,
        "en": "Jump Game",
        "zh": "跳躍遊戲",
        "difficulty": "Medium",
        "tags": ["陣列", "貪心", "動態規劃"],
        "desc": "維護「能到的最遠位置」，一趟掃描。",
    },
    {
        "num": 56,
        "en": "Merge Intervals",
        "zh": "合併區間",
        "difficulty": "Medium",
        "tags": ["陣列", "排序"],
        "desc": "排序後一趟合併，區間題的通用起手式。",
    },
    {
        "num": 57,
        "en": "Insert Interval",
        "zh": "插入區間",
        "difficulty": "Medium",
        "tags": ["陣列"],
        "desc": "已排序的情況下三段式處理，不需要重新排序。",
    },
    {
        "num": 58,
        "en": "Length of Last Word",
        "zh": "最後一個單詞的長度",
        "difficulty": "Easy",
        "tags": ["字串"],
        "desc": "從尾巴掃比 split 更省空間。",
    },
    {
        "num": 59,
        "en": "Spiral Matrix II",
        "zh": "螺旋矩陣 II",
        "difficulty": "Medium",
        "tags": ["陣列", "矩陣", "模擬"],
        "desc": "54 題的反向版本，同一套邊界收縮。",
    },
    {
        "num": 60,
        "en": "Permutation Sequence",
        "zh": "排列序列",
        "difficulty": "Hard",
        "tags": ["數學", "回溯"],
        "desc": "用階乘直接算出每一位，不需要真的枚舉。",
    },
    {
        "num": 61,
        "en": "Rotate List",
        "zh": "旋轉串列",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "雙指標"],
        "desc": "成環再斷開，一趟半解決。",
    },
    {
        "num": 62,
        "en": "Unique Paths",
        "zh": "不同路徑",
        "difficulty": "Medium",
        "tags": ["數學", "動態規劃", "組合數學"],
        "desc": "DP、滾動陣列與組合數公式三種解法。",
    },
    {
        "num": 63,
        "en": "Unique Paths II",
        "zh": "不同路徑 II",
        "difficulty": "Medium",
        "tags": ["陣列", "動態規劃", "矩陣"],
        "desc": "有障礙物時的 DP，原地滾動陣列。",
    },
    {
        "num": 64,
        "en": "Minimum Path Sum",
        "zh": "最小路徑和",
        "difficulty": "Medium",
        "tags": ["陣列", "動態規劃", "矩陣"],
        "desc": "網格 DP 的標準形式，含邊界初始化的處理。",
    },
    {
        "num": 65,
        "en": "Valid Number",
        "zh": "有效數字",
        "difficulty": "Hard",
        "tags": ["字串"],
        "desc": "用狀態機把一堆 if 收斂成一張轉移表。",
    },
    {
        "num": 66,
        "en": "Plus One",
        "zh": "加一",
        "difficulty": "Easy",
        "tags": ["陣列", "數學"],
        "desc": "進位的邊界：全部是 9 的時候。",
    },
    {
        "num": 67,
        "en": "Add Binary",
        "zh": "二進位求和",
        "difficulty": "Easy",
        "tags": ["位元運算", "數學", "字串"],
        "desc": "與第 2 題同一套進位邏輯，換成字串。",
    },
    {
        "num": 68,
        "en": "Text Justification",
        "zh": "文字左右對齊",
        "difficulty": "Hard",
        "tags": ["陣列", "字串", "模擬"],
        "desc": "純模擬題，重點在把規格拆成互斥的分支。",
    },
    {
        "num": 69,
        "en": "Sqrt(x)",
        "zh": "x 的平方根",
        "difficulty": "Easy",
        "tags": ["數學", "二分搜尋"],
        "desc": "二分搜尋與牛頓法，以及浮點數為什麼不可靠。",
    },
    {
        "num": 70,
        "en": "Climbing Stairs",
        "zh": "爬樓梯",
        "difficulty": "Easy",
        "tags": ["記憶化搜尋", "數學", "動態規劃"],
        "desc": "費波那契數列：遞迴 → 記憶化 → 滾動變數 → 矩陣快速冪。",
    },
    {
        "num": 71,
        "en": "Simplify Path",
        "zh": "簡化路徑",
        "difficulty": "Medium",
        "tags": ["字串", "堆疊"],
        "desc": "split 之後用堆疊處理 . 與 .. 的四種情況。",
    },
    {
        "num": 72,
        "en": "Edit Distance",
        "zh": "編輯距離",
        "difficulty": "Medium",
        "tags": ["字串", "動態規劃"],
        "desc": "經典二維 DP，三個轉移各自對應一種編輯操作。",
    },
    {
        "num": 73,
        "en": "Set Matrix Zeroes",
        "zh": "矩陣置零",
        "difficulty": "Medium",
        "tags": ["陣列", "雜湊表", "矩陣"],
        "desc": "用第一列與第一行當標記，做到 O(1) 額外空間。",
    },
    {
        "num": 74,
        "en": "Search a 2D Matrix",
        "zh": "搜尋二維矩陣",
        "difficulty": "Medium",
        "tags": ["陣列", "二分搜尋", "矩陣"],
        "desc": "把二維攤平成一維來做二分。",
    },
    {
        "num": 75,
        "en": "Sort Colors",
        "zh": "顏色分類",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標", "排序"],
        "desc": "荷蘭國旗問題：三指標一趟分割。",
    },
    {
        "num": 76,
        "en": "Minimum Window Substring",
        "zh": "最小覆蓋子串",
        "difficulty": "Hard",
        "tags": ["雜湊表", "字串", "滑動視窗"],
        "desc": "求最小視窗的滑動視窗，收縮條件比第 3 題複雜。",
    },
    {
        "num": 77,
        "en": "Combinations",
        "zh": "組合",
        "difficulty": "Medium",
        "tags": ["回溯"],
        "desc": "回溯 + 剪枝，剪枝條件的推導。",
    },
    {
        "num": 78,
        "en": "Subsets",
        "zh": "子集",
        "difficulty": "Medium",
        "tags": ["位元運算", "陣列", "回溯"],
        "desc": "回溯、迭代擴充與位元枚舉三種解法。",
    },
    {
        "num": 79,
        "en": "Word Search",
        "zh": "單詞搜索",
        "difficulty": "Medium",
        "tags": ["陣列", "回溯", "矩陣"],
        "desc": "網格回溯，原地標記避免額外的 visited 陣列。",
    },
    {
        "num": 80,
        "en": "Remove Duplicates from Sorted Array II",
        "zh": "刪除有序陣列中的重複項 II",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標"],
        "desc": "把 26 題推廣成「最多保留 k 個」的通用寫法。",
    },
    {
        "num": 81,
        "en": "Search in Rotated Sorted Array II",
        "zh": "搜尋旋轉排序陣列 II",
        "difficulty": "Medium",
        "tags": ["陣列", "二分搜尋"],
        "desc": "有重複元素時，為什麼最壞情況會退化成 O(n)。",
    },
    {
        "num": 82,
        "en": "Remove Duplicates from Sorted List II",
        "zh": "刪除排序串列中的重複元素 II",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "雙指標"],
        "desc": "刪除「所有」重複的節點，虛擬頭節點必備。",
    },
    {
        "num": 83,
        "en": "Remove Duplicates from Sorted List",
        "zh": "刪除排序串列中的重複元素",
        "difficulty": "Easy",
        "tags": ["鏈結串列"],
        "desc": "每組只留一個，與 82 題的差別在哪。",
    },
    {
        "num": 84,
        "en": "Largest Rectangle in Histogram",
        "zh": "柱狀圖中最大的矩形",
        "difficulty": "Hard",
        "tags": ["陣列", "堆疊", "單調堆疊"],
        "desc": "單調遞增堆疊：每根柱子被彈出時就是它的答案。",
    },
    {
        "num": 85,
        "en": "Maximal Rectangle",
        "zh": "最大矩形",
        "difficulty": "Hard",
        "tags": ["陣列", "動態規劃", "堆疊", "矩陣"],
        "desc": "逐列轉成直方圖，直接套 84 題。",
    },
    {
        "num": 86,
        "en": "Partition List",
        "zh": "分隔串列",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "雙指標"],
        "desc": "兩條串列各自接好再串起來。",
    },
    {
        "num": 87,
        "en": "Scramble String",
        "zh": "擾亂字串",
        "difficulty": "Hard",
        "tags": ["字串", "動態規劃"],
        "desc": "區間 DP + 記憶化，以及剪枝為什麼關鍵。",
    },
    {
        "num": 88,
        "en": "Merge Sorted Array",
        "zh": "合併兩個有序陣列",
        "difficulty": "Easy",
        "tags": ["陣列", "雙指標", "排序"],
        "desc": "從後往前填，避免覆蓋未處理的元素。",
    },
    {
        "num": 89,
        "en": "Gray Code",
        "zh": "格雷編碼",
        "difficulty": "Medium",
        "tags": ["位元運算", "數學", "回溯"],
        "desc": "i ^ (i >> 1) 這條公式怎麼來的。",
    },
    {
        "num": 90,
        "en": "Subsets II",
        "zh": "子集 II",
        "difficulty": "Medium",
        "tags": ["位元運算", "陣列", "回溯"],
        "desc": "有重複元素的子集去重。",
    },
    {
        "num": 91,
        "en": "Decode Ways",
        "zh": "解碼方法",
        "difficulty": "Medium",
        "tags": ["字串", "動態規劃"],
        "desc": "帶條件的費波那契，0 的處理是關鍵。",
    },
    {
        "num": 92,
        "en": "Reverse Linked List II",
        "zh": "反轉串列 II",
        "difficulty": "Medium",
        "tags": ["鏈結串列"],
        "desc": "頭插法一趟完成，不需要先找長度。",
    },
    {
        "num": 93,
        "en": "Restore IP Addresses",
        "zh": "復原 IP 位址",
        "difficulty": "Medium",
        "tags": ["字串", "回溯"],
        "desc": "回溯 + 三個合法性條件的剪枝。",
    },
    {
        "num": 94,
        "en": "Binary Tree Inorder Traversal",
        "zh": "二元樹的中序走訪",
        "difficulty": "Easy",
        "tags": ["堆疊", "樹", "深度優先搜尋"],
        "desc": "遞迴、堆疊迭代與 Morris 走訪（O(1) 空間）。",
    },
    {
        "num": 95,
        "en": "Unique Binary Search Trees II",
        "zh": "不同的二元搜尋樹 II",
        "difficulty": "Medium",
        "tags": ["動態規劃", "回溯", "樹"],
        "desc": "分治遞迴建樹，以及為什麼可以共用子樹。",
    },
    {
        "num": 96,
        "en": "Unique Binary Search Trees",
        "zh": "不同的二元搜尋樹",
        "difficulty": "Medium",
        "tags": ["數學", "動態規劃", "樹"],
        "desc": "卡塔蘭數：DP 遞推與封閉公式。",
    },
    {
        "num": 97,
        "en": "Interleaving String",
        "zh": "交錯字串",
        "difficulty": "Medium",
        "tags": ["字串", "動態規劃"],
        "desc": "二維 DP，為什麼貪心與雙指標都不行。",
    },
    {
        "num": 98,
        "en": "Validate Binary Search Tree",
        "zh": "驗證二元搜尋樹",
        "difficulty": "Medium",
        "tags": ["樹", "深度優先搜尋", "二元搜尋樹"],
        "desc": "上下界遞迴與中序走訪兩種解法，以及最常見的錯誤寫法。",
    },
    {
        "num": 99,
        "en": "Recover Binary Search Tree",
        "zh": "復原二元搜尋樹",
        "difficulty": "Medium",
        "tags": ["樹", "深度優先搜尋", "二元搜尋樹"],
        "desc": "中序走訪找出兩個逆序點，Morris 走訪做到 O(1) 空間。",
    },
    {
        "num": 100,
        "en": "Same Tree",
        "zh": "相同的樹",
        "difficulty": "Easy",
        "tags": ["樹", "深度優先搜尋", "廣度優先搜尋"],
        "desc": "遞迴與迭代，樹題目的最小起點。",
    },
]

DIFFICULTY_ZH = {"Easy": "簡單", "Medium": "中等", "Hard": "困難"}

# 側邊欄與主題頁的分組：每 25 題一組，題目變多時自動延伸。
GROUP_SIZE = 25


def group_label(num):
    start = ((num - 1) // GROUP_SIZE) * GROUP_SIZE + 1
    return u"第 %03d–%03d 題" % (start, start + GROUP_SIZE - 1)


def grouped():
    """回傳 [(group_label, [problem, ...]), ...]，依題號排序。"""
    out = []
    for p in sorted(PROBLEMS, key=lambda x: x["num"]):
        label = group_label(p["num"])
        if not out or out[-1][0] != label:
            out.append((label, []))
        out[-1][1].append(p)
    return out


def course_title(p):
    return u"%d. %s %s" % (p["num"], p["en"], p["zh"])


def slug(p):
    return u"problem-%04d" % p["num"]
