# -*- coding: utf-8 -*-
# LeetCode 題解主題的題目清單。
# 新增一題：在 PROBLEMS 裡加一筆，並在 bodies/ 放對應的 NNNN.html。

PROBLEMS = [
    {
        "num": 1,
        "en": "Two Sum",
        "zh": "兩數之和",
        "difficulty": "Easy",
        "tags": ["陣列", "雜湊表"],
        "desc": "從暴力法到一趟雜湊表：四種解法、複雜度對照與常見陷阱。",
    },
    {
        "num": 2,
        "en": "Add Two Numbers",
        "zh": "兩數相加",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "數學", "遞迴"],
        "desc": "鏈結串列上的直式加法：虛擬頭節點、進位處理、遞迴版本，以及「轉成整數再加」為何是陷阱。",
    },
    {
        "num": 3,
        "en": "Longest Substring Without Repeating Characters",
        "zh": "無重複字元的最長子字串",
        "difficulty": "Medium",
        "tags": ["雜湊表", "字串", "滑動視窗"],
        "desc": "滑動視窗的標準範本：從 O(n³) 暴力法一路優化到一趟掃描的 O(n)。",
    },
    {
        "num": 4,
        "en": "Median of Two Sorted Arrays",
        "zh": "兩個有序陣列的中位數",
        "difficulty": "Hard",
        "tags": ["陣列", "二分搜尋", "分治"],
        "desc": "從合併 O(m+n) 到「切一刀」的 O(log(min(m,n)))：二分搜尋分割點的完整推導。",
    },
    {
        "num": 5,
        "en": "Longest Palindromic Substring",
        "zh": "最長回文子字串",
        "difficulty": "Medium",
        "tags": ["字串", "動態規劃", "雙指標"],
        "desc": "中心擴展、動態規劃與 Manacher 演算法三種解法對照。",
    },
    {
        "num": 6,
        "en": "Zigzag Conversion",
        "zh": "Z 字形變換",
        "difficulty": "Medium",
        "tags": ["字串"],
        "desc": "模擬走訪與直接推導索引公式兩種思路。",
    },
    {
        "num": 7,
        "en": "Reverse Integer",
        "zh": "整數反轉",
        "difficulty": "Medium",
        "tags": ["數學"],
        "desc": "32 位元溢位怎麼在沒有大整數的語言裡判斷——Python 反而要自己補上這個檢查。",
    },
    {
        "num": 8,
        "en": "String to Integer (atoi)",
        "zh": "字串轉換整數",
        "difficulty": "Medium",
        "tags": ["字串"],
        "desc": "一題考規格閱讀的題目：狀態機寫法與逐步解析寫法。",
    },
    {
        "num": 9,
        "en": "Palindrome Number",
        "zh": "回文數",
        "difficulty": "Easy",
        "tags": ["數學"],
        "desc": "不轉字串的做法：反轉一半數字就夠了。",
    },
    {
        "num": 10,
        "en": "Regular Expression Matching",
        "zh": "正規表示式匹配",
        "difficulty": "Hard",
        "tags": ["字串", "動態規劃", "遞迴"],
        "desc": "* 的兩種選擇：記憶化遞迴與自底向上 DP 的完整狀態轉移推導。",
    },
    {
        "num": 11,
        "en": "Container With Most Water",
        "zh": "盛最多水的容器",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標", "貪心"],
        "desc": "雙指標為什麼可以放心捨棄一邊——附完整的正確性證明。",
    },
    {
        "num": 12,
        "en": "Integer to Roman",
        "zh": "整數轉羅馬數字",
        "difficulty": "Medium",
        "tags": ["雜湊表", "數學", "字串"],
        "desc": "把減法形式（IV、IX）直接放進對照表，貪心就成立了。",
    },
    {
        "num": 13,
        "en": "Roman to Integer",
        "zh": "羅馬數字轉整數",
        "difficulty": "Easy",
        "tags": ["雜湊表", "數學", "字串"],
        "desc": "「小的在大的左邊就是減」——一趟掃描的判斷規則。",
    },
    {
        "num": 14,
        "en": "Longest Common Prefix",
        "zh": "最長公共前綴",
        "difficulty": "Easy",
        "tags": ["字串", "字典樹"],
        "desc": "垂直掃描、水平掃描、分治與 zip 技巧。",
    },
    {
        "num": 15,
        "en": "3Sum",
        "zh": "三數之和",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標", "排序"],
        "desc": "排序後固定一個數 + 雙指標，重點在三處去重。",
    },
    {
        "num": 16,
        "en": "3Sum Closest",
        "zh": "最接近的三數之和",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標", "排序"],
        "desc": "與 15 題同一套骨架，把「等於」改成「最接近」。",
    },
    {
        "num": 17,
        "en": "Letter Combinations of a Phone Number",
        "zh": "電話號碼的字母組合",
        "difficulty": "Medium",
        "tags": ["雜湊表", "字串", "回溯"],
        "desc": "回溯法的入門題：遞迴與迭代兩種寫法。",
    },
    {
        "num": 18,
        "en": "4Sum",
        "zh": "四數之和",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標", "排序"],
        "desc": "kSum 的通用遞迴框架，以及兩層剪枝。",
    },
    {
        "num": 19,
        "en": "Remove Nth Node From End of List",
        "zh": "刪除鏈結串列的倒數第 N 個節點",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "雙指標"],
        "desc": "快慢指標一趟解決，虛擬頭節點處理刪除頭節點的邊界。",
    },
    {
        "num": 20,
        "en": "Valid Parentheses",
        "zh": "有效的括號",
        "difficulty": "Easy",
        "tags": ["字串", "堆疊"],
        "desc": "堆疊的入門題：三個邊界條件決定對錯。",
    },
    {
        "num": 21,
        "en": "Merge Two Sorted Lists",
        "zh": "合併兩個有序串列",
        "difficulty": "Easy",
        "tags": ["鏈結串列", "遞迴"],
        "desc": "虛擬頭節點的標準用法，迭代與遞迴對照。",
    },
    {
        "num": 22,
        "en": "Generate Parentheses",
        "zh": "括號生成",
        "difficulty": "Medium",
        "tags": ["字串", "動態規劃", "回溯"],
        "desc": "回溯 + 剪枝，以及卡塔蘭數的 DP 解法。",
    },
    {
        "num": 23,
        "en": "Merge k Sorted Lists",
        "zh": "合併 K 個升序串列",
        "difficulty": "Hard",
        "tags": ["鏈結串列", "分治", "堆積"],
        "desc": "最小堆積 O(N log k) 與兩兩合併分治的對照。",
    },
    {
        "num": 24,
        "en": "Swap Nodes in Pairs",
        "zh": "兩兩交換串列中的節點",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "遞迴"],
        "desc": "指標重接的順序問題，畫圖比看程式碼有用。",
    },
    {
        "num": 25,
        "en": "Reverse Nodes in k-Group",
        "zh": "K 個一組翻轉串列",
        "difficulty": "Hard",
        "tags": ["鏈結串列", "遞迴"],
        "desc": "把「翻轉一段」拆成獨立子問題，再處理接合。",
    },
    {
        "num": 26,
        "en": "Remove Duplicates from Sorted Array",
        "zh": "刪除有序陣列中的重複項",
        "difficulty": "Easy",
        "tags": ["陣列", "雙指標"],
        "desc": "原地修改的快慢指標範本。",
    },
    {
        "num": 27,
        "en": "Remove Element",
        "zh": "移除元素",
        "difficulty": "Easy",
        "tags": ["陣列", "雙指標"],
        "desc": "同向雙指標與相向雙指標，後者在「要刪的很少」時更快。",
    },
    {
        "num": 28,
        "en": "Find the Index of the First Occurrence in a String",
        "zh": "找出字串中第一個匹配項的下標",
        "difficulty": "Easy",
        "tags": ["雙指標", "字串", "字串匹配"],
        "desc": "暴力比對、KMP 與 Rabin–Karp 三種字串匹配演算法。",
    },
    {
        "num": 29,
        "en": "Divide Two Integers",
        "zh": "兩數相除",
        "difficulty": "Medium",
        "tags": ["位元運算", "數學"],
        "desc": "不用乘除法做除法：倍增減法與位元運算。",
    },
    {
        "num": 30,
        "en": "Substring with Concatenation of All Words",
        "zh": "串聯所有單詞的子串",
        "difficulty": "Hard",
        "tags": ["雜湊表", "字串", "滑動視窗"],
        "desc": "固定長度的滑動視窗，以 word 為單位跳躍。",
    },
    {
        "num": 31,
        "en": "Next Permutation",
        "zh": "下一個排列",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標"],
        "desc": "字典序下一個排列的三步驟：找降序點、找交換點、反轉尾段。",
    },
    {
        "num": 32,
        "en": "Longest Valid Parentheses",
        "zh": "最長有效括號",
        "difficulty": "Hard",
        "tags": ["字串", "動態規劃", "堆疊"],
        "desc": "堆疊、DP 與左右兩趟計數三種解法。",
    },
    {
        "num": 33,
        "en": "Search in Rotated Sorted Array",
        "zh": "搜尋旋轉排序陣列",
        "difficulty": "Medium",
        "tags": ["陣列", "二分搜尋"],
        "desc": "旋轉後仍然有一半是有序的——二分搜尋的變形。",
    },
    {
        "num": 34,
        "en": "Find First and Last Position of Element in Sorted Array",
        "zh": "在排序陣列中查找元素的第一個和最後一個位置",
        "difficulty": "Medium",
        "tags": ["陣列", "二分搜尋"],
        "desc": "左界與右界兩次二分，以及 bisect 的對應關係。",
    },
    {
        "num": 35,
        "en": "Search Insert Position",
        "zh": "搜尋插入位置",
        "difficulty": "Easy",
        "tags": ["陣列", "二分搜尋"],
        "desc": "二分搜尋的標準模板，重點在迴圈不變式。",
    },
    {
        "num": 36,
        "en": "Valid Sudoku",
        "zh": "有效的數獨",
        "difficulty": "Medium",
        "tags": ["陣列", "雜湊表", "矩陣"],
        "desc": "三組集合一趟掃完，宮格索引的公式推導。",
    },
    {
        "num": 37,
        "en": "Sudoku Solver",
        "zh": "解數獨",
        "difficulty": "Hard",
        "tags": ["陣列", "回溯", "矩陣"],
        "desc": "回溯 + 約束傳播，以及位元遮罩的加速。",
    },
    {
        "num": 38,
        "en": "Count and Say",
        "zh": "外觀數列",
        "difficulty": "Medium",
        "tags": ["字串"],
        "desc": "逐層產生，用雙指標數連續相同字元。",
    },
    {
        "num": 39,
        "en": "Combination Sum",
        "zh": "組合總和",
        "difficulty": "Medium",
        "tags": ["陣列", "回溯"],
        "desc": "可重複取用的回溯，用起始索引避免重複組合。",
    },
    {
        "num": 40,
        "en": "Combination Sum II",
        "zh": "組合總和 II",
        "difficulty": "Medium",
        "tags": ["陣列", "回溯"],
        "desc": "每個元素只能用一次 + 有重複元素，去重是重點。",
    },
    {
        "num": 41,
        "en": "First Missing Positive",
        "zh": "缺失的第一個正數",
        "difficulty": "Hard",
        "tags": ["陣列", "雜湊表"],
        "desc": "O(n) 時間 O(1) 空間：把陣列自己當成雜湊表。",
    },
    {
        "num": 42,
        "en": "Trapping Rain Water",
        "zh": "接雨水",
        "difficulty": "Hard",
        "tags": ["陣列", "雙指標", "動態規劃", "堆疊"],
        "desc": "四種解法：暴力、前後綴極值、單調堆疊、雙指標。",
    },
    {
        "num": 43,
        "en": "Multiply Strings",
        "zh": "字串相乘",
        "difficulty": "Medium",
        "tags": ["數學", "字串", "模擬"],
        "desc": "直式乘法的索引規律：i + j 與 i + j + 1。",
    },
    {
        "num": 44,
        "en": "Wildcard Matching",
        "zh": "通配符匹配",
        "difficulty": "Hard",
        "tags": ["字串", "動態規劃", "貪心"],
        "desc": "與 10 題對照：* 的語意不同導致貪心可行。",
    },
    {
        "num": 45,
        "en": "Jump Game II",
        "zh": "跳躍遊戲 II",
        "difficulty": "Medium",
        "tags": ["陣列", "貪心", "動態規劃"],
        "desc": "把它看成 BFS 分層，貪心就自然了。",
    },
    {
        "num": 46,
        "en": "Permutations",
        "zh": "全排列",
        "difficulty": "Medium",
        "tags": ["陣列", "回溯"],
        "desc": "交換法與 used 陣列法兩種回溯骨架。",
    },
    {
        "num": 47,
        "en": "Permutations II",
        "zh": "全排列 II",
        "difficulty": "Medium",
        "tags": ["陣列", "回溯"],
        "desc": "有重複元素時的去重規則與它的正確性。",
    },
    {
        "num": 48,
        "en": "Rotate Image",
        "zh": "旋轉圖像",
        "difficulty": "Medium",
        "tags": ["陣列", "數學", "矩陣"],
        "desc": "轉置 + 翻轉，以及四點一組的原地旋轉。",
    },
    {
        "num": 49,
        "en": "Group Anagrams",
        "zh": "字母異位詞分組",
        "difficulty": "Medium",
        "tags": ["陣列", "雜湊表", "字串", "排序"],
        "desc": "兩種簽章：排序後的字串與 26 維計數。",
    },
    {
        "num": 50,
        "en": "Pow(x, n)",
        "zh": "Pow(x, n)",
        "difficulty": "Medium",
        "tags": ["數學", "遞迴"],
        "desc": "快速冪：二分遞迴與位元迭代兩種寫法。",
    },
    {
        "num": 51,
        "en": "N-Queens",
        "zh": "N 皇后",
        "difficulty": "Hard",
        "tags": ["陣列", "回溯"],
        "desc": "用三組集合 O(1) 判斷衝突，對角線索引的公式。",
    },
    {
        "num": 52,
        "en": "N-Queens II",
        "zh": "N 皇后 II",
        "difficulty": "Hard",
        "tags": ["回溯"],
        "desc": "只數數量，順便介紹位元運算版本。",
    },
    {
        "num": 53,
        "en": "Maximum Subarray",
        "zh": "最大子陣列和",
        "difficulty": "Medium",
        "tags": ["陣列", "分治", "動態規劃"],
        "desc": "Kadane 演算法的推導，以及分治解法。",
    },
    {
        "num": 54,
        "en": "Spiral Matrix",
        "zh": "螺旋矩陣",
        "difficulty": "Medium",
        "tags": ["陣列", "矩陣", "模擬"],
        "desc": "四邊界收縮法，重點在中間那一行/列的重複問題。",
    },
    {
        "num": 55,
        "en": "Jump Game",
        "zh": "跳躍遊戲",
        "difficulty": "Medium",
        "tags": ["陣列", "貪心", "動態規劃"],
        "desc": "維護「能到的最遠位置」，一趟掃描。",
    },
    {
        "num": 56,
        "en": "Merge Intervals",
        "zh": "合併區間",
        "difficulty": "Medium",
        "tags": ["陣列", "排序"],
        "desc": "排序後一趟合併，區間題的通用起手式。",
    },
    {
        "num": 57,
        "en": "Insert Interval",
        "zh": "插入區間",
        "difficulty": "Medium",
        "tags": ["陣列"],
        "desc": "已排序的情況下三段式處理，不需要重新排序。",
    },
    {
        "num": 58,
        "en": "Length of Last Word",
        "zh": "最後一個單詞的長度",
        "difficulty": "Easy",
        "tags": ["字串"],
        "desc": "從尾巴掃比 split 更省空間。",
    },
    {
        "num": 59,
        "en": "Spiral Matrix II",
        "zh": "螺旋矩陣 II",
        "difficulty": "Medium",
        "tags": ["陣列", "矩陣", "模擬"],
        "desc": "54 題的反向版本，同一套邊界收縮。",
    },
    {
        "num": 60,
        "en": "Permutation Sequence",
        "zh": "排列序列",
        "difficulty": "Hard",
        "tags": ["數學", "回溯"],
        "desc": "用階乘直接算出每一位，不需要真的枚舉。",
    },
    {
        "num": 61,
        "en": "Rotate List",
        "zh": "旋轉串列",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "雙指標"],
        "desc": "成環再斷開，一趟半解決。",
    },
    {
        "num": 62,
        "en": "Unique Paths",
        "zh": "不同路徑",
        "difficulty": "Medium",
        "tags": ["數學", "動態規劃", "組合數學"],
        "desc": "DP、滾動陣列與組合數公式三種解法。",
    },
    {
        "num": 63,
        "en": "Unique Paths II",
        "zh": "不同路徑 II",
        "difficulty": "Medium",
        "tags": ["陣列", "動態規劃", "矩陣"],
        "desc": "有障礙物時的 DP，原地滾動陣列。",
    },
    {
        "num": 64,
        "en": "Minimum Path Sum",
        "zh": "最小路徑和",
        "difficulty": "Medium",
        "tags": ["陣列", "動態規劃", "矩陣"],
        "desc": "網格 DP 的標準形式，含邊界初始化的處理。",
    },
    {
        "num": 65,
        "en": "Valid Number",
        "zh": "有效數字",
        "difficulty": "Hard",
        "tags": ["字串"],
        "desc": "用狀態機把一堆 if 收斂成一張轉移表。",
    },
    {
        "num": 66,
        "en": "Plus One",
        "zh": "加一",
        "difficulty": "Easy",
        "tags": ["陣列", "數學"],
        "desc": "進位的邊界：全部是 9 的時候。",
    },
    {
        "num": 67,
        "en": "Add Binary",
        "zh": "二進位求和",
        "difficulty": "Easy",
        "tags": ["位元運算", "數學", "字串"],
        "desc": "與第 2 題同一套進位邏輯，換成字串。",
    },
    {
        "num": 68,
        "en": "Text Justification",
        "zh": "文字左右對齊",
        "difficulty": "Hard",
        "tags": ["陣列", "字串", "模擬"],
        "desc": "純模擬題，重點在把規格拆成互斥的分支。",
    },
    {
        "num": 69,
        "en": "Sqrt(x)",
        "zh": "x 的平方根",
        "difficulty": "Easy",
        "tags": ["數學", "二分搜尋"],
        "desc": "二分搜尋與牛頓法，以及浮點數為什麼不可靠。",
    },
    {
        "num": 70,
        "en": "Climbing Stairs",
        "zh": "爬樓梯",
        "difficulty": "Easy",
        "tags": ["記憶化搜尋", "數學", "動態規劃"],
        "desc": "費波那契數列：遞迴 → 記憶化 → 滾動變數 → 矩陣快速冪。",
    },
    {
        "num": 71,
        "en": "Simplify Path",
        "zh": "簡化路徑",
        "difficulty": "Medium",
        "tags": ["字串", "堆疊"],
        "desc": "split 之後用堆疊處理 . 與 .. 的四種情況。",
    },
    {
        "num": 72,
        "en": "Edit Distance",
        "zh": "編輯距離",
        "difficulty": "Medium",
        "tags": ["字串", "動態規劃"],
        "desc": "經典二維 DP，三個轉移各自對應一種編輯操作。",
    },
    {
        "num": 73,
        "en": "Set Matrix Zeroes",
        "zh": "矩陣置零",
        "difficulty": "Medium",
        "tags": ["陣列", "雜湊表", "矩陣"],
        "desc": "用第一列與第一行當標記，做到 O(1) 額外空間。",
    },
    {
        "num": 74,
        "en": "Search a 2D Matrix",
        "zh": "搜尋二維矩陣",
        "difficulty": "Medium",
        "tags": ["陣列", "二分搜尋", "矩陣"],
        "desc": "把二維攤平成一維來做二分。",
    },
    {
        "num": 75,
        "en": "Sort Colors",
        "zh": "顏色分類",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標", "排序"],
        "desc": "荷蘭國旗問題：三指標一趟分割。",
    },
    {
        "num": 76,
        "en": "Minimum Window Substring",
        "zh": "最小覆蓋子串",
        "difficulty": "Hard",
        "tags": ["雜湊表", "字串", "滑動視窗"],
        "desc": "求最小視窗的滑動視窗，收縮條件比第 3 題複雜。",
    },
    {
        "num": 77,
        "en": "Combinations",
        "zh": "組合",
        "difficulty": "Medium",
        "tags": ["回溯"],
        "desc": "回溯 + 剪枝，剪枝條件的推導。",
    },
    {
        "num": 78,
        "en": "Subsets",
        "zh": "子集",
        "difficulty": "Medium",
        "tags": ["位元運算", "陣列", "回溯"],
        "desc": "回溯、迭代擴充與位元枚舉三種解法。",
    },
    {
        "num": 79,
        "en": "Word Search",
        "zh": "單詞搜索",
        "difficulty": "Medium",
        "tags": ["陣列", "回溯", "矩陣"],
        "desc": "網格回溯，原地標記避免額外的 visited 陣列。",
    },
    {
        "num": 80,
        "en": "Remove Duplicates from Sorted Array II",
        "zh": "刪除有序陣列中的重複項 II",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標"],
        "desc": "把 26 題推廣成「最多保留 k 個」的通用寫法。",
    },
    {
        "num": 81,
        "en": "Search in Rotated Sorted Array II",
        "zh": "搜尋旋轉排序陣列 II",
        "difficulty": "Medium",
        "tags": ["陣列", "二分搜尋"],
        "desc": "有重複元素時，為什麼最壞情況會退化成 O(n)。",
    },
    {
        "num": 82,
        "en": "Remove Duplicates from Sorted List II",
        "zh": "刪除排序串列中的重複元素 II",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "雙指標"],
        "desc": "刪除「所有」重複的節點，虛擬頭節點必備。",
    },
    {
        "num": 83,
        "en": "Remove Duplicates from Sorted List",
        "zh": "刪除排序串列中的重複元素",
        "difficulty": "Easy",
        "tags": ["鏈結串列"],
        "desc": "每組只留一個，與 82 題的差別在哪。",
    },
    {
        "num": 84,
        "en": "Largest Rectangle in Histogram",
        "zh": "柱狀圖中最大的矩形",
        "difficulty": "Hard",
        "tags": ["陣列", "堆疊", "單調堆疊"],
        "desc": "單調遞增堆疊：每根柱子被彈出時就是它的答案。",
    },
    {
        "num": 85,
        "en": "Maximal Rectangle",
        "zh": "最大矩形",
        "difficulty": "Hard",
        "tags": ["陣列", "動態規劃", "堆疊", "矩陣"],
        "desc": "逐列轉成直方圖，直接套 84 題。",
    },
    {
        "num": 86,
        "en": "Partition List",
        "zh": "分隔串列",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "雙指標"],
        "desc": "兩條串列各自接好再串起來。",
    },
    {
        "num": 87,
        "en": "Scramble String",
        "zh": "擾亂字串",
        "difficulty": "Hard",
        "tags": ["字串", "動態規劃"],
        "desc": "區間 DP + 記憶化，以及剪枝為什麼關鍵。",
    },
    {
        "num": 88,
        "en": "Merge Sorted Array",
        "zh": "合併兩個有序陣列",
        "difficulty": "Easy",
        "tags": ["陣列", "雙指標", "排序"],
        "desc": "從後往前填，避免覆蓋未處理的元素。",
    },
    {
        "num": 89,
        "en": "Gray Code",
        "zh": "格雷編碼",
        "difficulty": "Medium",
        "tags": ["位元運算", "數學", "回溯"],
        "desc": "i ^ (i >> 1) 這條公式怎麼來的。",
    },
    {
        "num": 90,
        "en": "Subsets II",
        "zh": "子集 II",
        "difficulty": "Medium",
        "tags": ["位元運算", "陣列", "回溯"],
        "desc": "有重複元素的子集去重。",
    },
    {
        "num": 91,
        "en": "Decode Ways",
        "zh": "解碼方法",
        "difficulty": "Medium",
        "tags": ["字串", "動態規劃"],
        "desc": "帶條件的費波那契，0 的處理是關鍵。",
    },
    {
        "num": 92,
        "en": "Reverse Linked List II",
        "zh": "反轉串列 II",
        "difficulty": "Medium",
        "tags": ["鏈結串列"],
        "desc": "頭插法一趟完成，不需要先找長度。",
    },
    {
        "num": 93,
        "en": "Restore IP Addresses",
        "zh": "復原 IP 位址",
        "difficulty": "Medium",
        "tags": ["字串", "回溯"],
        "desc": "回溯 + 三個合法性條件的剪枝。",
    },
    {
        "num": 94,
        "en": "Binary Tree Inorder Traversal",
        "zh": "二元樹的中序走訪",
        "difficulty": "Easy",
        "tags": ["堆疊", "樹", "深度優先搜尋"],
        "desc": "遞迴、堆疊迭代與 Morris 走訪（O(1) 空間）。",
    },
    {
        "num": 95,
        "en": "Unique Binary Search Trees II",
        "zh": "不同的二元搜尋樹 II",
        "difficulty": "Medium",
        "tags": ["動態規劃", "回溯", "樹"],
        "desc": "分治遞迴建樹，以及為什麼可以共用子樹。",
    },
    {
        "num": 96,
        "en": "Unique Binary Search Trees",
        "zh": "不同的二元搜尋樹",
        "difficulty": "Medium",
        "tags": ["數學", "動態規劃", "樹"],
        "desc": "卡塔蘭數：DP 遞推與封閉公式。",
    },
    {
        "num": 97,
        "en": "Interleaving String",
        "zh": "交錯字串",
        "difficulty": "Medium",
        "tags": ["字串", "動態規劃"],
        "desc": "二維 DP，為什麼貪心與雙指標都不行。",
    },
    {
        "num": 98,
        "en": "Validate Binary Search Tree",
        "zh": "驗證二元搜尋樹",
        "difficulty": "Medium",
        "tags": ["樹", "深度優先搜尋", "二元搜尋樹"],
        "desc": "上下界遞迴與中序走訪兩種解法，以及最常見的錯誤寫法。",
    },
    {
        "num": 99,
        "en": "Recover Binary Search Tree",
        "zh": "復原二元搜尋樹",
        "difficulty": "Medium",
        "tags": ["樹", "深度優先搜尋", "二元搜尋樹"],
        "desc": "中序走訪找出兩個逆序點，Morris 走訪做到 O(1) 空間。",
    },
    {
        "num": 100,
        "en": "Same Tree",
        "zh": "相同的樹",
        "difficulty": "Easy",
        "tags": ["樹", "深度優先搜尋", "廣度優先搜尋"],
        "desc": "遞迴與迭代，樹題目的最小起點。",
    },
    {
        "num": 101,
        "en": "Symmetric Tree",
        "zh": "對稱二元樹",
        "difficulty": "Easy",
        "tags": ["樹", "深度優先搜尋", "廣度優先搜尋"],
        "desc": "鏡像遞迴：「左對右、右對左」，以及迭代版的成對推進。",
    },
    {
        "num": 102,
        "en": "Binary Tree Level Order Traversal",
        "zh": "二元樹的層序走訪",
        "difficulty": "Medium",
        "tags": ["樹", "廣度優先搜尋"],
        "desc": "BFS 分層的標準範本，以及 DFS 也能做到的理由。",
    },
    {
        "num": 103,
        "en": "Binary Tree Zigzag Level Order Traversal",
        "zh": "二元樹的鋸齒層序走訪",
        "difficulty": "Medium",
        "tags": ["樹", "廣度優先搜尋"],
        "desc": "層序加上方向翻轉：反轉法與雙端佇列法。",
    },
    {
        "num": 104,
        "en": "Maximum Depth of Binary Tree",
        "zh": "二元樹的最大深度",
        "difficulty": "Easy",
        "tags": ["樹", "深度優先搜尋", "廣度優先搜尋"],
        "desc": "樹遞迴模板的最小範例，三行解完。",
    },
    {
        "num": 105,
        "en": "Construct Binary Tree from Preorder and Inorder Traversal",
        "zh": "從前序與中序走訪序列建構二元樹",
        "difficulty": "Medium",
        "tags": ["陣列", "雜湊表", "分治", "樹"],
        "desc": "前序定根、中序分邊，從 O(n²) 優化到 O(n)。",
    },
    {
        "num": 106,
        "en": "Construct Binary Tree from Inorder and Postorder Traversal",
        "zh": "從中序與後序走訪序列建構二元樹",
        "difficulty": "Medium",
        "tags": ["陣列", "雜湊表", "分治", "樹"],
        "desc": "後序倒著看就是「根右左」，與第 105 題的完整對照。",
    },
    {
        "num": 107,
        "en": "Binary Tree Level Order Traversal II",
        "zh": "二元樹的層序走訪 II",
        "difficulty": "Medium",
        "tags": ["樹", "廣度優先搜尋"],
        "desc": "由下而上的層序：為什麼最後反轉比 insert(0) 好。",
    },
    {
        "num": 108,
        "en": "Convert Sorted Array to Binary Search Tree",
        "zh": "將有序陣列轉換為二元搜尋樹",
        "difficulty": "Easy",
        "tags": ["陣列", "分治", "樹", "二元搜尋樹"],
        "desc": "取中點當根，以及平衡性的證明。",
    },
    {
        "num": 109,
        "en": "Convert Sorted List to Binary Search Tree",
        "zh": "將有序鏈結串列轉換為二元搜尋樹",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "分治", "樹", "二元搜尋樹"],
        "desc": "快慢指標找中點，以及「中序建樹」的 O(n) 神解。",
    },
    {
        "num": 110,
        "en": "Balanced Binary Tree",
        "zh": "平衡二元樹",
        "difficulty": "Easy",
        "tags": ["樹", "深度優先搜尋"],
        "desc": "後序回傳一包資訊：從 O(n²) 到 O(n)。",
    },
    {
        "num": 111,
        "en": "Minimum Depth of Binary Tree",
        "zh": "二元樹的最小深度",
        "difficulty": "Easy",
        "tags": ["樹", "深度優先搜尋", "廣度優先搜尋"],
        "desc": "和第 104 題的關鍵差異：單邊為空時不能取 min。",
    },
    {
        "num": 112,
        "en": "Path Sum",
        "zh": "路徑總和",
        "difficulty": "Easy",
        "tags": ["樹", "深度優先搜尋"],
        "desc": "葉節點的定義，以及有負數時為何不能剪枝。",
    },
    {
        "num": 113,
        "en": "Path Sum II",
        "zh": "路徑總和 II",
        "difficulty": "Medium",
        "tags": ["樹", "深度優先搜尋", "回溯"],
        "desc": "回溯記錄路徑，以及「存之前要複製一份」的理由。",
    },
    {
        "num": 114,
        "en": "Flatten Binary Tree to Linked List",
        "zh": "二元樹展開為鏈結串列",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "堆疊", "樹", "深度優先搜尋"],
        "desc": "反向後序與 Morris 兩種寫法，O(1) 空間解。",
    },
    {
        "num": 115,
        "en": "Distinct Subsequences",
        "zh": "不同的子序列",
        "difficulty": "Hard",
        "tags": ["字串", "動態規劃"],
        "desc": "二維 DP 的「用或不用」，以及滾動時為何要倒著更新。",
    },
    {
        "num": 116,
        "en": "Populating Next Right Pointers in Each Node",
        "zh": "填充每個節點的下一個右側節點指標",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "樹", "深度優先搜尋", "廣度優先搜尋"],
        "desc": "利用完美二元樹的性質做到 O(1) 空間。",
    },
    {
        "num": 117,
        "en": "Populating Next Right Pointers in Each Node II",
        "zh": "填充每個節點的下一個右側節點指標 II",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "樹", "深度優先搜尋", "廣度優先搜尋"],
        "desc": "任意二元樹版：用「上一層已接好的 next 鏈」當佇列。",
    },
    {
        "num": 118,
        "en": "Pascal's Triangle",
        "zh": "楊輝三角",
        "difficulty": "Easy",
        "tags": ["陣列", "動態規劃"],
        "desc": "最乾淨的 DP 入門，以及每一項就是組合數。",
    },
    {
        "num": 119,
        "en": "Pascal's Triangle II",
        "zh": "楊輝三角 II",
        "difficulty": "Easy",
        "tags": ["陣列", "動態規劃"],
        "desc": "O(k) 空間要倒著更新，以及用乘除直接算組合數。",
    },
    {
        "num": 120,
        "en": "Triangle",
        "zh": "三角形最小路徑和",
        "difficulty": "Medium",
        "tags": ["陣列", "動態規劃"],
        "desc": "由下而上的 DP 為什麼比由上而下乾淨得多。",
    },
    {
        "num": 121,
        "en": "Best Time to Buy and Sell Stock",
        "zh": "買賣股票的最佳時機",
        "difficulty": "Easy",
        "tags": ["陣列", "動態規劃"],
        "desc": "一趟掃描記錄歷史最低點，以及它和最大子陣列的等價性。",
    },
    {
        "num": 122,
        "en": "Best Time to Buy and Sell Stock II",
        "zh": "買賣股票的最佳時機 II",
        "difficulty": "Medium",
        "tags": ["陣列", "貪心", "動態規劃"],
        "desc": "貪心為何正確：把所有上漲區間加起來。",
    },
    {
        "num": 123,
        "en": "Best Time to Buy and Sell Stock III",
        "zh": "買賣股票的最佳時機 III",
        "difficulty": "Hard",
        "tags": ["陣列", "動態規劃"],
        "desc": "四個狀態變數，以及它和第 188 題的關係。",
    },
    {
        "num": 124,
        "en": "Binary Tree Maximum Path Sum",
        "zh": "二元樹中的最大路徑和",
        "difficulty": "Hard",
        "tags": ["樹", "深度優先搜尋", "動態規劃"],
        "desc": "「回傳給父節點的值」和「答案」為什麼是兩件事。",
    },
    {
        "num": 125,
        "en": "Valid Palindrome",
        "zh": "驗證回文串",
        "difficulty": "Easy",
        "tags": ["雙指標", "字串"],
        "desc": "雙指標跳過非英數字元，以及大小寫與 Unicode 的坑。",
    },
    {
        "num": 126,
        "en": "Word Ladder II",
        "zh": "單詞接龍 II",
        "difficulty": "Hard",
        "tags": ["雜湊表", "字串", "回溯", "廣度優先搜尋"],
        "desc": "BFS 分層建圖 + DFS 回溯，找出所有最短路徑。",
    },
    {
        "num": 127,
        "en": "Word Ladder",
        "zh": "單詞接龍",
        "difficulty": "Hard",
        "tags": ["雜湊表", "字串", "廣度優先搜尋"],
        "desc": "BFS 求最短路，萬用字元建圖與雙向 BFS 的加速。",
    },
    {
        "num": 128,
        "en": "Longest Consecutive Sequence",
        "zh": "最長連續序列",
        "difficulty": "Medium",
        "tags": ["陣列", "雜湊表", "聯合查找"],
        "desc": "O(n) 的關鍵：只從「序列的起點」開始數。",
    },
    {
        "num": 129,
        "en": "Sum Root to Leaf Numbers",
        "zh": "求根節點到葉節點數字之和",
        "difficulty": "Medium",
        "tags": ["樹", "深度優先搜尋"],
        "desc": "把路徑當成一個數字往下傳。",
    },
    {
        "num": 130,
        "en": "Surrounded Regions",
        "zh": "被圍繞的區域",
        "difficulty": "Medium",
        "tags": ["陣列", "深度優先搜尋", "廣度優先搜尋", "聯合查找", "矩陣"],
        "desc": "反過來想：從邊界出發，標記「不會被圍」的 O。",
    },
    {
        "num": 131,
        "en": "Palindrome Partitioning",
        "zh": "分割回文串",
        "difficulty": "Medium",
        "tags": ["字串", "動態規劃", "回溯"],
        "desc": "回溯 + 回文表預處理。",
    },
    {
        "num": 132,
        "en": "Palindrome Partitioning II",
        "zh": "分割回文串 II",
        "difficulty": "Hard",
        "tags": ["字串", "動態規劃"],
        "desc": "兩層 DP：先算回文表，再算最少切幾刀。",
    },
    {
        "num": 133,
        "en": "Clone Graph",
        "zh": "複製圖",
        "difficulty": "Medium",
        "tags": ["雜湊表", "深度優先搜尋", "廣度優先搜尋", "圖"],
        "desc": "用雜湊表記錄「原節點 → 新節點」來處理環。",
    },
    {
        "num": 134,
        "en": "Gas Station",
        "zh": "加油站",
        "difficulty": "Medium",
        "tags": ["陣列", "貪心"],
        "desc": "貪心的正確性證明：為什麼「失敗點的下一站」一定是答案。",
    },
    {
        "num": 135,
        "en": "Candy",
        "zh": "分發糖果",
        "difficulty": "Hard",
        "tags": ["陣列", "貪心"],
        "desc": "左右各掃一遍取最大值，以及它為何是最小解。",
    },
    {
        "num": 136,
        "en": "Single Number",
        "zh": "只出現一次的數字",
        "difficulty": "Easy",
        "tags": ["陣列", "位元運算"],
        "desc": "XOR 的三個性質，一行解完。",
    },
    {
        "num": 137,
        "en": "Single Number II",
        "zh": "只出現一次的數字 II",
        "difficulty": "Medium",
        "tags": ["陣列", "位元運算"],
        "desc": "逐位數 mod 3，以及兩個狀態變數的位元魔法。",
    },
    {
        "num": 138,
        "en": "Copy List with Random Pointer",
        "zh": "複製帶隨機指標的鏈結串列",
        "difficulty": "Medium",
        "tags": ["雜湊表", "鏈結串列"],
        "desc": "雜湊表法，以及「原地交錯」的 O(1) 空間解。",
    },
    {
        "num": 139,
        "en": "Word Break",
        "zh": "單詞拆分",
        "difficulty": "Medium",
        "tags": ["陣列", "雜湊表", "字串", "動態規劃", "字典樹", "記憶化搜尋"],
        "desc": "一維 DP，以及為什麼貪心一定會錯。",
    },
    {
        "num": 140,
        "en": "Word Break II",
        "zh": "單詞拆分 II",
        "difficulty": "Hard",
        "tags": ["陣列", "雜湊表", "字串", "動態規劃", "回溯"],
        "desc": "記憶化回溯，以及先用第 139 題做可行性剪枝。",
    },
    {
        "num": 141,
        "en": "Linked List Cycle",
        "zh": "環形鏈結串列",
        "difficulty": "Easy",
        "tags": ["雜湊表", "鏈結串列", "雙指標"],
        "desc": "Floyd 快慢指標為什麼一定會相遇。",
    },
    {
        "num": 142,
        "en": "Linked List Cycle II",
        "zh": "環形鏈結串列 II",
        "difficulty": "Medium",
        "tags": ["雜湊表", "鏈結串列", "雙指標"],
        "desc": "相遇點到環入口的距離推導（完整證明）。",
    },
    {
        "num": 143,
        "en": "Reorder List",
        "zh": "重排鏈結串列",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "雙指標", "堆疊", "遞迴"],
        "desc": "找中點 + 反轉後半 + 交錯合併，三個基本功的組合。",
    },
    {
        "num": 144,
        "en": "Binary Tree Preorder Traversal",
        "zh": "二元樹的前序走訪",
        "difficulty": "Easy",
        "tags": ["堆疊", "樹", "深度優先搜尋"],
        "desc": "遞迴、堆疊、Morris 三種寫法。",
    },
    {
        "num": 145,
        "en": "Binary Tree Postorder Traversal",
        "zh": "二元樹的後序走訪",
        "difficulty": "Easy",
        "tags": ["堆疊", "樹", "深度優先搜尋"],
        "desc": "後序迭代為什麼最難，以及「反向前序」的取巧。",
    },
    {
        "num": 146,
        "en": "LRU Cache",
        "zh": "LRU 快取",
        "difficulty": "Medium",
        "tags": ["雜湊表", "鏈結串列", "設計", "雙向鏈結串列"],
        "desc": "雜湊表 + 雙向鏈結串列，以及 OrderedDict 的捷徑。",
    },
    {
        "num": 147,
        "en": "Insertion Sort List",
        "zh": "對鏈結串列進行插入排序",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "排序"],
        "desc": "鏈結串列上的插入排序，以及「已經有序就跳過」的優化。",
    },
    {
        "num": 148,
        "en": "Sort List",
        "zh": "排序鏈結串列",
        "difficulty": "Medium",
        "tags": ["鏈結串列", "雙指標", "分治", "排序", "歸併排序"],
        "desc": "自頂向下與自底向上的歸併排序，真正的 O(1) 空間解。",
    },
    {
        "num": 149,
        "en": "Max Points on a Line",
        "zh": "直線上最多的點數",
        "difficulty": "Hard",
        "tags": ["陣列", "雜湊表", "數學", "幾何"],
        "desc": "用最簡分數而不是浮點斜率，以及 gcd 正規化的細節。",
    },
    {
        "num": 150,
        "en": "Evaluate Reverse Polish Notation",
        "zh": "逆波蘭表達式求值",
        "difficulty": "Medium",
        "tags": ["陣列", "數學", "堆疊"],
        "desc": "堆疊求值，以及 Python 整數除法的方向陷阱。",
    },
    {
        "num": 151,
        "en": "Reverse Words in a String",
        "zh": "反轉字串中的單詞",
        "difficulty": "Medium",
        "tags": ["雙指標", "字串"],
        "desc": "原地反轉三部曲，以及 Python 一行解為何不算解。",
    },
    {
        "num": 152,
        "en": "Maximum Product Subarray",
        "zh": "乘積最大子陣列",
        "difficulty": "Medium",
        "tags": ["陣列", "動態規劃"],
        "desc": "同時追蹤最大與最小值，因為負負得正。",
    },
    {
        "num": 153,
        "en": "Find Minimum in Rotated Sorted Array",
        "zh": "尋找旋轉排序陣列中的最小值",
        "difficulty": "Medium",
        "tags": ["陣列", "二分搜尋"],
        "desc": "和 nums[right] 比較而不是 nums[left]，以及原因。",
    },
    {
        "num": 154,
        "en": "Find Minimum in Rotated Sorted Array II",
        "zh": "尋找旋轉排序陣列中的最小值 II",
        "difficulty": "Hard",
        "tags": ["陣列", "二分搜尋"],
        "desc": "重複元素為何讓最壞情況退化成 O(n)。",
    },
    {
        "num": 155,
        "en": "Min Stack",
        "zh": "最小堆疊",
        "difficulty": "Medium",
        "tags": ["堆疊", "設計"],
        "desc": "同步輔助堆疊、只存最小值、以及只用一個堆疊的差值法。",
    },
    {
        "num": 160,
        "en": "Intersection of Two Linked Lists",
        "zh": "相交鏈結串列",
        "difficulty": "Easy",
        "tags": ["雜湊表", "鏈結串列", "雙指標"],
        "desc": "兩個指標換軌道：為什麼一定會在交點相遇。",
    },
    {
        "num": 162,
        "en": "Find Peak Element",
        "zh": "尋找峰值",
        "difficulty": "Medium",
        "tags": ["陣列", "二分搜尋"],
        "desc": "二分搜尋為什麼能用在沒排序的陣列上。",
    },
    {
        "num": 164,
        "en": "Maximum Gap",
        "zh": "最大間距",
        "difficulty": "Hard",
        "tags": ["陣列", "排序", "桶排序", "基數排序"],
        "desc": "鴿籠原理 + 桶排序，做到線性時間。",
    },
    {
        "num": 165,
        "en": "Compare Version Numbers",
        "zh": "比較版本號",
        "difficulty": "Medium",
        "tags": ["雙指標", "字串"],
        "desc": "不切割字串的雙指標寫法，以及前導零與補零。",
    },
    {
        "num": 166,
        "en": "Fraction to Recurring Decimal",
        "zh": "分數到小數",
        "difficulty": "Medium",
        "tags": ["雜湊表", "數學", "字串"],
        "desc": "用雜湊表記錄餘數出現的位置來抓出循環節。",
    },
    {
        "num": 167,
        "en": "Two Sum II - Input Array Is Sorted",
        "zh": "兩數之和 II - 輸入有序陣列",
        "difficulty": "Medium",
        "tags": ["陣列", "雙指標", "二分搜尋"],
        "desc": "對撞雙指標，以及它的正確性證明。",
    },
    {
        "num": 168,
        "en": "Excel Sheet Column Title",
        "zh": "Excel 表欄位名稱",
        "difficulty": "Easy",
        "tags": ["數學", "字串"],
        "desc": "沒有 0 的 26 進位：為什麼每一步都要先減 1。",
    },
    {
        "num": 169,
        "en": "Majority Element",
        "zh": "多數元素",
        "difficulty": "Easy",
        "tags": ["陣列", "雜湊表", "分治", "排序", "計數"],
        "desc": "Boyer-Moore 投票法，以及它為什麼一定對。",
    },
    {
        "num": 171,
        "en": "Excel Sheet Column Number",
        "zh": "Excel 表欄位序號",
        "difficulty": "Easy",
        "tags": ["數學", "字串"],
        "desc": "第 168 題的反向運算。",
    },
    {
        "num": 172,
        "en": "Factorial Trailing Zeroes",
        "zh": "階乘後的零",
        "difficulty": "Medium",
        "tags": ["數學"],
        "desc": "數 5 的個數，以及 Legendre 公式。",
    },
    {
        "num": 173,
        "en": "Binary Search Tree Iterator",
        "zh": "二元搜尋樹迭代器",
        "difficulty": "Medium",
        "tags": ["堆疊", "樹", "設計", "二元搜尋樹", "迭代器"],
        "desc": "把中序走訪拆成 next()，以及攤還 O(1) 的分析。",
    },
    {
        "num": 174,
        "en": "Dungeon Game",
        "zh": "地下城遊戲",
        "difficulty": "Hard",
        "tags": ["陣列", "動態規劃", "矩陣"],
        "desc": "為什麼一定要從終點倒著算回來。",
    },
    {
        "num": 179,
        "en": "Largest Number",
        "zh": "最大數",
        "difficulty": "Medium",
        "tags": ["陣列", "字串", "貪心", "排序"],
        "desc": "自訂比較器 a+b vs b+a，以及它確實是全序的證明。",
    },
    {
        "num": 187,
        "en": "Repeated DNA Sequences",
        "zh": "重複的 DNA 序列",
        "difficulty": "Medium",
        "tags": ["雜湊表", "字串", "位元運算", "滑動視窗", "雜湊函數"],
        "desc": "滑動視窗 + 集合，以及 Rabin-Karp 的位元編碼。",
    },
    {
        "num": 188,
        "en": "Best Time to Buy and Sell Stock IV",
        "zh": "買賣股票的最佳時機 IV",
        "difficulty": "Hard",
        "tags": ["陣列", "動態規劃"],
        "desc": "k 次交易的通用 DP，以及 k 夠大時如何退化成第 122 題。",
    },
    {
        "num": 189,
        "en": "Rotate Array",
        "zh": "輪轉陣列",
        "difficulty": "Medium",
        "tags": ["陣列", "數學", "雙指標"],
        "desc": "三次反轉，以及環狀替換法為何需要 gcd。",
    },
    {
        "num": 190,
        "en": "Reverse Bits",
        "zh": "顛倒二進位位元",
        "difficulty": "Easy",
        "tags": ["位元運算", "分治"],
        "desc": "逐位反轉與分治交換，以及查表法。",
    },
    {
        "num": 191,
        "en": "Number of 1 Bits",
        "zh": "位元 1 的個數",
        "difficulty": "Easy",
        "tags": ["位元運算"],
        "desc": "n & (n-1) 消去最低位的 1。",
    },
    {
        "num": 198,
        "en": "House Robber",
        "zh": "打家劫舍",
        "difficulty": "Medium",
        "tags": ["陣列", "動態規劃"],
        "desc": "最基本的「選或不選」DP，滾動兩個變數。",
    },
    {
        "num": 199,
        "en": "Binary Tree Right Side View",
        "zh": "二元樹的右視圖",
        "difficulty": "Medium",
        "tags": ["樹", "深度優先搜尋", "廣度優先搜尋"],
        "desc": "BFS 取每層最後一個，DFS 先走右邊。",
    },
    {
        "num": 200,
        "en": "Number of Islands",
        "zh": "島嶼數量",
        "difficulty": "Medium",
        "tags": ["陣列", "深度優先搜尋", "廣度優先搜尋", "聯合查找", "矩陣"],
        "desc": "洪水填充的標準範本：DFS、BFS、並查集三種解法。",
    },
]

DIFFICULTY_ZH = {"Easy": "簡單", "Medium": "中等", "Hard": "困難"}

# 側邊欄與主題頁的分組：每 25 題一組，題目變多時自動延伸。
GROUP_SIZE = 25


def group_label(num):
    start = ((num - 1) // GROUP_SIZE) * GROUP_SIZE + 1
    return u"第 %03d–%03d 題" % (start, start + GROUP_SIZE - 1)


def grouped():
    """回傳 [(group_label, [problem, ...]), ...]，依題號排序。"""
    out = []
    for p in sorted(PROBLEMS, key=lambda x: x["num"]):
        label = group_label(p["num"])
        if not out or out[-1][0] != label:
            out.append((label, []))
        out[-1][1].append(p)
    return out


def course_title(p):
    return u"%d. %s %s" % (p["num"], p["en"], p["zh"])


def slug(p):
    return u"problem-%04d" % p["num"]
